### ISSUE TITLE
Recursive upload issue

### ISSUE THREAD

**Issue by jurecotic** [yadayada/acd_cli#10]
When I try to upload a folder which has already been uploaded (to sync new files) I now get:

```
Traceback (most recent call last):
  File "./acd_cli.py", line 546, in <module>
    main()
  File "./acd_cli.py", line 542, in main
    args.func(args)
  File "./acd_cli.py", line 263, in upload_action
    upload(path, args.parent, args.overwrite, args.force)
  File "./acd_cli.py", line 63, in upload
    upload_folder(path, parent_id, overwr, force)
  File "./acd_cli.py", line 160, in upload_folder
    upload(full_path, curr_node.id, overwr, force)
  File "./acd_cli.py", line 63, in upload
    upload_folder(path, parent_id, overwr, force)
  File "./acd_cli.py", line 160, in upload_folder
    upload(full_path, curr_node.id, overwr, force)
  File "./acd_cli.py", line 66, in upload
    upload_file(path, parent_id, overwr, force)
  File "./acd_cli.py", line 102, in upload_file
    mod_time = mod_time.timestamp()
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'
```

I'm on latest master and have already tried clearing the cache and resyncing.

**Comment by yadayada** [comment]
The timestamp method was added in version 3.3. 
You can change the offending line to:

```python
mod_time = (cached_file.modified - datetime.datetime(1970, 1, 1)) / datetime.timedelta(seconds=1)
```

Did this occur on your 14.04 machine again?

**Comment by jurecotic** [comment]
No, this occurred on my RaspberryPi. I can confirm, that manually building Python 3.3 fixes this problem.

**Comment by yadayada** [comment]
Changed it anyway. So this should no longer occur in d5372275e492b29710d477de1851b613a6f018b9.
