### ISSUE TITLE
Error on sync: Invalid authentication token: Invalid JSON or missing key.

### ISSUE THREAD

**Issue by metalgeekstl** [yadayada/acd_cli#113]
After working for a few weeks, suddenly I'm unable to sync. 
I re-created my token but no change.
See below:

```
user@box: acd_cli$ acd_cli sync
15-08-22 11:08:41.298 [CRITICAL] [acdcli.api.oauth] - Invalid authentication token: Invalid JSON or missing key.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 42, in _create_handler
    return LocalOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 230, in __init__
    self.load_client_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 238, in load_client_data
    self.client_data = json.load(cd)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 2 column 75 (char 92)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 73, in validate
    o = json.loads(oauth)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 2 column 75 (char 92)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a5', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1230, in main
    if not common.init(CACHE_PATH):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/common.py", line 62, in init
    return oauth.init(path) and _load_endpoints()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 19, in init
    handler = _create_handler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 44, in _create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 143, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 95, in load_oauth_data
    self.oauth_data = self.validate(o)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 80, in validate
    raise RequestError(RequestError.CODE.INVALID_TOKEN, e.__str__())
acdcli.api.common.RequestError: RequestError: 1005, Invalid control character at: line 2 column 75 (char 92)
```

**Comment by yadayada** [comment]
Is the oauth_data file in the cache path valid JSON?

**Comment by metalgeekstl** [comment]
Disregard. the token was malformed after pasting it into nano for some reason.

**Comment by yadayada** [comment]
Ok. I wonder if you could provide some more information about the initial error that caused you to re-authenticate.

Is this the same error that occurred before replacing the oauth file?
Have you saved the old oauth file that you had replaced and if so, what's its content?

**Comment by metalgeekstl** [comment]
It is the same error before replacing.
I didn't save the old oauth file. I can only describe that it was formated like you see when you select "word wrap" in MS notepad. Uniformed margins and like a run-on sentence.No tabbed lines

Now it looks more formated:

    "access_token": "*********AsAhQzGaOHpTuV5w-Pyljd6YZQTAfafwIUHDNcNPRHWCBdD$
    "exp_time": 1440265064.3015833,
    "expires_in": 3600,
    "refresh_token": "*********Kq7667FvVpoHv7eqG4GprCAIUSbZ3aoIRj8v1$
    "token_type": "bearer"
}

(I obfuscated the token for security purposes.)

**Comment by yadayada** [comment]
Hmm, I can only say that the OAuth handler shouldn't have saved invalid data to disk in the first place.
