### ISSUE TITLE
acd_cli sync errors

### ISSUE THREAD

**Issue by 2marshall** [yadayada/acd_cli#117]
I got acd_cli installed and the OAuth data file stored in /root/.cache/acd_cli folder but when I goto run acd_cli sync I get these errors

```
root@debian:/scripts# acdcli sync
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 41, in _create_handler
    return LocalOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 221, in __init__
    self.load_client_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 228, in load_client_data
    with open(cdp) as cd:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/acd_cli/client_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a1', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1055, in main
    if not common.init(CACHE_PATH):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/common.py", line 60, in init
    return oauth.init(path) and _load_endpoints()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 19, in init
    handler = _create_handler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 43, in _create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 141, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 99, in load_oauth_data
    self.get_auth_token(reload=False)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 114, in get_auth_token
    self.refresh_auth_token()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 169, in refresh_auth_token
    response = requests.post(self.APPSPOT_URL, data=ref)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

**Comment by yadayada** [comment]
Please enter the last line into a search engine.

**Comment by 2marshall** [comment]
1. hmm... I found some stackoverlow articles and can see that this checks out with a 400 response when running the below command. I got this URL from oauth.py.

>>> requests.get('https://api.amazon.com/auth/o2/tokeninfo', verify=True)
<Response [400]>

The hard part is knowing the file I need to make the verify=False changes into so this SSL verify doesn't occur.

2. Do I need this file? The first error is relating to it's absence. I thought it was optional. FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/acd_cli/client_data'

**Comment by yadayada** [comment]
No, you don't need the client_data file.
I was thinking more along the lines of getting your SSL to verify correctly.

What is your SSL-Session Verify return code when you enter
```
openssl s_client -CApath /etc/ssl/certs -connect api.amazon.com:443
```
I get 0 (ok).

**Comment by 2marshall** [comment]
No, you don't need the client_data file. - thanks good to know

yah I get this

openssl s_client -CApath /etc/ssl/certs -connect api.amazon.com:443

SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES128-SHA
    Session-ID: 35302B8F81AA19FC41E26B1CF6371C23CB9588E158BADD386025A3F41DA386AF
    Session-ID-ctx:
    Master-Key: 9681FBFC9DD8B12C10AFCF89DEBF90FD33547F80F53C3470404858B0944A9DDDE3DFB69065DCF93EC373184330229779
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1423645205
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

**Comment by yadayada** [comment]
Sorry. I just noticed the error occurs don't occur with Amazon, but with the Appspot url...

Please try:
```
openssl s_client -CApath /etc/ssl/certs -connect appspot.com:443

python -c 'import requests; requests.get("https://tensile-runway-92512.appspot.com")'
```

And, to be sure:
``python -c 'import requests; requests.get("https://api.amazon.com")'``

Or, if you just want to patch, it's that line
```
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 169, in refresh_auth_token
    response = requests.post(self.APPSPOT_URL, data=ref)
```

**Comment by 2marshall** [comment]
Yep amazon is fine.  I did the following:

python -c 'import requests; requests.get("https://api.amazon.com")'
brought me back to root@debian: prompt

I than ran this and got errors. I wonder how others have gone past this.

python -c 'import requests; requests.get("https://tensile-runway-92512.appspot.com")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)

Or, if you just want to patch, it's that line

  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 169, in refresh_auth_token
    response = requests.post(self.APPSPOT_URL, data=ref)

I honestly don't watch to patch your code because when you do new updates I'll probably get the error again when I download. making it work correct would be ideal. If this is the only option I'm fine with doing it. are you saying to just comment out line 169? I tried that and re-ran acd_cli sync but got another error

File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 170
    except ConnectionError as e:


thanks for everything :)

**Comment by yadayada** [comment]
So, what about
```
openssl s_client -CApath /etc/ssl/certs -connect appspot.com:443
```

>making it work correct would be ideal. 

Well, yeah... But you're the only one with this error (so far) and access to your machine.

As it turns out, creating your own security profile, whitelisting it and creating the client_data will fix your problems after all. See https://developer.amazon.com/public/apis/experience/cloud-drive/content/getting-started.

**Comment by 2marshall** [comment]
openssl s_client -CApath /etc/ssl/certs -connect appspot.com:443

SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: DF10B9B6998AF7B8344641B7E46F7E19AF392A3C37D60710EFB3A02000D14CC9
    Session-ID-ctx:
    Master-Key: F6B15BED3D8FAEB1278DC87130FD9AB25E171249F9B7CA247BB9B690E34BF116EE80C9E68247291C0129A924797D5028
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 100800 (seconds)
    TLS session ticket:
    0000 - 80 d8 e0 c5 64 4a 42 ca-3c e2 1c b4 b5 7a 6f 7c   ....dJB.<....zo|
    0010 - be 29 8e e2 a5 f1 a0 dd-5d e4 7e b1 b6 a5 ed 92   .)......].~.....
    0020 - 1a b9 26 ab b8 86 cd 45-5c 92 06 ff ec 03 7c 9c   ..&....E\.....|.
    0030 - d7 10 8e 9e c2 72 06 06-0c 26 e0 14 27 02 95 3e   .....r...&..'..>
    0040 - 40 23 bc 76 c2 4c 0d 2c-5a 5b 6a 0b 6d 22 ce b8   @#.v.L.,Z[j.m"..
    0050 - 61 2b 2a 18 2d 3d 31 47-5c 9e b7 74 8b 43 a5 c8   a+*.-=1G\..t.C..
    0060 - 13 30 ba 10 67 60 e6 e4-d2 1b 2a c6 54 d0 f8 f3   .0..g`....*.T...
    0070 - 56 1e 8f d3 00 02 0d 76-f4 b8 71 35 bc a0 19 bc   V......v..q5....
    0080 - 0c 96 2d c1 b7 cc 3d 60-a1 d3 eb 47 6e cc b0 d0   ..-...=`...Gn...
    0090 - e7 30 94 7c 74 15 b5 82-37 06 b4 76 01 02 b6 59   .0.|t...7..v...Y
    00a0 - c2 d1 5e d5                                       ..^.

    Start Time: 1423648920
    Timeout   : 300 (sec)
    Verify return code: 9 (certificate is not yet valid)

As it turns out, creating your own security profile, whitelisting it and creating the client_data will fix your problems after all. See https://developer.amazon.com/public/apis/experience/cloud-drive/content/getting-started.

ok, I'll try this. you should update that install guide to make this required. thanks for your guidance :)

**Comment by yadayada** [comment]
Honey, is your hardware clock outdated?
```
python3 -c 'import time; print(time.time() > 1423648920)
```

**Comment by 2marshall** [comment]
ha that was it. the clock was off. haaa. so stupid of me.

**Comment by yadayada** [comment]
Well, I for one wouldn't have guessed it at first.
