### ISSUE TITLE
Can't mount

### ISSUE THREAD

**Issue by TimDowker** [yadayada/acd_cli#120]
Trying to do a simple mount.  Get the following error

```
root@Plex:~# acd_cli mount /.plex/
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a5', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1251, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 849, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/fuse.py", line 467, in mount
    FUSE(ACDFuse(**args), path, entry_timeout=60, attr_timeout=60, auto_cache=True,
  File "/usr/local/lib/python3.4/dist-packages/acdcli/fuse.py", line 248, in __init__
    self.free = self.total - query.calculate_usage()
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

Any ideas?

**Comment by yadayada** [comment]
Sorry, I have yet to commit the fix for this.
Please create a file in your cloud drive manually, sync and try again.
