### ISSUE TITLE
Missing errno.EREMOTEIO attribute on Mac OS

### ISSUE THREAD

**Issue by groman2** [yadayada/acd_cli#130]
I keep getting the following errors while attempting to rsync to my cloud drive:

```
$ acdcli version
acd_cli 0.3.0a6
$ acdcli mount -i 2 -fg ACD/
15-09-07 10:36:08.874 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:37:00.025 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:37:31.284 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:37:32.784 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:37:34.641 [ERROR] [acdcli.acd_fuse] - create: RequestError: 500, {"logref":"1fad3958-5587-11e5-baf2-f990ad51223d","message":"Internal failure","code":""}
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 391, in create
    r = self.acd_client.create_file(name, pid)
  File "/usr/local/lib/python3.4/site-packages/acdcli/api/content.py", line 122, in create_file
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 500, {"logref":"1fad3958-5587-11e5-baf2-f990ad51223d","message":"Internal failure","code":""}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/acdcli/bundled/fuse.py", line 430, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python3.4/site-packages/acdcli/bundled/fuse.py", line 661, in create
    fi.fh = self.operations('create', path, mode)
  File "/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 241, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 394, in create
    FuseOSError.convert(e)
  File "/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 68, in convert
    raise FuseOSError(errno.EREMOTEIO)
AttributeError: 'module' object has no attribute 'EREMOTEIO'
15-09-07 10:37:35.339 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:44:52.235 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:16.554 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:16.601 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:18.821 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:19.828 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:21.345 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:23.477 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:23.703 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:25.988 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:27.989 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:30.263 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:31.665 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:33.852 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:33.856 [ERROR] [acdcli.acd_fuse] - Error writing file. Code: 500, msg: {"logref":"3d5aeb63-5588-11e5-b524-6dc20b7d10e5","message":"Internal failure","code":""}
15-09-07 10:45:34.017 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:39.923 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:43.006 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:43.646 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:45.453 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:47.283 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-07 10:45:48.828 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
```

My rsync invocation is:

```
 rsync -Pauvr --inplace --whole-file --exclude ".*" --exclude ".*/" $SRC $DEST 
```

Is this expected?

**Comment by yadayada** [comment]
The errno module should always have the EREMOTEIO attribute in any Python 3 distribution, see
https://docs.python.org/3.2/library/errno.html etc.

Please mount with ``acdcli -d mount -i0 -fg ACD/`` and see what's going on or paste that log (please remove the authentication data or wait till it's invalid).

**Comment by groman2** [comment]
So after restarting it, I can't reproduce the original error (I guess my giant rsync moved onto different files that don't trigger it?), but I'm still getting errors after a whole bunch of files get transferred

```
15-09-12 16:40:31.272 [DEBUG] [fuse.log] - <- write 65536
15-09-12 16:40:31.273 [DEBUG] [fuse.log] - -> write /photos/20130608/img079p.tif (65536, 135987200, 45)
15-09-12 16:40:31.273 [DEBUG] [fuse.log] - <- write 65536
15-09-12 16:40:31.274 [DEBUG] [fuse.log] - -> write /photos/20130608/img079p.tif (65536, 136052736, 45)
15-09-12 16:41:31.277 [ERROR] [acdcli.acd_fuse] - Write timeout.
15-09-12 16:41:31.277 [DEBUG] [fuse.log] - <- write '[Errno 60] Operation timed out'
fuse: writing device: Socket is not connected
reply: 'HTTP/1.1 200 OK\r\n'
15-09-12 16:41:31.523 [WARNING] [requests.packages.urllib3.connectionpool] - Connection pool is full, discarding connection: content-na.drive.amazonaws.com
15-09-12 16:41:31.531 [DEBUG] [fuse.log] - -> destroy / ()
15-09-12 16:41:31.531 [DEBUG] [fuse.log] - <- destroy None
mbp:~ groman$ 
```
and `acdcli` died. After restarting it and restarting my rsync, it got past the `img079p.tif` file and choked on some other file:
```
15-09-12 17:33:47.008 [DEBUG] [fuse.log] - -> write /photos/20130615/D7D_5459-Edit.tif (65536, 71630848, 123)
15-09-12 17:33:47.008 [DEBUG] [fuse.log] - <- write 65536
15-09-12 17:33:47.008 [DEBUG] [fuse.log] - -> write /photos/20130615/D7D_5459-Edit.tif (65536, 71696384, 123)
15-09-12 17:33:47.009 [DEBUG] [fuse.log] - <- write 65536
15-09-12 17:33:47.009 [DEBUG] [fuse.log] - -> write /photos/20130615/D7D_5459-Edit.tif (65536, 71761920, 123)
15-09-12 17:33:47.009 [DEBUG] [fuse.log] - <- write 65536
15-09-12 17:33:47.011 [DEBUG] [fuse.log] - -> write /photos/20130615/D7D_5459-Edit.tif (65536, 71827456, 123)
15-09-12 17:34:47.014 [ERROR] [acdcli.acd_fuse] - Write timeout.
15-09-12 17:34:47.014 [DEBUG] [fuse.log] - <- write '[Errno 60] Operation timed out'
fuse: writing device: Socket is not connected
15-09-12 17:34:47.314 [DEBUG] [fuse.log] - -> destroy / ()
15-09-12 17:34:47.315 [DEBUG] [fuse.log] - <- destroy None
header: Content-Type header: Date header: Server header: x-amzn-RequestId header: Content-Length header: Connection 
mbp:~ groman $ 
```


Side question: Are these warnings about "Connection pool full" normal?

**Comment by groman2** [comment]
Any update or any more information I can provide?

**Comment by yadayada** [comment]
Side answer: The connection pool warnings are normal.

Your write blocks are higher than expected (65K >> 4K).
You could try to make the write buffer smaller, set the write_timeout to a higher value or disable the write timeout in the WriteStream write function.

E.g.
```diff
diff --git a/acdcli/acd_fuse.py b/acdcli/acd_fuse.py
index 034649d..4e6b323 100644
--- a/acdcli/acd_fuse.py
+++ b/acdcli/acd_fuse.py
@@ -23,7 +23,7 @@ MAX_CHUNKS_PER_FILE = 15
 CHUNK_TIMEOUT = 5
 
 WRITE_TIMEOUT = 60
-WRITE_BUFFER_SZ = 2 ** 10
+WRITE_BUFFER_SZ = 100
 
 MIN_AUTOSYNC_INTERVAL = 60
```

BTW, what OS are you using?

**Comment by groman2** [comment]
OS X Yosemite 10.10.4, Darwin Kernel Version 14.4.0, Python 3.4.3 (default, Aug 11 2015, 08:57:25) 

I'll try tweaking the buffer sizes/timeouts and let you know if it works. 

Thanks!

**Comment by yadayada** [comment]
Please test again with the latest dev commit.

**Comment by yadayada** [comment]
It seems EREMOTEIO is not defined in Apple's errno.h
