### ISSUE TITLE
max retries exceeded error

### ISSUE THREAD

**Issue by tooj** [yadayada/acd_cli#14]
Updated to the latest version today and I ran `acd_cli.py clear-cache` after obtaining my oauth_data.
Running `acd_cli.py sync` results in the following error on Ubuntu 14.10 server 64-bit:

```python
Syncing... Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 322, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 496, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 324, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 617, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 327, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 546, in urlopen
    raise MaxRetryError(self, url, e)
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdws.us-east-1.amazonaws.com', port=443): Max retries exceeded with url: /drive/v1/nodes?filters=kind%3AFILE&startToken=<mytoken> (Caused by <class 'ConnectionResetError'>: [Errno 104] Connection reset by peer)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myhomedir/acd_cli/acd_cli.py", line 573, in <module>
    main()
  File "/home/myhomedir/acd_cli/acd_cli.py", line 569, in main
    args.func(args)
  File "/home/myhomedir/acd_cli/acd_cli.py", line 233, in sync_action
    sync_node_list()
  File "/home/myhomedir/acd_cli/acd_cli.py", line 46, in sync_node_list
    files = metadata.get_file_list()
  File "/home/myhomedir/acd_cli/acd/metadata.py", line 20, in get_file_list
    return get_node_list(filters='kind:FILE')
  File "/home/myhomedir/acd_cli/acd/metadata.py", line 16, in get_node_list
    return paginated_get_request(oauth.get_metadata_url() + 'nodes', q_params, {})
  File "/home/myhomedir/acd_cli/acd/common.py", line 28, in paginated_get_request
    headers=dict(headers, **oauth.get_auth_header()))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdws.us-east-1.amazonaws.com', port=443): Max retries exceeded with url: /drive/v1/nodes?filters=kind%3AFILE&startToken=<mytoken> (Caused by <class 'ConnectionResetError'>: [Errno 104] Connection reset by peer)
```

**Comment by yadayada** [comment]
Seems like some sort of connection problem. Anyway, I cannot reproduce it.
