### ISSUE TITLE
FreeBSD mount error

### ISSUE THREAD

**Issue by jbondhus** [yadayada/acd_cli#141]
I'm getting the following error when I try 'acd_cli mount /mnt'. I'm running freebsd 9.3 (on a freenas jail) with the fuse kernel module loaded.

```
root@hashbackup:~ # acd_cli -d mount -i0 -fg /mnt
15-09-14 20:56:50.771 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin, ClementinePlugin, TermsOfUsePlugin
15-09-14 20:56:50.771 [INFO] [acd_cli] - TestPlugin attached.
15-09-14 20:56:50.771 [INFO] [acd_cli] - Clementine executable not found.
15-09-14 20:56:50.771 [INFO] [acd_cli] - TermsOfUsePlugin attached.
15-09-14 20:56:50.772 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
15-09-14 20:56:50.772 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
15-09-14 20:56:50.772 [INFO] [acdcli.cache.db] - Initializing cache with path "/root/.cache/acd_cli".
15-09-14 20:56:50.974 [INFO] [acdcli.cache.db] - Cache not considered uninitialized.
15-09-14 20:56:50.975 [INFO] [acdcli.cache.db] - DB schema version is 1.
15-09-14 20:56:50.984 [INFO] [acd_cli] - Last sync at 2015-09-15 01:56:33.868849.
15-09-14 20:56:51.203 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.431263s
15-09-14 20:56:51.203 [INFO] [acdcli.api.backoff_req] - GET "https://cdws.us-east-1.amazonaws.com/drive/v1/account/quota"
15-09-14 20:56:51.207 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
send: b'GET /drive/v1/account/quota HTTP/1.1
Host: cdws.us-east-1.amazonaws.com
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer REDACTEDc
User-Agent: acd_cli/0.3.0a6 python-requests/2.7.0 CPython/3.4.3 FreeBSD/9.3-RELEASE-p25

'
reply: 'HTTP/1.1 200 OK
'
15-09-14 20:56:51.419 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /drive/v1/account/quota HTTP/1.1" 200 177
header: Server header: Date header: Content-Type header: Content-Length header: Connection header: x-amzn-RequestId header: Content-Encoding header: Cache-Control header: Pragma header: Vary fuse: failed to exec mount program: No such file or directory
fuse: failed to mount file system: No error: 0
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1266, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 856, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 516, in mount
    **kwargs
  File "/usr/local/lib/python3.4/site-packages/acdcli/bundled/fuse.py", line 414, in __init__
    raise RuntimeError(err)
RuntimeError: 1
root@hashbackup:~ #
```

**Comment by HazCod** [comment]
`failed to exec mount program: No such file or directory`

Can you run `mount` ?

**Comment by jbondhus** [comment]
Can I run the command 'mount' on the shell? Yes, I can.

```
root@hashbackup:~ # mount
tank/jails/hashbackup on / (zfs, local, nfsv4acls)
root@hashbackup:~ # which mount
/sbin/mount
```

The command I'm running as root so it should have the same path as the shell environment.

**Comment by jbondhus** [comment]
Oops, didn't mean to close it, my bad.

**Comment by yadayada** [comment]
This seems like an external issue.

**Comment by jbondhus** [comment]
@yadayada If I'm executing it from the command line, shouldn't the path be the same as the path variable of the shell I'm running it from? The mount command is in /sbin/mount, that seems like it's a directory that would be added to any path by default because it contains critical binaries.

**Comment by yadayada** [comment]
If I uninstall my fuse package, I get a similar error:
```
fuse: failed to exec fusermount program: No such file or directory
```
So, I assume the fusepy module cannot execute ``mount``.

Does
```
python3 -c "import subprocess; subprocess.call('mount')"
```
work?

**Comment by jbondhus** [comment]
```
root@hashbackup:~ # python3 -c "import subprocess; subprocess.call('mount')"
tank/jails/hashbackup on / (zfs, local, nfsv4acls)
root@hashbackup:~ #
```

And here's the path it's using.

```
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin
```

**Comment by yadayada** [comment]
I'd like to see if fusepy actually works at all.

Please download fuse.py and hello.py from https://gist.github.com/yadayada/ee50fe2bee37a25ae9be,
and run
```bash
mkdir hellomnt
python3 hello.py hellomnt &
cat hellomnt/hello
```

**Comment by jbondhus** [comment]
```
root@hashbackup:~ # python3 hello.py hellomnt &
[1] 48660
root@hashbackup:~ # fuse: failed to exec mount program: No such file or directory
fuse: failed to mount file system: No error: 0
Traceback (most recent call last):
  File "hello.py", line 45, in <module>
    FUSE(HelloOperations(), path, foreground=True)
  File "/root/fuse.py", line 414, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

The kernel module is installed and loaded

```
root@hashbackup:~ # kldstat
Id Refs Address            Size     Name
 1   84 0xffffffff80200000 150d000  kernel
 2    1 0xffffffff819d8000 1781ce   ispfw.ko
 3    1 0xffffffff81c12000 48ff     geom_stripe.ko
 4    1 0xffffffff81c17000 10548    geom_raid3.ko
 5    1 0xffffffff81c28000 102dd    geom_raid5.ko
 6    1 0xffffffff81c39000 5826     geom_gate.ko
 7    1 0xffffffff81c3f000 4a1c     geom_multipath.ko
 8    1 0xffffffff81c44000 b1a      dtraceall.ko
 9    1 0xffffffff81c45000 4ed6     profile.ko
10    3 0xffffffff81c4a000 3564     cyclic.ko
11   10 0xffffffff81c4e000 3464f    dtrace.ko
12    1 0xffffffff81c83000 fef0     systrace_freebsd32.ko
13    1 0xffffffff81c93000 10be4    systrace.ko
14    1 0xffffffff81ca4000 4ade     sdt.ko
15    1 0xffffffff81ca9000 48eb     lockstat.ko
16    1 0xffffffff81cae000 b664     fasttrap.ko
17    1 0xffffffff81cba000 6697     fbt.ko
18    1 0xffffffff81cc1000 556b     dtnfscl.ko
19    1 0xffffffff81cc7000 458e     dtmalloc.ko
20    1 0xffffffff81ccc000 8849     ipmi.ko
21    1 0xffffffff81cd5000 336a0    if_cxgbe.ko
22    1 0xffffffff81d09000 46bcd    linux.ko
23    2 0xffffffff81d50000 2bb1     vboxnetflt.ko
24    2 0xffffffff81d53000 46f6c    vboxdrv.ko
25    1 0xffffffff81d9a000 44f8     ng_ether.ko
26    1 0xffffffff81d9f000 400a     vboxnetadp.ko
27    1 0xffffffff81da4000 92cb     fuse.ko
root@hashbackup:~ #
```

Also, below is a link to a list of all files on this system. If you need any more information please let me know.

https://jbondhus-sharing.s3.amazonaws.com/Persistant/2015/09%20-%20September/hashbackup.jb.local%20File%20List.txt

**Comment by yadayada** [comment]
How about an strace?

**Comment by jbondhus** [comment]
`strace` doesn't exist on FreeBSD, so I used `truss`, the FreeBSD alternative for `strace`.

https://forums.freebsd.org/threads/alternative-for-strace-on-amd64.25396/

See below for the output of `truss`.

https://jbondhus-sharing.s3.amazonaws.com/Persistant/2015/09%20-%20September/hashbackup.jb.local%20Trace%20Output.txt

**Comment by yadayada** [comment]
Unfortunately, there's not much I can tell from the trace. Ilibfuse somehow isn't able to mount.
I suppose you get the same error when you try mount other fuse filesystems...

**Comment by jbondhus** [comment]
I fixed this issue. I had to install the package `fusefs-kmod`. On freeBSD the command to do this is `pkg install fusefs-kmod`. This happens because the kernel module is loaded because the jail is using the same kernel as the host, but the kernel module is not installed as a package on the jail.
