### ISSUE TITLE
acdcli.api.common.RequestError: RequestError: 1004, Error refreshing authentication token

### ISSUE THREAD

**Issue by amaxcz** [yadayada/acd_cli#154]
we have another issue with ACD. we need to have proper error handling it ACD fails.
trying acdcli sync

```
beruska:~ amaxcz$ acdcli sync
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/api/oauth.py", line 17, in create_handler
    return LocalOAuthHandler(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/api/oauth.py", line 218, in __init__
    self.load_client_data()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/api/oauth.py", line 225, in load_client_data
    with open(cdp) as cd:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/amaxcz/Library/Caches/acd_cli/client_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acdcli')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 1275, in main
    acd_client = client.ACDClient(CACHE_PATH)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/api/client.py", line 31, in __init__
    self.handler = oauth.create_handler(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/api/oauth.py", line 19, in create_handler
    return AppspotOAuthHandler(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/api/oauth.py", line 131, in __init__
    self.load_oauth_data()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/api/oauth.py", line 75, in load_oauth_data
    self.get_auth_token(reload=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/api/oauth.py", line 90, in get_auth_token
    self.refresh_auth_token()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/api/oauth.py", line 170, in refresh_auth_token
    'Error refreshing authentication token: %s' % response.text)
acdcli.api.common.RequestError: RequestError: 1004, Error refreshing authentication token: <html>
  <head>
    <title>Internal Server Error</title>
    <style>
      body {
        padding: 20px;
        font-family: arial, sans-serif;
        font-size: 14px;
      }
      pre {
        background: #F2F2F2;
        padding: 10px;
      }
    </style>
  </head>
  <body>
    <h1>Internal Server Error</h1>
    <p>The server has either erred or is incapable of performing
    the requested operation.</p>
    <pre>Traceback (most recent call last):
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1102, in __call__
    return handler.dispatch()
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 570, in dispatch
    return method(*args, **kwargs)
  File &quot;/base/data/home/apps/s~acd-cli-oa-backup/1.387290489679662868/main.py&quot;, line 105, in post
    resp = urllib2.urlopen(AMAZON_OA_TOKEN_URL, urllib.urlencode(params), timeout=15)
  File &quot;/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py&quot;, line 127, in urlopen
    return _opener.open(url, data, timeout)
  File &quot;/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py&quot;, line 410, in open
    response = meth(req, response)
  File &quot;/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py&quot;, line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File &quot;/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py&quot;, line 448, in error
    return self._call_chain(*args)
  File &quot;/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py&quot;, line 382, in _call_chain
    result = func(*args)
  File &quot;/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib2.py&quot;, line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
</pre>
  </body>
</html>
beruska:~ amaxcz$
```

**Comment by amaxcz** [comment]
is it possible to validate HTTP error codes before exceptions occurs?

**Comment by yadayada** [comment]
The oauth app gets a 503 response from Amazon's authentication server. Yup, I could catch the exception, but that's mere formatting. 

What do you expect the AppspotOAuthHandler to do in this case?

PS: Please don't create multipe messages in rapid succession. I get sent an email for each comment.

**Comment by yadayada** [comment]
I added further exception handling to http://tensile-runway-92512.appspot.com. This should lead to a shorter error message.
