### ISSUE TITLE
sync issue

### ISSUE THREAD

**Issue by jonas5** [yadayada/acd_cli#156]
```
acdcli -v sync
15-09-26 19:18:29.223 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-09-26 19:18:29.224 [INFO] [acd_cli] - TestPlugin attached.
15-09-26 19:18:29.224 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/plex/.cache/acd_cli".
15-09-26 19:18:29.224 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
15-09-26 19:18:29.225 [INFO] [acdcli.cache.db] - Initializing cache with path "/home/plex/.cache/acd_cli".
15-09-26 19:18:29.239 [INFO] [acdcli.cache.db] - Cache not considered uninitialized.
15-09-26 19:18:29.241 [INFO] [acdcli.cache.db] - DB schema version is 1.
Syncing...
15-09-26 19:18:29.251 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "None".
15-09-26 19:18:29.251 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
15-09-26 19:18:29.255 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
15-09-26 19:19:12.828 [INFO] [acdcli.api.metadata] - Found "reset" tag in changes.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 397, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acdcli')()
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/EGG-INFO/scripts/acd_cli.py", line 1321, in main
    sys.exit(args.func(args))
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/EGG-INFO/scripts/acd_cli.py", line 541, in sync_action
    r = sync_node_list(full=args.full)
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/EGG-INFO/scripts/acd_cli.py", line 140, in sync_node_list
    nodes, purged, ncp, full = acd_client.get_changes(checkpoint=cp, include_purged=not not cp)
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/acdcli/api/metadata.py", line 64, in get_changes
    for line in r.iter_lines(chunk_size=10 * 1024 ** 2, decode_unicode=False):
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 715, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 303, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 447, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 401, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)
```

**Comment by yadayada** [comment]
Which Python version did you use with which requests version on which platform?
Is this reproducible or did it occur once only?

**Comment by vampywiz17** [comment]
Python 3.4, Lubuntu 15.04, 

It got the errors every time.

**Comment by yadayada** [comment]
It doesn't look fixable.
Please try to run the ``old-sync`` using the latest commit from the dev branch.

**Comment by jonas5** [comment]
Hi,
I have been looking into the issue.
And it seems to be a memory issue. As the sqlite loads straight into the memory. (OOM)
Increasing the memory seems to solve the issue. 

My nodes.db file is peaking 1gb+, and I start to see the limitations of using a sqlite as db engine.

Sqlite is very good for small applications, but for bigger projects some other sql application would be more suitable.

**Comment by jonas5** [comment]
Is it any possibility after a certain X-y MB of data synced to dump the chunks into the db, then free memory and then continue the sync process and chunk another X-y MB.

To secure what has been downloaded if the sync process has been aborted or crashed for any reason and decrease the amount of memory required for this process.

**Comment by yadayada** [comment]
>My nodes.db file is peaking 1gb+, 

Sooo... you've got approx. 2 million nodes?

>Is it any possibility after a certain X-y MB of data synced to dump the chunks into the db, then free memory and then continue the sync process and chunk another X-y MB.

Yup. See #106.

**Comment by jonas5** [comment]
Approx 2 mill nodes sounds correct. 

With unlimited space! Comes unlimited ... power! 

Which gives this application unlimited of ... responsibilities?

**Comment by HazCod** [comment]
@jonas5 could you try out my fork?

**Comment by jonas5** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acdcli')()
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/EGG-INFO/scripts/acd_cli.py", line 1268, in main
    sys.exit(args.func(args))
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/EGG-INFO/scripts/acd_cli.py", line 524, in sync_action
    r = sync_node_list(full=args.full)
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/EGG-INFO/scripts/acd_cli.py", line 149, in sync_node_list
    cache.insert_nodes(nodes, partial=not full)
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/acdcli/cache/sync.py", line 85, in insert_nodes
    for folderChunk in grouper(maxBuff, folders):
NameError: name 'grouper' is not defined

**Comment by jonas5** [comment]
That comes ofc. after:

15-09-30 16:51:20.089 [INFO] [acdcli.api.metadata] - 123 pages, 245196 nodes, 71 purged nodes in changes.
15-09-30 16:51:21.392 [INFO] [acdcli.cache.sync] - Purged 71 node(s).

**Comment by HazCod** [comment]
Ahh, I just discovered you need to do a setup.py clean and setup.py build before an install.
Could you pull and try again please @jonas5 ?

**Comment by jonas5** [comment]
Doesnt seems like it download and dumps in chunks, just write down in chunks.
after let it run for a while

ps aux gives;
user      1695  9.3 34.8 2207412 2137284 pts/2 S+   10:34   0:30 /usr/bin/python3 /usr/local/bin/acdcli -v sync

and filesize of nodes.db
-rw-r--r-- 1 user user 15K Oct  2 10:22 nodes.db

**Comment by HazCod** [comment]
Ah, I tought the problem was solely in the insertion of nodes in the sql db.

**Comment by jonas5** [comment]
The new version still seem to have the same issue. But it is able to continue after it crash.

15-10-15 00:26:27.731 [INFO] [acdcli.cache.sync] - Inserted/updated 1843 file(s).
15-10-15 00:26:33.932 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests-2.8.1-py3.5.egg/requests/packages/urllib3/response.py", line 417, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests-2.8.1-py3.5.egg/requests/packages/urllib3/response.py", line 214, in _error_catcher
    yield
  File "/usr/local/lib/python3.5/site-packages/requests-2.8.1-py3.5.egg/requests/packages/urllib3/response.py", line 467, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.5/site-packages/requests-2.8.1-py3.5.egg/requests/packages/urllib3/response.py", line 421, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests-2.8.1-py3.5.egg/requests/models.py", line 657, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.5/site-packages/requests-2.8.1-py3.5.egg/requests/packages/urllib3/response.py", line 322, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python3.5/site-packages/requests-2.8.1-py3.5.egg/requests/packages/urllib3/response.py", line 485, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/requests-2.8.1-py3.5.egg/requests/packages/urllib3/response.py", line 232, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acdcli')()
  File "/mnt/disk/sw-raid/build/local/lib/python3.5/site-packages/acdcli-0.3.0a6-py3.5.egg/EGG-INFO/scripts/acd_cli.py", line 1361, in main
    sys.exit(args.func(args))
  File "/mnt/disk/sw-raid/build/local/lib/python3.5/site-packages/acdcli-0.3.0a6-py3.5.egg/EGG-INFO/scripts/acd_cli.py", line 539, in sync_action
    r = sync_node_list(full=args.full)
  File "/mnt/disk/sw-raid/build/local/lib/python3.5/site-packages/acdcli-0.3.0a6-py3.5.egg/EGG-INFO/scripts/acd_cli.py", line 137, in sync_node_list
    for changeset in acd_client.get_changes(checkpoint=cp_, include_purged=bool(cp_)):
  File "/usr/local/lib/python3.5/site-packages/acdcli-0.3.0a6-py3.5.egg/acdcli/api/metadata.py", line 61, in get_changes
    for line in r.iter_lines(chunk_size=10 * 1024 ** 2, decode_unicode=False):
  File "/usr/local/lib/python3.5/site-packages/requests-2.8.1-py3.5.egg/requests/models.py", line 699, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/usr/local/lib/python3.5/site-packages/requests-2.8.1-py3.5.egg/requests/models.py", line 660, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Press [CTRL+C] to stop..
15-10-15 00:26:36.816 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-10-15 00:26:36.817 [INFO] [acd_cli] - TestPlugin attached.
15-10-15 00:26:36.817 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/support/.cache/acd_cli".
15-10-15 00:26:36.818 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
15-10-15 00:26:36.819 [INFO] [acdcli.cache.db] - Initializing cache with path "/home/support/.cache/acd_cli".
15-10-15 00:26:36.860 [INFO] [acdcli.cache.db] - Cache is initialized.
15-10-15 00:26:36.864 [INFO] [acdcli.cache.db] - DB schema version is 1.
Syncing...
15-10-15 00:26:36.883 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "COKTf9_0KRoA".
15-10-15 00:26:36.884 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
15-10-15 00:26:36.935 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
15-10-15 00:26:40.670 [INFO] [acdcli.cache.sync] - Inserted/updated 221 folder(s).

(Connection broken)...?

**Comment by jonas5** [comment]
I will test this asap. thanks yadayada for your hard work!

**Comment by jonas5** [comment]
15-10-15 19:45:36.342 [INFO] [acdcli.cache.sync] - Inserted/updated 190 folder(s).
15-10-15 19:45:47.553 [INFO] [acdcli.cache.sync] - Inserted/updated 1806 file(s).
15-10-15 19:46:57.187 [INFO] [acdcli.cache.sync] - Parented 1996 node(s).
15-10-15 19:46:59.600 [INFO] [acdcli.cache.sync] - Purged 1 node(s).
15-10-15 19:47:02.080 [INFO] [acdcli.cache.sync] - Inserted/updated 135 folder(s).
15-10-15 19:47:19.793 [INFO] [acdcli.cache.sync] - Inserted/updated 1864 file(s).
15-10-15 19:48:29.371 [INFO] [acdcli.cache.sync] - Parented 1999 node(s).
15-10-15 19:48:33.043 [INFO] [acdcli.cache.sync] - Inserted/updated 130 folder(s).
15-10-15 19:48:52.093 [INFO] [acdcli.cache.sync] - Inserted/updated 1868 file(s).
15-10-15 19:50:02.312 [INFO] [acdcli.cache.sync] - Parented 1998 node(s).
15-10-15 19:50:03.030 [INFO] [acdcli.api.metadata] - ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
RequestError: 1003, [acd_api] reading changes terminated prematurely.
15-10-15 19:50:03.031 [CRITICAL] [acd_cli] - Sync failed.

**Comment by yadayada** [comment]
It does what it says in the commit message. Surprising, isn't it?
Why do you think this issue is closed and marked as unresolved? Stop your bloody spamming.

**Comment by jonas5** [comment]
Dont worry, we are getting there!

What about putting a -r x, retry on sync?
