### ISSUE TITLE
acd_cli started spitting errors and now complains about oath

### ISSUE THREAD

**Issue by vhgarandil** [yadayada/acd_cli#162]
I was using acd_cli to upload and sync when it stopped working and now all I get is the following:
```
''''cloudshadow@pms:~$ acd_cli -v mount /home/cloudshadow/.acd-sorted/
    15-10-03 02:49:04.076 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
    15-10-03 02:49:04.076 [INFO] [acd_cli] - TestPlugin attached.
15-10-03 02:49:04.076 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/cloudshadow/.cache/acd_cli".
15-10-03 02:49:04.077 [CRITICAL] [acdcli.api.oauth] - Invalid authentication token: Invalid JSON or missing key.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 17, in create_handler
    return LocalOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 218, in __init__
    self.load_client_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 225, in load_client_data
    with open(cdp) as cd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cloudshadow/.cache/acd_cli/client_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 48, in validate
    o = json.loads(oauth)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 346, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 7 column 2 - line 7 column 3 (char 1052 - 1053)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1241, in main
    acd_client = client.ACDClient(CACHE_PATH)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 31, in __init__
    self.handler = oauth.create_handler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 19, in create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 131, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 70, in load_oauth_data
    self.oauth_data = self.validate(o)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 55, in validate
    raise RequestError(RequestError.CODE.INVALID_TOKEN, e.__str__())
acdcli.api.common.RequestError: RequestError: 1005, Extra data: line 7 column 2 - line 7 column 3 (char 1052 - 1053)
''''
```
I have checked ~/.cache/acd_cli/ and cannot find client_data present.

Any input on this would be greatly appreciated.

**Comment by yadayada** [comment]
Please try again with the latest dev commit to see what's wrong with the oauth data.

**Comment by vhgarandil** [comment]
root@pms:/home/cloudshadow# pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git
Downloading/unpacking git+https://github.com/yadayada/acd_cli.git
  Cloning https://github.com/yadayada/acd_cli.git to /tmp/pip-lkrp85pg-build
  Running setup.py (path:/tmp/pip-lkrp85pg-build/setup.py) egg_info for package from git+https://github.com/yadayada/acd_cli.git
    
Requirement already up-to-date: appdirs in /usr/local/lib/python3.4/dist-packages/appdirs-1.4.0-py3.4.egg (from acdcli==0.3.0a6)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.4/dist-packages/python_dateutil-2.4.2-py3.4.egg (from acdcli==0.3.0a6)
Downloading/unpacking requests>=2.1.0 from https://pypi.python.org/packages/2.7/r/requests/requests-2.7.0-py2.py3-none-any.whl#md5=564fb256f865a79f977e57b79d31659a (from acdcli==0.3.0a6)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Requirement already up-to-date: requests-toolbelt in /usr/local/lib/python3.4/dist-packages/requests_toolbelt-0.4.0-py3.4.egg (from acdcli==0.3.0a6)
Requirement already up-to-date: sqlalchemy in /usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4-linux-x86_64.egg (from acdcli==0.3.0a6)
Requirement already up-to-date: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->acdcli==0.3.0a6)
Installing collected packages: requests, acdcli
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: acdcli 0.3.0a6
    Uninstalling acdcli:
      Successfully uninstalled acdcli
  Running setup.py install for acdcli
    changing mode of build/scripts-3.4/acd_cli.py from 644 to 755
    
    changing mode of /usr/local/bin/acd_cli.py to 755
    Installing acd_cli script to /usr/local/bin
    Installing acdcli script to /usr/local/bin
Successfully installed requests acdcli
Cleaning up...


But it still throws:
cloudshadow@pms:~$ acd_cli -v sync
15-10-03 10:56:08.570 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-10-03 10:56:08.570 [INFO] [acd_cli] - TestPlugin attached.
15-10-03 10:56:08.570 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/cloudshadow/.cache/acd_cli".
15-10-03 10:56:08.571 [CRITICAL] [acdcli.api.oauth] - Invalid authentication token: Invalid JSON or missing key.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 17, in create_handler
    return LocalOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 218, in __init__
    self.load_client_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 225, in load_client_data
    with open(cdp) as cd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cloudshadow/.cache/acd_cli/client_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 48, in validate
    o = json.loads(oauth)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 346, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 7 column 2 - line 7 column 3 (char 1052 - 1053)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1241, in main
    acd_client = client.ACDClient(CACHE_PATH)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 31, in __init__
    self.handler = oauth.create_handler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 19, in create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 131, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 70, in load_oauth_data
    self.oauth_data = self.validate(o)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 55, in validate
    raise RequestError(RequestError.CODE.INVALID_TOKEN, e.__str__())
acdcli.api.common.RequestError: RequestError: 1005, Extra data: line 7 column 2 - line 7 column 3 (char 1052 - 1053)

**Comment by yadayada** [comment]
```
pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git@dev
```

**Comment by vhgarandil** [comment]
After that:
cloudshadow@pms:~$ acd_cli -v mount /home/cloudshadow/.acd-sorted/
15-10-03 11:07:47.804 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-10-03 11:07:47.804 [INFO] [acd_cli] - TestPlugin attached.
15-10-03 11:07:47.804 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/cloudshadow/.cache/acd_cli".
15-10-03 11:07:47.805 [CRITICAL] [acdcli.api.oauth] - Invalid authentication token: Invalid JSON or missing key.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 17, in create_handler
    return LocalOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 218, in __init__
    self.load_client_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 225, in load_client_data
    with open(cdp) as cd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cloudshadow/.cache/acd_cli/client_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 48, in validate
    o = json.loads(oauth)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 346, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 7 column 2 - line 7 column 3 (char 1052 - 1053)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1241, in main
    acd_client = client.ACDClient(CACHE_PATH)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 31, in __init__
    self.handler = oauth.create_handler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 19, in create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 131, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 70, in load_oauth_data
    self.oauth_data = self.validate(o)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 55, in validate
    raise RequestError(RequestError.CODE.INVALID_TOKEN, e.__str__())
acdcli.api.common.RequestError: RequestError: 1005, Extra data: line 7 column 2 - line 7 column 3 (char 1052 - 1053)
cloudshadow@pms:~$ sudo pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git@dev
[sudo] password for cloudshadow: 
Downloading/unpacking git+https://github.com/yadayada/acd_cli.git@dev
  Cloning https://github.com/yadayada/acd_cli.git (to dev) to /tmp/pip-z65cowvl-build
  Running setup.py (path:/tmp/pip-z65cowvl-build/setup.py) egg_info for package from git+https://github.com/yadayada/acd_cli.git@dev
    
Requirement already up-to-date: appdirs in /usr/local/lib/python3.4/dist-packages/appdirs-1.4.0-py3.4.egg (from acdcli==0.3.0a6)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.4/dist-packages/python_dateutil-2.4.2-py3.4.egg (from acdcli==0.3.0a6)
Downloading/unpacking requests>=2.1.0 from https://pypi.python.org/packages/2.7/r/requests/requests-2.7.0-py2.py3-none-any.whl#md5=564fb256f865a79f977e57b79d31659a (from acdcli==0.3.0a6)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Requirement already up-to-date: requests-toolbelt in /usr/local/lib/python3.4/dist-packages/requests_toolbelt-0.4.0-py3.4.egg (from acdcli==0.3.0a6)
Requirement already up-to-date: sqlalchemy in /usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4-linux-x86_64.egg (from acdcli==0.3.0a6)
Requirement already up-to-date: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->acdcli==0.3.0a6)
Installing collected packages: requests, acdcli
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: acdcli 0.3.0a6
    Uninstalling acdcli:
      Successfully uninstalled acdcli
  Running setup.py install for acdcli
    changing mode of build/scripts-3.4/acd_cli.py from 644 to 755
    
    changing mode of /usr/local/bin/acd_cli.py to 755
    Installing acd_cli script to /usr/local/bin
    Installing acdcli script to /usr/local/bin
Successfully installed requests acdcli
Cleaning up...
cloudshadow@pms:~$ acd_cli -v mount /home/cloudshadow/.acd-sorted/
15-10-03 11:16:11.202 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-10-03 11:16:11.202 [INFO] [acd_cli] - TestPlugin attached.
15-10-03 11:16:11.202 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/cloudshadow/.cache/acd_cli".
15-10-03 11:16:11.202 [CRITICAL] [acdcli.api.oauth] - Invalid authentication token: Invalid JSON or missing key.Token:
{
    "access_token": "Atza|IQEBLjAsAhRbqH0jE7i0a-kmTe-le5O1LCADqQIUKQL3wfD7wgT0sT6c-WKOxpYcYYvNgHtGHujlGtMK-LY8s6YHevmw5TdTgaOkcs_Oa-Y3-SSMZ3IOFcP_ADT3WshFwj0ahQ9V2osq5Zbue4fkjInWIg8YiKcK_4lU99UOZw6tlIj9aC9dSmPO64bayUwbSIokpyQP9aZZ1fEtJAEWv8GYS7ttl4v-vEvyW5XP9CVVU2YvrvJEXC8WyphbOw8nLx4c_2OYI4kza3aQGb6sKmh7ZX_J2zNrdWabuEIi1FHahwC0YEg18qUpLM_jiRQK_WnFZEuux2DVmh1P2TE4luaNi_LfO7eJY9iz_woerYowbAh6H7cxOpNSN2YVvnXKCN87BQ3rSoCT7ft8KOVvPzf3Sl9iS7bCxb8aCtWqOA4vZThPd-FhrHT3VXw0hhxv4KEd",
    "exp_time": 1443827908.694629,
    "expires_in": 3600,
    "refresh_token": "Atzr|IQEBLjAsAhRMNo0Zm5xD7-FN4osMrH6ORmBmEAIUQaqaPynQVT4w_FeqbSsF2b7DEqJnte1QhDWfFFxoChRIBlpQ7gHv0_6hmxrs3oNkYwr_mxyvrmKM2Jp5N0ryShu9VmdkF2Hijs9r16g5dCrBl2A0A8zewIbbp0MrEatuSZugUySZ3DCkm3BrAWz0q-qrhNmSHgBG8Za0P19yAx0GSqS7pJRAClyyUhABcoHlBZ2dnIgRYBhyB5R78zlI9MAnR0qKIzbpsgpb0rEkUyC5cKRKO08ULMX0OE-Pji-hBf8d7086NUU4v2j-NfGy4IL8UNNO1VT-TTimDaLPOIBbFAcC6H0PZXvLXrbbeK9drRMDNb0RkAGRL3iFcY5MmUBBW9MwlRfbw_t5QJkMWF-r1MUBHd1PFZl2mofUkQ55wLXbiIZQKELu-8HpmCJqGM7jAoPi",
    "token_type": "bearer"
}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 49, in validate
    o = json.loads(oauth)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 346, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 7 column 2 - line 7 column 3 (char 1052 - 1053)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1294, in main
    acd_client = client.ACDClient(CACHE_PATH)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 31, in __init__
    self.handler = oauth.create_handler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 20, in create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 133, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 72, in load_oauth_data
    self.oauth_data = self.validate(o)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 57, in validate
    raise RequestError(RequestError.CODE.INVALID_TOKEN, e.__str__())
acdcli.api.common.RequestError: RequestError: 1005, Extra data: line 7 column 2 - line 7 column 3 (char 1052 - 1053)

**Comment by vhgarandil** [comment]
Looks like it might have helped to move the oauth_data file and issue a new one.

**Comment by yadayada** [comment]
I was just about to suggest this. Somehow a superfluous closing brace got in your oauth_data JSON.
