### ISSUE TITLE
Database metadata locked

### ISSUE THREAD

**Issue by HazCod** [yadayada/acd_cli#164]
Can't access my mount anymore, suggestions?

```
15-10-08 12:43:06.525 [CRITICAL] [acdcli.cache.db] - Error opening database: (sqlite3.OperationalError) database is locked [SQL: 'PRAGMA table_info("metadata")']
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/default.py", line 450, in do_execute
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acdcli')()
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/EGG-INFO/scripts/acd_cli.py", line 1248, in main
    cache = db.NodeCache(CACHE_PATH, args.check)
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/acdcli/cache/db.py", line 64, in __init__
    raise e
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/acdcli/cache/db.py", line 58, in __init__
    uninitialized = not self.engine.has_table(schema.Metadate.__tablename__) and \
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 2069, in has_table
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1972, in run_callable
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1477, in run_callable
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/dialects/sqlite/base.py", line 1127, in has_table
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/dialects/sqlite/base.py", line 1468, in _get_table_pragma
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 906, in execute
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1054, in _execute_text
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/util/compat.py", line 188, in raise_from_cause
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/util/compat.py", line 181, in reraise
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/default.py", line 450, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'PRAGMA table_info("metadata")']
```

**Comment by sjfer** [comment]
Delete nodes.db and resync, then remount?

**Comment by yadayada** [comment]
See #124, #143.

**Comment by HazCod** [comment]
`acdcli -v init

acdcli -v init
15-10-09 11:36:22.066 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-10-09 11:36:22.066 [INFO] [acd_cli] - TestPlugin attached.
15-10-09 11:36:22.066 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/media/.cache/acd_cli".
15-10-09 11:36:22.066 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
15-10-09 11:36:22.066 [INFO] [acdcli.cache.db] - Initializing cache with path "/home/media/.cache/acd_cli".
15-10-09 11:36:27.090 [CRITICAL] [acdcli.cache.db] - Error opening database: (sqlite3.OperationalError) database is locked [SQL: 'PRAGMA table_info("metadata")']
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/default.py", line 450, in do_execute
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acdcli')()
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/EGG-INFO/scripts/acd_cli.py", line 1248, in main
    cache = db.NodeCache(CACHE_PATH, args.check)
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/acdcli/cache/db.py", line 64, in __init__
    raise e
  File "/usr/local/lib/python3.4/dist-packages/acdcli-0.3.0a6-py3.4.egg/acdcli/cache/db.py", line 58, in __init__
    uninitialized = not self.engine.has_table(schema.Metadate.__tablename__) and \
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 2069, in has_table
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1972, in run_callable
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1477, in run_callable
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/dialects/sqlite/base.py", line 1127, in has_table
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/dialects/sqlite/base.py", line 1468, in _get_table_pragma
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 906, in execute
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1054, in _execute_text
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/util/compat.py", line 188, in raise_from_cause
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/util/compat.py", line 181, in reraise
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
  File "/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.8-py3.4.egg/sqlalchemy/engine/default.py", line 450, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'PRAGMA table_info("metadata")']

`

**Comment by HazCod** [comment]
Fixed by rebooting, but something serious nonetheless @yadayada
