### ISSUE TITLE
Error While Sync

### ISSUE THREAD

**Issue by dcplaya** [yadayada/acd_cli#18]
I have updated to your newest version and when I try to sync, I get the following error (running with -v as well)

```
15-05-01 08:14:20.529 [acd_cli] [INFO] - Getting changes with checkpoint "None".
15-05-01 08:14:20.534 [acd.common] [INFO] - Retry 0, waiting 0.000882 secs
15-05-01 08:14:20.543 [urllib3.connectionpool] [INFO] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
Traceback (most recent call last):
  File "./acd_cli.py", line 615, in <module>
    main()
  File "./acd_cli.py", line 611, in main
    args.func(args)
  File "./acd_cli.py", line 274, in sync_action
    sync_node_list(full=args.full)
  File "./acd_cli.py", line 52, in sync_node_list
    r = metadata.get_changes(checkpoint=cp)
  File "/home/drew/Documents/acd_cli/acd/metadata.py", line 48, in get_changes
    ro = str.splitlines(r.text)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 711, in text
    encoding = self.apparent_encoding
  File "/usr/lib/python3/dist-packages/requests/models.py", line 598, in apparent_encoding
    return chardet.detect(self.content)['encoding']
  File "/usr/lib/python3/dist-packages/chardet/__init__.py", line 30, in detect
    u.feed(aBuf)
  File "/usr/lib/python3/dist-packages/chardet/universaldetector.py", line 128, in feed
    if prober.feed(aBuf) == constants.eFoundIt:
  File "/usr/lib/python3/dist-packages/chardet/charsetgroupprober.py", line 64, in feed
    st = prober.feed(aBuf)
  File "/usr/lib/python3/dist-packages/chardet/sbcharsetprober.py", line 72, in feed
    aBuf = self.filter_without_english_letters(aBuf)
  File "/usr/lib/python3/dist-packages/chardet/charsetprober.py", line 57, in filter_without_english_letters
    aBuf = re.sub(b'([A-Za-z])+', b' ', aBuf)
  File "/usr/lib/python3.4/re.py", line 175, in sub
    return _compile(pattern, flags).sub(repl, string, count)
MemoryError
```

**Comment by yadayada** [comment]
Please try again with the newest commit.

**Comment by dcplaya** [comment]
Just got around to trying it. Seems to be working!  Thank you.
