### ISSUE TITLE
Allow specifying file name for single file download

### ISSUE THREAD

**Issue by jbondhus** [yadayada/acd_cli#184]
Right now, if I attempt to download a file to a custom file name, for example `acdcli download /fuse-2.9.4.tar.gz /root/test_fuse2.tar.gz`, an error will be thrown as follows.

```
root@mirror:~ # acdcli download /fuse-2.9.4.tar.gz /root/test_fuse2.tar.gz
15-11-01 20:38:52.237 [ERROR] [acd_cli] - Traceback (most recent call last):
  File "/usr/local/bin/acd_cli.py", line 197, in wrapped
    ret_val = f(*args, **kwargs)
  File "/usr/local/bin/acd_cli.py", line 494, in download_file
    write_callbacks=[hasher.update, pg_handler.update])
  File "/usr/local/lib/python3.3/site-packages/acdcli/api/content.py", line 265, in download_file
    f = open(part_path, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/root/test_fuse2.tar.gz/fuse-2.9.4.tar.gz.__incomplete'

[                         ]   0.0% of  564KiB  0/1     0.0B/s       0s
1 file(s) failed.
```

Obviously what's happening is acdcli is thinking that the destination I specified is a directory, when in fact I am trying to get it to download to a specific file name.

**Comment by yadayada** [comment]
The `path` parameter is always supposed to be a directory, even though it may not documented correctly everywhere.

There was a similar request recently, #151, which I may have to revisit if I accept to allow naming the destination files... I'm undecided as of yet.
