### ISSUE TITLE
pysqlite circular references

### ISSUE THREAD

**Issue by utdrmac** [yadayada/acd_cli#195]
Trying to install this. Banging head against wall. Not a python user. Can't get init to work. Using python 3.4.3.

```
root@gasgiant:~# acd_cli init
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 337, in dbapi
    from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
  File "/usr/local/lib/python3.4/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.4/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1399, in main
    cache = db.NodeCache(CACHE_PATH, args.check)
  File "/usr/local/lib/python3.4/site-packages/acdcli/cache/db.py", line 54, in __init__
    connect_args={'check_same_thread': False})
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 334, in dbapi
    from pysqlite2 import dbapi2 as sqlite
ImportError: No module named 'pysqlite2'
```

Attempts to install:

```
root@gasgiant:~# pip3.4 install pysqlite
Collecting pysqlite
  Using cached pysqlite-2.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.
```

What now?

**Comment by yadayada** [comment]
There was someone who wrote an e-mail with a similar problem last week to whom I regrettably forgot to reply :/

I presume your python installation is missing the sqlite3 module. On my machine, I've got

```
$ find /usr -name _sqlite3* 2>/dev/null
  /usr/lib/python3.4/lib-dynload/_sqlite3.cpython-34m-x86_64-linux-gnu.so
  /usr/lib/python2.7/lib-dynload/_sqlite3.x86_64-linux-gnu.so
```

Did you compile python3 yourself?

**Comment by utdrmac** [comment]
I may have compiled python3 at some point many months ago; I honestly 
don't recall as I don't get on this machine often. I have so many 
versions of python on this NAS.

```
root@gasgiant:~# python
python                python2.7             python2.7-dbg-config 
python3.2-config      python3.4             python3-config python-config
python2               python2.7-config      python3 
python3.2mu           python3.4m            python3mu python-dbg
python2.6             python2.7-dbg         python3.2 
python3.2mu-config    python3.4m-config     python3mu-config 
python-dbg-config

root@gasgiant:~# find /usr/ -name _sqlite3*
/usr/lib/python2.6/lib-dynload/_sqlite3.so
/usr/lib/python2.7/lib-dynload/_sqlite3.so
/usr/lib/python2.7/lib-dynload/_sqlite3_d.so
/usr/lib/python3.2/lib-dynload/_sqlite3.cpython-32mu.so
/usr/lib/debug/usr/lib/python2.7/lib-dynload/_sqlite3.so
```

I think the problem is that when I compiled python3.4, it got placed in 
/usr/local/
```
root@gasgiant:~# which python3.4
/usr/local/bin/python3.4
```

Instead of /usr, so it can't find all the libraries and stuff. *shrug* I 
dono. This is the most I've ever messed with python aside from an 
install a couple months ago.

Thanks!

-Matthew

**Comment by utdrmac** [comment]
I removed my installation of 3.4 and recompiled using --prefix=/usr and things are working great now! FUSE support is amazing!
