### ISSUE TITLE
(sqlite3.OperationalError) database is locked

### ISSUE THREAD

**Issue by aaiezza** [yadayada/acd_cli#205]
After kicking off the following commands:

```
# bcbio_nextgen.py -w template gatk-variant project1.csv /atlas/garvin_inst_2014/raw_reads/NA12878D_HiSeqX_R1.fastq /atlas/garvin_inst_2014/raw_reads/NA12878D_HiSeqX_R2.fastq

# bcbio_nextgen.py ../config/project1.yaml
```
I get:
```
/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
[2015-11-28T06:02Z] Resource requests: bwa, sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16, 16
[2015-11-28T06:02Z] Configuring 1 jobs to run, using 1 cores each with 2.00g of memory reserved for each job
[2015-11-28T06:02Z] Timing: organize samples
[2015-11-28T06:02Z] multiprocessing: organize_samples
[2015-11-28T06:02Z] Using input YAML configuration: /athena/bcbio_test/project1/config/project1.yaml
[2015-11-28T06:02Z] Checking sample YAML configuration: /athena/bcbio_test/project1/config/project1.yaml
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 139, in run
    [x[0]["description"] for x in samples]]])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
    self.results = func(*args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 226, in organize_samples
    return run_info.organize(*args)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 55, in organize
    item = add_reference_resources(item)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 139, in add_reference_resources
    data["genome_resources"] = genome.get_resources(data["genome_build"], ref_loc, data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 41, in get_resources
    return _ensure_annotations(cleaned, data)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 50, in _ensure_annotations
    resources["rnaseq"]["gene_bed"] = gtf.gtf_to_bed(transcript_gff, out_dir)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py", line 58, in gtf_to_bed
    db = get_gtf_db(gtf)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py", line 42, in get_gtf_db
    return gffutils.FeatureDB(db_file)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/gffutils/interface.py", line 130, in __init__
    ''')
sqlite3.OperationalError: database is locked
```
Any idea what this might be?

-Alex

**Comment by yadayada** [comment]
>Any idea what this might be?

Is there any particular reason why you don't ask the bcbio_nextgen or gffutils developers?

**Comment by aaiezza** [comment]
* blush *
I had so many tabs open I didn't notice I was not in that repo. Sorry about that
