### ISSUE TITLE
osxfuse - acd_cli mount - No such table metadata

### ISSUE THREAD

**Issue by rubenvarela** [yadayada/acd_cli#206]
I've been playing with acd_cli yesterday and today. I wanted to try out the mount functionality today so I installed the latest osxfuse 2.8.2 to give it a try.

I got the following error:

    (acd)  ~/D/amazon_cloud_drive  acd_cli mount tmp/acd/
    15-11-29 02:26:21.817 [ERROR] [acd_cli] - Traceback (most recent call last):
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
        cursor.execute(statement, parameters)
    sqlite3.OperationalError: no such table: metadata

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/Users/ruben/.pyenv/versions/acd/bin/acd_cli.py", line 186, in autosync
        sync_node_list(full=False)
      File "/Users/ruben/.pyenv/versions/acd/bin/acd_cli.py", line 130, in sync_node_list
        cp_ = cache.KeyValueStorage.get(CacheConsts.CHECKPOINT_KEY) if not full else None
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/acdcli/cache/schema.py", line 233, in get
        val = self.Session.query(Metadate).filter_by(key=key).first()
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2469, in first
        ret = list(self[0:1])
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2292, in __getitem__
        return list(res)
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2571, in __iter__
        return self._execute_and_instances(context)
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2586, in _execute_and_instances
        result = conn.execute(querycontext.statement, self._params)
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
        context)
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
        exc_info
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
        raise value.with_traceback(tb)
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
      File "/Users/ruben/.pyenv/versions/acd/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: metadata [SQL: 'SELECT metadata."key" AS metadata_key, metadata.value AS metadata_value \nFROM metadata \nWHERE metadata."key" = ?\n LIMIT ? OFFSET ?'] [parameters: ('checkpoint', 1, 0)]

**Comment by yadayada** [comment]
>sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: metadata

That's strange. All tables should be created when the db.Nodecache is instantiated...
Have you synced (successfully) prior to trying to mount?

To prevent to autosync, which fails here, use ``-i0``, e.g. ``acd_cli mount -i0 tmp/acd``

**Comment by rubenvarela** [comment]
I did try running sync and it worked.

I just ran it again and this is the output:

    (acd)  ~/D/amazon_cloud_drive  acd_cli -v sync
    15-11-29 09:54:23.819 [INFO] [acd_cli] - Plugin leaf classes: ClementinePlugin, TestPlugin, TestPlugin, TermsOfUsePlugin
    15-11-29 09:54:23.819 [INFO] [acd_cli] - Clementine executable not found.
    15-11-29 09:54:23.820 [INFO] [acd_cli] - TestPlugin attached.
    15-11-29 09:54:23.820 [INFO] [acd_cli] - TestPlugin attached.
    15-11-29 09:54:23.820 [INFO] [acd_cli] - TermsOfUsePlugin attached.
    15-11-29 09:54:23.821 [INFO] [acdcli.api.client] - Initializing ACD with path "/Users/ruben/Library/Caches/acd_cli".
    15-11-29 09:54:23.821 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
    15-11-29 09:54:23.822 [INFO] [acdcli.cache.db] - Initializing cache with path "/Users/ruben/Library/Caches/acd_cli".
    15-11-29 09:54:23.843 [INFO] [acdcli.cache.db] - Cache is initialized.
    15-11-29 09:54:23.847 [INFO] [acdcli.cache.db] - DB schema version is 1.
    Syncing...
    15-11-29 09:54:23.859 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "CJmHkJGVKhoA".
    15-11-29 09:54:23.859 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
    15-11-29 09:54:23.874 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
    15-11-29 09:54:24.032 [INFO] [acdcli.api.metadata] - 1 page(s) in changes.
    Done.

Is there a way to recreate the database?

&nbsp;

Running with `-i0` didn't throw the error:

    (acd)  ~/D/amazon_cloud_drive  acd_cli -v mount -i0 tmp/acd
    15-11-29 09:56:36.725 [INFO] [acd_cli] - Plugin leaf classes: ClementinePlugin, TestPlugin, TermsOfUsePlugin, TestPlugin
    15-11-29 09:56:36.726 [INFO] [acd_cli] - Clementine executable not found.
    15-11-29 09:56:36.726 [INFO] [acd_cli] - TestPlugin attached.
    15-11-29 09:56:36.726 [INFO] [acd_cli] - TermsOfUsePlugin attached.
    15-11-29 09:56:36.726 [INFO] [acd_cli] - TestPlugin attached.
    15-11-29 09:56:36.727 [INFO] [acdcli.api.client] - Initializing ACD with path "/Users/ruben/Library/Caches/acd_cli".
    15-11-29 09:56:36.727 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
    15-11-29 09:56:36.728 [INFO] [acdcli.cache.db] - Initializing cache with path "/Users/ruben/Library/Caches/acd_cli".
    15-11-29 09:56:36.744 [INFO] [acdcli.cache.db] - Cache is initialized.
    15-11-29 09:56:36.747 [INFO] [acdcli.cache.db] - DB schema version is 1.
    15-11-29 09:56:36.764 [INFO] [acd_cli] - Last sync at 2015-11-29 14:54:24.024679.
    15-11-29 09:56:36.780 [INFO] [acdcli.api.backoff_req] - GET "https://cdws.us-east-1.amazonaws.com/drive/v1/account/quota"
    15-11-29 09:56:36.814 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com

but I can't run `ls`

    acd  ~/D/amazon_cloud_drive  ls tmp/acd/
    ls: reading directory tmp/acd/: Bad address


Any ideas? :/

**Comment by yadayada** [comment]
Can you please unmount and re-mount using
``acdcli -d mount -i0 --foreground tmp/acd``
 
then ``ls`` the mount point and look at the debug log. Please also check the output of ``acdcli ls /``.

**Comment by rubenvarela** [comment]
Huh....

    15-11-29 15:00:21.559 [DEBUG] [acdcli.acd_fuse] - -> access / (0,)
    15-11-29 15:00:21.560 [DEBUG] [acdcli.acd_fuse] - <- access 0
    15-11-29 15:00:21.560 [DEBUG] [acdcli.acd_fuse] - -> access / (4,)
    15-11-29 15:00:21.560 [DEBUG] [acdcli.acd_fuse] - <- access 0
    15-11-29 15:00:21.561 [DEBUG] [acdcli.acd_fuse] - -> opendir / ()
    15-11-29 15:00:21.561 [DEBUG] [acdcli.acd_fuse] - <- opendir 0
    15-11-29 15:00:21.561 [DEBUG] [acdcli.acd_fuse] - -> statfs / ()
    15-11-29 15:00:21.561 [DEBUG] [acdcli.acd_fuse] - <- statfs {'f_bavail': 209701345, 'f_bfree':     209701345, 'f_bsize': 524288, 'f_frsize': 524288, 'f_namemax': 256, 'f_blocks': 209715200}
    15-11-29 15:00:21.562 [DEBUG] [acdcli.acd_fuse] - -> readdir / (0,)
    15-11-29 15:00:21.568 [DEBUG] [acdcli.acd_fuse] - <- readdir ['.', '..', 'Pictures', 'Documents',     'Backups', 'Videos']
    15-11-29 15:00:21.568 [DEBUG] [acdcli.acd_fuse] - -> access / (1,)
    15-11-29 15:00:21.568 [DEBUG] [acdcli.acd_fuse] - <- access 0
    15-11-29 15:00:21.568 [DEBUG] [acdcli.acd_fuse] - -> getattr /Pictures (None,)
    15-11-29 15:00:21.570 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_ctime': 1448572106.895,     'st_mode': 16895, 'st_atime': 1448827221.570937, 'st_nlink': 1, 'st_mtime': 1448572106.895}
    15-11-29 15:00:21.571 [DEBUG] [acdcli.acd_fuse] - -> access /Pictures (0,)
    15-11-29 15:00:21.571 [DEBUG] [acdcli.acd_fuse] - <- access 0
    15-11-29 15:00:21.571 [DEBUG] [acdcli.acd_fuse] - -> getattr /Pictures (None,)
    15-11-29 15:00:21.574 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_ctime': 1448572106.895,     'st_mode': 16895, 'st_atime': 1448827221.574088, 'st_nlink': 1, 'st_mtime': 1448572106.895}
    15-11-29 15:00:21.574 [DEBUG] [acdcli.acd_fuse] - -> getattr /Documents (None,)
    15-11-29 15:00:21.576 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_ctime': 1448572106.88,     'st_mode': 16895, 'st_atime': 1448827221.576456, 'st_nlink': 1, 'st_mtime': 1448645852.817}
    15-11-29 15:00:21.576 [DEBUG] [acdcli.acd_fuse] - -> access /Documents (0,)
    15-11-29 15:00:21.577 [DEBUG] [acdcli.acd_fuse] - <- access 0
    15-11-29 15:00:21.577 [DEBUG] [acdcli.acd_fuse] - -> getattr /Documents (None,)
    15-11-29 15:00:21.579 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_ctime': 1448572106.88,     'st_mode': 16895, 'st_atime': 1448827221.579202, 'st_nlink': 1, 'st_mtime': 1448645852.817}
    15-11-29 15:00:21.579 [DEBUG] [acdcli.acd_fuse] - -> getattr /Backups (None,)
    15-11-29 15:00:21.581 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_ctime': 1448669724.836,     'st_mode': 16895, 'st_atime': 1448827221.581257, 'st_nlink': 1, 'st_mtime': 1448782070.652}
    15-11-29 15:00:21.581 [DEBUG] [acdcli.acd_fuse] - -> access /Backups (0,)
    15-11-29 15:00:21.581 [DEBUG] [acdcli.acd_fuse] - <- access 0
    15-11-29 15:00:21.582 [DEBUG] [acdcli.acd_fuse] - -> getattr /Backups (None,)
    15-11-29 15:00:21.584 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_ctime': 1448669724.836,     'st_mode': 16895, 'st_atime': 1448827221.584428, 'st_nlink': 1, 'st_mtime': 1448782070.652}
    15-11-29 15:00:21.584 [DEBUG] [acdcli.acd_fuse] - -> getattr /Videos (None,)
    15-11-29 15:00:21.587 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_ctime': 1448572106.898,     'st_mode': 16895, 'st_atime': 1448827221.587048, 'st_nlink': 1, 'st_mtime': 1448572106.898}
    15-11-29 15:00:21.587 [DEBUG] [acdcli.acd_fuse] - -> access /Videos (0,)
    15-11-29 15:00:21.587 [DEBUG] [acdcli.acd_fuse] - <- access 0
    15-11-29 15:00:21.588 [DEBUG] [acdcli.acd_fuse] - -> getattr /Videos (None,)
    15-11-29 15:00:21.590 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_ctime': 1448572106.898,     'st_mode': 16895, 'st_atime': 1448827221.590456, 'st_nlink': 1, 'st_mtime': 1448572106.898}
    15-11-29 15:00:21.591 [DEBUG] [acdcli.acd_fuse] - -> releasedir / (0,)
    15-11-29 15:00:21.591 [DEBUG] [acdcli.acd_fuse] - <- releasedir 0

In another tab:

    acd  ~/D/amazon_cloud_drive  ls tmp/acd/
    Backups/  Documents/  Pictures/  Videos/

    acd  ~/D/amazon_cloud_drive  acdcli ls
    [e5C3WPwYSYespdtiDyNOtg] [A] Backups/
    [XWVchdttS5K5QLzssMse9A] [A] Documents/
    [0fpt1K_uSji8MIzsrwKHFA] [A] Pictures/
    [iPH67diMSZCgN_TIZvS8PQ] [A] Videos/


 I uninstalled and reinstalled it and now it works... 

&nbsp;

Thank you! I definitely will try it on another computer and see what happens. I think at some point I had an older installation of osxfuse and I upgraded the OS and I guess I just reinstalled. 

Now when I uninstalled (manually for example the preference pane) and reinstalled it, I think that made it work.

**Comment by jmoriau** [comment]
I have the exact same issue, it works with -i0 though. The error is:

    16-01-19 20:14:45.961 [ERROR] [acd_cli] - Traceback (most recent call last):
      File "/Users/user/.pyenv/versions/3.5.1/bin/acd_cli.py", line 176, in autosync
        sync_node_list(full=False)
      File "/Users/user/.pyenv/versions/3.5.1/bin/acd_cli.py", line 114, in sync_node_list
        cp_ = cache.KeyValueStorage.get(CacheConsts.CHECKPOINT_KEY) if not full else None
      File "/Users/user/.pyenv/versions/3.5.1/lib/python3.5/site-packages/acdcli/cache/schema.py", line 155, in get
        c.execute('SELECT value FROM metadata WHERE key == ?', [key])
    sqlite3.OperationalError: no such table: metadata

**Comment by jmoriau** [comment]
I tried (out of curiosity) to override the `full` parameter of `sync_node_list`:

    def sync_node_list(full=False) -> 'Union[int, None]':
        full=True
        global cache

and the error now is:

    File "/Users/user/.pyenv/versions/3.5.1/bin/acd_cli.py", line 177, in autosync
        sync_node_list(full=False)
    File "/Users/user/.pyenv/versions/3.5.1/bin/acd_cli.py", line 119, in sync_node_list
      cache.init()
    File "/Users/user/.pyenv/versions/3.5.1/lib/python3.5/site-packages/acdcli/cache/schema.py", line 102, in init
      self._migrate(ver)
    File "/Users/user/.pyenv/versions/3.5.1/lib/python3.5/site-packages/acdcli/cache/schema.py", line 114, in _migrate
    migration(self._conn)
    File "/Users/user/.pyenv/versions/3.5.1/lib/python3.5/site-packages/acdcli/cache/schema.py", line 65, in _0_to_1
    'ALTER TABLE nodes ADD updated DATETIME;'
sqlite3.OperationalError: no such table: nodes

Don'y know if it helps :/

**Comment by kissgyorgy** [comment]
I have the same issue:

```
16-07-06 23:41:32.060 [ERROR] [acd_cli] - Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: metadata

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.1/bin/acd_cli.py", line 186, in autosync
    sync_node_list(full=False)
  File "/usr/local/var/pyenv/versions/3.5.1/bin/acd_cli.py", line 130, in sync_node_list
    cp_ = cache.KeyValueStorage.get(CacheConsts.CHECKPOINT_KEY) if not full else None
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/acdcli/cache/schema.py", line 233, in get
    val = self.Session.query(Metadate).filter_by(key=key).first()
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: metadata [SQL: 'SELECT metadata."key" AS metadata_key, metadata.value AS metadata_value \nFROM metadata \nWHERE metadata."key" = ?\n LIMIT ? OFFSET ?'] [parameters: ('checkpoint', 1, 0)]
```
