### ISSUE TITLE
OSX Problems unmounting - FileNotFoundError: [Errno 2] No such file or directory: 'fusermount'

### ISSUE THREAD

**Issue by ecchi** [yadayada/acd_cli#213]
It seems to work fine, uploading and opening content. Just unmounting producers errors.

Might because of encfs also being used. I unmount encfs first, then acd. But I think almost every acd unmount I get:
```
acdcli umount ~/.acd-drive 
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1437, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 966, in unmount_action
    return acdcli.acd_fuse.unmount(args.path, args.lazy)
  File "/usr/local/lib/python3.5/site-packages/acdcli/acd_fuse.py", line 724, in unmount
    subprocess.check_call(command)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 579, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'fusermount'
```

OSX 10.11.1, OSXFuse 2.8.2, Python 3.5.0(brew), installed acdcli from this repo guide.

I can't really "re-mount" either, until I reboot.
```
acd_cli mount ~/.acd-drive                                             
mount_osxfusefs: mount point /Users/ecchi/.acd-drive is itself on a OSXFUSE volume
```
tried  acdcli -d mount -i0 --foreground ~/.acd-drive:
```
15-12-05 00:26:39.445 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-12-05 00:26:39.445 [INFO] [acd_cli] - TestPlugin attached.
15-12-05 00:26:39.445 [INFO] [acdcli.api.client] - Initializing ACD with path "/Users/ecchi/Library/Caches/acd_cli".
15-12-05 00:26:39.446 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
15-12-05 00:26:39.446 [INFO] [acdcli.cache.db] - Initializing cache with path "/Users/ecchi/Library/Caches/acd_cli".
15-12-05 00:26:39.457 [INFO] [acdcli.cache.db] - Cache is initialized.
15-12-05 00:26:39.458 [INFO] [acdcli.cache.db] - DB schema version is 1.
15-12-05 00:26:39.469 [INFO] [acd_cli] - Last sync at 2015-12-05 05:26:21.754280.
15-12-05 00:26:39.469 [DEBUG] [acd_cli] - Namespace(acd_client=<acdcli.api.client.ACDClient object at 0x1109fe438>, action='mount', allow_other=False, allow_root=False, cache=<acdcli.cache.db.NodeCache object at 0x110a0d048>, check=0, color=2, debug=1, foreground=True, func=<function mount_action at 0x1109e2840>, interval=0, log=True, modules='', nlinks=False, no_wait=False, nonempty=False, path='/Users/ecchi/.acd-drive', ro=False, single_threaded=False, utf=False, verbose=None)
15-12-05 00:26:39.475 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.028970s
15-12-05 00:26:39.475 [INFO] [acdcli.api.backoff_req] - GET "https://cdws.us-east-1.amazonaws.com/drive/v1/account/quota"
15-12-05 00:26:39.483 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
send: b'GET /drive/v1/account/quota HTTP/1.1\r\nHost: cdws.us-east-1.amazonaws.com\r\nUser-Agent: acdcli.api/0.8.8 python-requests/2.8.1\r\nConnection: keep-alive\r\nAuthorization: Bearer Atza|RandomJunkI'mKeepingAnonymousForSecurityReasons\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server header: Date header: Content-Type header: Content-Length header: Connection header: x-amzn-RequestId header: Content-Encoding header: Cache-Control header: Pragma header: Vary 15-12-05 00:26:39.991 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /drive/v1/account/quota HTTP/1.1" 200 136
mount_osxfusefs: mount point /Users/ecchi/.acd-drive is itself on a OSXFUSE volume
```

**Comment by yadayada** [comment]
Sorry. Please don't use umount action of acd_cli for now and manually ``umount ~/.acd-drive``.
https://github.com/osxfuse/osxfuse/wiki/FAQ#48-how-should-i-unmount-my-fuse-for-os-x-file-system-i-cannot-find-the-fusermount-program-anywhere

**Comment by yadayada** [comment]
Could MacOS/BSD users please test the branch https://github.com/yadayada/acd_cli/tree/umount-macos and report back? ``acdcli umount`` should unmount all ACDFuse mountpoints and ``acdcli umount /mount/point`` the specified mountpoint.

**Comment by msh100** [comment]
@yadayada as requested

```
msh100@Marcus ~ $ acd_cli umount acd_test
umount: illegal option -- u
usage: umount [-fv] [-t fstypelist] special | node
       umount -a[fv] [-h host] [-t fstypelist]
```

You just need to `umount <path>`, not `-u`.

**Comment by yadayada** [comment]
Thanks @msh100, I pushed a new commit. BTW, is there something similar to lazy unmounting on BSD/MacOS? Maybe `-f`?

**Comment by msh100** [comment]
That works now.

Here's the man page for `umount` if it helps.

```
NAME
     umount -- unmount filesystems

SYNOPSIS
     umount [-fv] special | node
     umount -a | -A [-fv] [-h host] [-t type]

DESCRIPTION
     The umount command calls the unmount(2) system call to remove a special device or the remote node
     (rhost:path) from the filesystem tree at the point node.  If either special or node are not provided,
     the appropriate information is taken from the list of filesystems provided by getfsent(3).

     The options are as follows:

     -a      All the filesystems described via getfsent(3) are unmounted.

     -A      All the currently mounted filesystems except the root are unmounted.

     -f      The filesystem is forcibly unmounted.  Active special devices continue to work, but all other
             files return errors if further accesses are attempted.  The root filesystem cannot be
             forcibly unmounted.

     -h host
             Only filesystems mounted from the specified host will be unmounted.  This option implies the
             -A option and, unless otherwise specified with the -t option, will only unmount NFS filesys-
             tems.

     -t type
             Is used to indicate the actions should only be taken on filesystems of the specified type.
             More than one type may be specified in a comma separated list.  The list of filesystem types
             can be prefixed with ``no'' to specify the filesystem types for which action should not be
             taken.  For example, the umount command:

                   umount -A -t nfs,hfs

             umounts all currently-mounted filesystems of the type NFS and HFS.  (The -a option only
             unmounts entries in the /etc/fstab list.)

     -v      Verbose, additional information is printed out as each filesystem is unmounted.
```

**Comment by yadayada** [comment]
I think `--force` may/should be used in lieu of `--lazy` for busy mounts.
Does the generic `acdcli umount` work? If not, `umount -A -t fuse.ACDFuse` may do.

**Comment by msh100** [comment]
Trying to `umount` fails with no params, 

```
msh100@Marcus ~ $ acd_cli umount
mount: illegal option -- l
usage: mount [-dfruvw] [-o options] [-t external_type] special node
       mount [-adfruvw] [-t external_type]
       mount [-dfruvw] special | node
15-12-06 12:58:03.700 [CRITICAL] [acdcli.acd_fuse] - Getting mountpoints failed.
```

I think `mount` is different, because `fuse` is not the correct prefix, check: 

```
msh100@Marcus ~ $ mount -t osxfusefs
ACDFuse on /Users/msh100/acd_test (osxfusefs, nodev, nosuid, synchronous, mounted by msh100)
ACDFuse on /Users/msh100/acd_test2 (osxfusefs, nodev, nosuid, synchronous, mounted by msh100)
```

**Comment by yadayada** [comment]
Hmm, it fails prematurely, unfortunately, because BSD mount doesn't have `-l`. I'll remove that because it's not really necessary.

>I think mount is different, because fuse is not the correct prefix

Ok, could you check if `umount -A -t osxfusefs.ACDFuse` or `umount -A -t ACDFuse` works?

**Comment by msh100** [comment]
Unfortunately I don't think you can narrow it down by more than `osxfusefs` with `mount` or `umount` :(

**Comment by msh100** [comment]
Although it may seem messy, `mount` always outputs `ACDFuse` as the first string. Maybe you can grab the paths from here?

```
msh100@Marcus ~ $ mount -t osxfusefs | grep '^ACDFuse *'
ACDFuse on /Users/msh100/acd_test (osxfusefs, nodev, nosuid, synchronous, mounted by msh100)
ACDFuse on /Users/msh100/acd_test2 (osxfusefs, nodev, nosuid, synchronous, mounted by msh100)
```

**Comment by yadayada** [comment]
Having no subtype is very inconvenient. I made a few adjustments; would you kindly try the latest commit again?

**Comment by msh100** [comment]
This seems good, umount command seem to function as expected (with and without defined path).

**Comment by notDavid** [comment]
@yadayada Hi there, I'm still getting this error, should i create a new issue?

https://gist.github.com/notDavid/4d198a2fe5c6d9e8bb25

acd_cli 0.3.1, api 0.8.7
OS X 10.11.3, Python 3.5.1 (homebrew), OSXFuse 2.8.3

**Comment by yadayada** [comment]
>Hi there, I'm still getting this error, should i create a new issue?

No, please upgrade.

**Comment by notDavid** [comment]
ahhh it's only fixed in master, not yet in a released version. Sorry didn't notice :)
