### ISSUE TITLE
"This session is in 'prepared' state; no further "

### ISSUE THREAD

**Issue by erse80** [yadayada/acd_cli#215]
Any idea?
```
15-12-05 18:00:46.321 [ERROR] [acd_cli] - Traceback (most recent call last):
  File "/usr/local/bin/acd_cli.py", line 176, in autosync
    sync_node_list(full=False)
  File "/usr/local/bin/acd_cli.py", line 114, in sync_node_list
    cp_ = cache.KeyValueStorage.get(CacheConsts.CHECKPOINT_KEY) if not full else None
  File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/schema.py", line 235, in get
    val = self.Session.query(Metadate).filter_by(key=key).first()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2469, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2292, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2571, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2584, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2575, in _connection_from_session
    **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 893, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 202, in _assert_active
    "This session is in 'prepared' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
```

**Comment by yadayada** [comment]
Please test the getattr branch and see if **this** error goes away.
