### ISSUE TITLE
sqlalchemy issue on sync, upload, download (windows)

### ISSUE THREAD

**Issue by sasotepina** [yadayada/acd_cli#217]
I started getting this error today. I don't recall changing or installing anything since the last time it worked. It does not look as acd_cli error, but any help is appreciated.

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\sqlalchemy\dialects\sqlite\pysqlite.py", line 337, in dbapi
    from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
  File "C:\Python34\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Python34\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified procedure could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python34\Scripts\acdcli-script.py", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "C:\Python34\Scripts\acd_cli.py", line 1345, in main
    cache = db.NodeCache(CACHE_PATH, args.check)
  File "C:\Python34\lib\site-packages\acdcli\cache\db.py", line 48, in __init__
    connect_args={'check_same_thread': False})
  File "C:\Python34\lib\site-packages\sqlalchemy\engine\__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "C:\Python34\lib\site-packages\sqlalchemy\engine\strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "C:\Python34\lib\site-packages\sqlalchemy\dialects\sqlite\pysqlite.py", line 339, in dbapi
    raise e
  File "C:\Python34\lib\site-packages\sqlalchemy\dialects\sqlite\pysqlite.py", line 334, in dbapi
    from pysqlite2 import dbapi2 as sqlite
ImportError: No module named 'pysqlite2'
```

**Comment by yadayada** [comment]
Have you tried ~~turning it off and on again~~ reinstalling Python?

**Comment by JigSawFr** [comment]
:+1: Try reinstall of Python package as a library is missing.

**Comment by sasotepina** [comment]
Reinstalling Python does not help.
I'm only getting this at work (tested on two computers so far), so I guess it could be some system or antivirus update messing with Python.

**Comment by sasotepina** [comment]
Yep. Uninstalling Symantec.cloud fixes this issue.

**Comment by JigSawFr** [comment]
@sasotepina disabling would be more usefull if you need this programm ? or by adding an whitlisted app i think

**Comment by sasotepina** [comment]
I tried reinstalling Python, disabling Symantec, changing policy to everything off, restarting. Still the same error.
Uninstalling did the trick.
But interestingly everything (acd_cli) works fine after reinstall of Symatec.cloud.
