### ISSUE TITLE
Directory upload error

### ISSUE THREAD

**Issue by erse80** [yadayada/acd_cli#221]
Hi 

upload directory faild i use 

branche gettattr

# acd_cli upload test/ /Videos
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1430, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 686, in upload_action
    excl_re, args.exclude_path, jobs)
  File "/usr/local/bin/acd_cli.py", line 263, in create_upload_jobs
    rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 292, in traverse_ul_dir
    curr_node = parent.get_child(short_nm)
AttributeError: 'Node' object has no attribute 'get_child'
#

**Comment by yadayada** [comment]
For further issues with the getattr branch, please comment on #216.
