### ISSUE TITLE
OSError: Unable to find libfuse (on mount)

### ISSUE THREAD

**Issue by bgold0** [yadayada/acd_cli#225]
`acd_cli ls` works and shows me all the files in my amazon cloud but when I do the following, I get an error:

>> acd_cli mount /home/plex/amazon

	Traceback (most recent call last):
	  File "/usr/local/bin/acd_cli", line 9, in <module>
	    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
	  File "/usr/local/bin/acd_cli.py", line 1366, in main
	    sys.exit(args.func(args))
	  File "/usr/local/bin/acd_cli.py", line 904, in mount_action
	    import acdcli.acd_fuse
	  File "/usr/local/lib/python3.4/dist-packages/acdcli/acd_fuse.py", line 15, in <module>
	    from acdcli.bundled.fuse import FUSE, FuseOSError as FuseError, Operations
	  File "/usr/local/lib/python3.4/dist-packages/acdcli/bundled/fuse.py", line 76, in <module>
	    raise EnvironmentError('Unable to find libfuse')
	OSError: Unable to find libfuse

Does anyone know what the problem might be?

**Comment by bgold0** [comment]
Was able to fix this with `apt-get -f install`

**Comment by djcuntpaste** [comment]
I am receiving the same error even after trying the apt-get -f install as previously suggested.
