### ISSUE TITLE
autosync: sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by aus** [yadayada/acd_cli#231]
I am getting some `database is locked` errors with the autosync code. I believe this is related to the node cache rework and started with 8997b8c3697d1f7b2b31f3c0bb4150004eb1e321. Maybe missing some `commit()` somewhere? Here's the traceback:

```
[INFO] [acdcli.api.metadata] - Getting changes with checkpoint "CP_KrsadKhoA".
[DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -120.076353s
[DEBUG] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
[DEBUG] [acdcli.api.backoff_req] - {"checkpoint": "CP_xxxxxxxx", "includePurged": "true"}
[INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
[DEBUG] [requests.packages.urllib3.connectionpool] - "POST /drive/v1/changes HTTP/1.1" 200 None
[DEBUG] [acdcli.api.metadata] - Checkpoint: CNqWnuadKhoA
ERROR] [acd_cli] - Traceback (most recent call last):
  File "/usr/local/bin/acd_cli.py", line 176, in autosync
    sync_node_list(full=False)
  File "/usr/local/bin/acd_cli.py", line 131, in sync_node_list
    cache.KeyValueStorage.update({CacheConsts.LAST_SYNC_KEY: time.time()})
  File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/schema.py", line 161, in update
    self.__setitem__(key, dict_[key])
  File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/schema.py", line 147, in __setitem__
    c.execute('INSERT OR REPLACE INTO metadata VALUES (?, ?)', [key, value])
sqlite3.OperationalError: database is locked
```

I will try to get more debug information for you later.

**Comment by saqebakhter** [comment]
With Fuse autosync disabled what can we do do sync fuse with ACD?
