### ISSUE TITLE
Install fails SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Mikelevel** [yadayada/acd_cli#232]
Installed dependencies from https://acd-cli.readthedocs.org/en/latest/setup.html
And then...

**$ sudo pip install --upgrade git+https://github.com/yadayada/acd_cli.git**
Downloading/unpacking git+https://github.com/yadayada/acd_cli.git
  Cloning https://github.com/yadayada/acd_cli.git to /tmp/pip-Z1_XkS-build
  Running setup.py (path:/tmp/pip-Z1_XkS-build/setup.py) egg_info for package from git+https://github.com/yadayada/acd_cli.git
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-Z1_XkS-build/setup.py", line 8
        def read(fname: str) -> str:
                      ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-Z1_XkS-build/setup.py", line 8

    def read(fname: str) -> str:

                  ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-Z1_XkS-build
Storing debug log for failure in /root/.pip/pip.log

**$ sudo cat /root/.pip/pip.log**
------------------------------------------------------------
/usr/bin/pip run on Sat Dec 26 10:46:36 2015
Downloading/unpacking git+https://github.com/yadayada/acd_cli.git
  Cloning https://github.com/yadayada/acd_cli.git to /tmp/pip-Z1_XkS-build
  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git clone -q https://github.com/yadayada/acd_cli.git /tmp/pip-Z1_XkS-build
  Running setup.py (path:/tmp/pip-Z1_XkS-build/setup.py) egg_info for package from git+https://github.com/yadayada/acd_cli.git
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-Z1_XkS-build/setup.py", line 8
        def read(fname: str) -> str:
                      ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-Z1_XkS-build/setup.py", line 8

    def read(fname: str) -> str:

                  ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-Z1_XkS-build
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-Z1_XkS-build

**Comment by yadayada** [comment]
acd_cli doesn't run on Python 2.7.
