### ISSUE TITLE
Sync fails with TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by lox** [yadayada/acd_cli#238]
Running on Python 3.4.5 (docker image `python:3.4`), I get the following error when calling `acd_cli -v sync`:

```
acd_1 | Traceback (most recent call last):
acd_1 |   File "/usr/local/bin/acd_cli", line 9, in <module>
acd_1 |     load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
acd_1 |   File "/usr/local/bin/acd_cli.py", line 1433, in main
acd_1 |     sys.exit(args.func(args))
acd_1 |   File "/usr/local/bin/acd_cli.py", line 954, in mount_action
acd_1 |     allow_root=args.allow_root, allow_other=args.allow_other)
acd_1 |   File "/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 679, in mount
acd_1 |     FUSE(ACDFuse(**args), path,
acd_1 |   File "/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 374, in __init__
acd_1 |     self.free = self.total - self.cache.calculate_usage()
acd_1 | TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

**Comment by lox** [comment]
Looks like this should have been fixed in #238
