### ISSUE TITLE
OSError: Unable to find libfuse (on mount)

### ISSUE THREAD

**Issue by djcuntpaste** [yadayada/acd_cli#242]
When trying to mount my amazon drive I receive the following error;
```
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1433, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 948, in mount_action
    import acdcli.acd_fuse
  File "/usr/local/lib/python3.4/dist-packages/acdcli/acd_fuse.py", line 14, in <module>
    from acdcli.bundled.fuse import FUSE, FuseOSError as FuseError, Operations
  File "/usr/local/lib/python3.4/dist-packages/acdcli/bundled/fuse.py", line 76, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse
```

I have tried running apt-get -f install as suggested in a previous ticket, this did not resolve the issue for me.

Running on Ubuntu 14.04 LTS

**Comment by djcuntpaste** [comment]
Doing some more in previous tickets and used the modprobe fuse command to receive;
```modprobe: FATAL: Module fuse not found.```

opened a ticket with my VPS provider to see if the kernel for FUSE is enabled and if not, if it can be.
