### ISSUE TITLE
DistributionNotFound error on Debian 4.7.2-5.

### ISSUE THREAD

**Issue by kamiller42** [yadayada/acd_cli#249]
When running acdcli, I see the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2708, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests-toolbelt
```

My OS info...
```
root@vs1:~# cat /proc/version
Linux version 2.6.32-39-pve (root@lola) (gcc version 4.7.2 (Debian 4.7.2-5) ) #1 SMP Wed Jun 24 06:39:42 CEST 2015
```

When I installed, I received no errors...

```
root@vs1:~# pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git
Collecting git+https://github.com/yadayada/acd_cli.git
  Cloning https://github.com/yadayada/acd_cli.git to /tmp/pip-6ufnb3-build
Collecting appdirs (from acdcli==0.3.1)
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Collecting colorama (from acdcli==0.3.1)
  Using cached colorama-0.3.6-py2.py3-none-any.whl
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.2/dist-packages (from acdcli==0.3.1)
Collecting requests!=2.9.0,>=2.1.0 (from acdcli==0.3.1)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting requests-toolbelt (from acdcli==0.3.1)
  Using cached requests_toolbelt-0.5.1-py2.py3-none-any.whl
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python3.2/dist-packages (from python-dateutil->acdcli==0.3.1)
Installing collected packages: appdirs, colorama, requests, requests-toolbelt, acdcli
  Running setup.py install for acdcli
Successfully installed acdcli-0.3.1 appdirs-1.4.0 colorama-0.3.6 requests-2.9.1 requests-toolbelt-0.5.1
```

**Comment by yadayada** [comment]
Sorry, I think you'll have to google 'pkg_resources.DistributionNotFound' yourself.

**Comment by breunigs** [comment]
I ran into the same problem yesterday, albeit using a modern Debian (testing). For me, it worked to simply run pip again. Considering Squeeze LTS support runs out in February 2016 anyway, it might be easier to just upgrade your OS if you cannot get it working. (At least I guess you're running Squeeze, since the version you quoted is for gcc packaged within Debian. To be sure, try `cat /etc/debian_version` or `cat /etc/issue`)
