### ISSUE TITLE
Cannot mount

### ISSUE THREAD

**Issue by chesterdkat** [yadayada/acd_cli#271]
Raspberry Pi 2 (single core 512 MB RAM)

I cannot mount:
```
acdcli mount /mnt/acd
fusermount: user has no write access to mountpoint /mnt/acd
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1491, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 998, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/acd_fuse.py", line 685, in mount
    **kwargs
  File "/usr/local/lib/python3.4/dist-packages/acdcli/bundled/fuse.py", line 416, in __init__
    raise RuntimeError(err)
RuntimeError: 1

^C

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/popen_fork.py", line 30, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/usr/local/bin/acd_cli.py", line 85, in signal_handler
    sys.exit(KEYB_INTERR_RETVAL)
SystemExit: 4
```

**Comment by yadayada** [comment]
>fusermount: user has no write access to mountpoint /mnt/acd
