### ISSUE TITLE
acd_cli no longer syncing

### ISSUE THREAD

**Issue by microSCOPED** [yadayada/acd_cli#275]
So, things have been working great until today.

I tried to perform an acd_cli sync and received the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1397, in main
    acd_client = client.ACDClient(CACHE_PATH)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 37, in __init__
    self._load_endpoints()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 56, in _load_endpoints
    self._endpoint_data = self._get_endpoints()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 64, in _get_endpoints
    r = requests.get(AMZ_ENDPOINT_REQ_URL, auth=self.handler)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 343, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 254, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 160, in proxy_manager_for
    **proxy_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/poolmanager.py", line 281, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/poolmanager.py", line 226, in __init__
    proxy = parse_url(proxy_url)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/url.py", line 189, in parse_url
    raise LocationParseError(url)
requests.packages.urllib3.exceptions.LocationParseError: Failed to parse: 96.44.147.34:6060' acd_cli mount
```

Any help would be appreciated!

Mike

**Comment by yadayada** [comment]
Maybe unset your proxy?

**Comment by dany20mh** [comment]
I have same problem.


Danials-iMac:~ Danial$ acdcli s
Getting changesTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 1524, in main
    sys.exit(args.func(args))
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 663, in sync_action
    return sync_node_list(full=args.full)
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 121, in sync_node_list
    silent=False):
TypeError: get_changes() got an unexpected keyword argument 'silent'

**Comment by dany20mh** [comment]
So sync right now is working for me with this commit f845664

**Comment by microSCOPED** [comment]
Sorry, been away for work. I will check tonight and let you guys know. Thanks!

**Comment by microSCOPED** [comment]
I got it sorted.

I removed everything acd_cli, pip, even python. Rebooted the server. the reinstalled everything and it is working fine now. No idea...
