### ISSUE TITLE
the OSXFUSE file system is not available

### ISSUE THREAD

**Issue by dany20mh** [yadayada/acd_cli#277]
Recently and some random times I'm getting this error while I'm trying to mount, would you please help me with this ?
```
16-02-22 14:52:36.527 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-02-22 14:52:36.527 [INFO] [acd_cli] - TestPlugin attached.
16-02-22 14:52:36.527 [INFO] [acdcli.api.client] - Initializing ACD with path "/Users/Danial/Library/Caches/acd_cli".
16-02-22 14:52:36.527 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-02-22 14:52:36.528 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-02-22 14:52:36.583 [INFO] [acd_cli] - Last sync at 2016-02-22 19:42:39.910010.
16-02-22 14:52:36.583 [DEBUG] [acd_cli] - Namespace(acd_client=<acdcli.api.client.ACDClient object at 0x102e7e9b0>, action='mount', allow_other=False, allow_root=False, cache=<acdcli.cache.db.NodeCache object at 0x102e6fac8>, check=0, color=2, debug=1, foreground=True, func=<function mount_action at 0x102e4f598>, gid=20, interval=0, log=False, modules='', nlinks=False, no_wait=False, nonempty=False, path='/Users/Danial/amazon', read_only=False, single_threaded=False, uid=501, umask=18, utf=False, verbose=None)
16-02-22 14:52:36.588 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.060367s
16-02-22 14:52:36.588 [INFO] [acdcli.api.backoff_req] - GET "https://cdws.us-east-1.amazonaws.com/drive/v1/account/quota"
16-02-22 14:52:36.591 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
send: b'GET /drive/v1/account/quota HTTP/1.1\r\nHost: cdws.us-east-1.amazonaws.com\r\nAccept-Encoding: gzip, deflate\r\nAuthorization: Bearer Atza|IQEBLjAsAhRSIbJY61UPr1BaePxIpNmgBmpYkwIUPuQ9HLhOL1k8SXCMa5x8PdFHZpc_VVfVmaVls6PcM-fVET-y94ciJiv39xj_KdH9IrjW1W42oW1cdVU6Cf8Wq1ELrPvhJLbByq90PVlYsTZ7UBCKnkTlawdShywSDawv5OfY_RB2IX8kOOIIZTgP7OkYlx-_M9GBpUAwn4JGlf8U9hopzBIErj34FuTsTAkowkLmneshFDgoyaMGyPUffmwfAJx4wFkszgnZpseJTaqMKUvDFkT98_YVHnSXp8KA4Zkwr9aJjqaGlHfDqLFaT0kRho9hu_RGWKiCq7Wk2LlPZsUqeby4Bjw5uPZ1bTC2b6CDIJaDzhAEDMwBfGSv2TUl0Duj9mgHT6qw6Hwd1Wvdx046rFGZ_pDzWQLn-6lTco6ObRwaoUrZivD1xNSHQNerdFsP\r\nConnection: keep-alive\r\nUser-Agent: acdcli.api/0.8.9 python-requests/2.9.1\r\nAccept: */*\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server header: Date header: Content-Type header: Content-Length header: Connection header: x-amzn-RequestId header: Content-Encoding header: Cache-Control header: Pragma header: Vary 16-02-22 14:52:37.046 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /drive/v1/account/quota HTTP/1.1" 200 175
/Library/Filesystems/osxfusefs.fs/Support/osxfusefs.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
the OSXFUSE file system is not available (71)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 1524, in main
    sys.exit(args.func(args))
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 1029, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/acd_fuse.py", line 702, in mount
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/bundled/fuse.py", line 416, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

**Comment by dany20mh** [comment]
And also I'm getting this



fuse: unknown option `big_writes'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 1524, in main
    sys.exit(args.func(args))
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 1029, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/acd_fuse.py", line 702, in mount
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/bundled/fuse.py", line 416, in __init__
    raise RuntimeError(err)
RuntimeError: 1
mount_osxfusefs: failed to mount /Users/Danial/amazon@/dev/osxfuse0: Socket is not connected

**Comment by dany20mh** [comment]
I download the zip file until commit 766a5a9 and copy paste it in the folder, I get rid of the second error (my second comment)

**Comment by jgillman** [comment]
@dany20mh What version of OSXFUSE are you running?

**Comment by dany20mh** [comment]
acd_cli 0.3.1, api 0.8.8
I was on the OSXFUSE 3.2.0 and then that happened and then I moved to 2.8.3 and second error happened (these were with the latest commit from the git)
And then I download the zip from the commit 766a5a9 and replaced it so I fixed the second problem.
But for the first problem I still don't know cause it's random.

**Comment by jgillman** [comment]
I saw https://github.com/yadayada/acd_cli/commit/fff7531e090e4659287ab577a3bd29f1773104b4 and updated with:

```
$ pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git
```

Mounting with `acdcli mount /my/mount/point` works!

**Comment by dany20mh** [comment]
Yes, with fff7531 mounting sync is working but I can't confirm anything about the first issue that I still have it or not, cause that comes randomly.

**Comment by berot3** [comment]
not sure if its ok to comment in a closed issue, but I get the exact same issue:
````
16-10-23 19:46:40.974 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-10-23 19:46:40.974 [INFO] [acd_cli] - TestPlugin attached.
16-10-23 19:46:40.974 [INFO] [acd_cli] - Settings path is "/Users/user/Library/Application Support/acd_cli".
16-10-23 19:46:40.975 [INFO] [acdcli.api.client] - Initializing ACD with path "/Users/user/Library/Caches/acd_cli".
16-10-23 19:46:40.975 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-10-23 19:46:40.984 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-10-23 19:46:40.985 [INFO] [acd_cli] - Last sync at 2016-10-23 17:36:13.269030.
16-10-23 19:46:40.991 [INFO] [acdcli.api.backoff_req] - GET "https://cdws.us-east-1.amazonaws.com/drive/v1/account/quota"
16-10-23 19:46:41.000 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
mount_osxfuse: the OSXFUSE file system is not available (255)
fuse: failed to mount file system: Undefined error: 0
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1611, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 1097, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/usr/local/lib/python3.5/site-packages/acdcli/acd_fuse.py", line 716, in mount
    FUSE(ACDFuse(**args), path, subtype=ACDFuse.__name__, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/fuse.py", line 480, in __init__
    raise RuntimeError(err)
RuntimeError: 1
````

with acd_cli 0.3.2, api 0.9.0 on macOS 10.12

Though I set acd_cli up the first time and could not make it work before, so for me it happens every time and not just randomly.
