### ISSUE TITLE
fuse: unknown option `big_writes'

### ISSUE THREAD

**Issue by philnord** [yadayada/acd_cli#278]
```
Philips-MacBook-Pro:plex Phil$ acd_cli mount /Users/Phil/plex/.acd-sorted/
fuse: unknown option `big_writes'
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1524, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 1029, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/usr/local/lib/python3.5/site-packages/acdcli/acd_fuse.py", line 702, in mount
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/acdcli/bundled/fuse.py", line 416, in __init__
    raise RuntimeError(err)
RuntimeError: 1
mount_osxfusefs: failed to mount /Users/Phil/plex/.acd-sorted@/dev/osxfuse1: Socket is not connected
```
Started getting this error when mounting. Was ok the 20th of Feb.

**Comment by dany20mh** [comment]
Well you can fix it if you just copy an older version of the acdcli into it's folder and you won't get this error.

**Comment by dany20mh** [comment]
So I copied this commit f845664 and the big_writes and sync is working.

**Comment by philnord** [comment]
Thanks for the quick fix
