### ISSUE TITLE
database locked

### ISSUE THREAD

**Issue by dany20mh** [yadayada/acd_cli#281]
I'm getting this error when I'm trying to sync
```
Danials-iMac:~ Danial$ acdcli sync
Getting changes..
Inserting nodesTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 1524, in main
    sys.exit(args.func(args))
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 663, in sync_action
    return sync_node_list(full=args.full)
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 133, in sync_node_list
    cache.insert_nodes(changeset.nodes, partial=not full)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/cache/sync.py", line 71, in insert_nodes
    self.insert_folders(folders)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/cache/sync.py", line 99, in insert_folders
    f['status']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/cache/cursors.py", line 24, in __exit__
    self.conn.commit()
sqlite3.OperationalError: database is locked
```

**Comment by yadayada** [comment]
Try to kill the process that's locking the database.

**Comment by dany20mh** [comment]
Got it, thanks :)
