### ISSUE TITLE
ValueError: time data does not match format '%Y-%m-%d %H:%M:%S.%f+00:00'

### ISSUE THREAD

**Issue by kwiky** [yadayada/acd_cli#282]
Hi !

I can't mount a fuse driver because of date format error, see below : 
```
16-02-28 15:18:06.306 [DEBUG] [acdcli.acd_fuse] - -> access / (0,)
16-02-28 15:18:06.306 [DEBUG] [acdcli.acd_fuse] - <- access 0
16-02-28 15:18:06.306 [DEBUG] [acdcli.acd_fuse] - -> getattr / (None,)
16-02-28 15:18:06.307 [DEBUG] [acdcli.acd_fuse] - <- getattr '[Unhandled Exception]'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/acdcli/cache/query.py", line 10, in datetime_from_string
    dt = datetime.strptime(dt, '%Y-%m-%d %H:%M:%S.%f+00:00')
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/_strptime.py", line 500, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data '2015-12-11 15:53:48.333000' does not match format '%Y-%m-%d %H:%M:%S.%f+00:00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/acdcli/bundled/fuse.py", line 432, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python3.4/site-packages/acdcli/bundled/fuse.py", line 440, in getattr
    return self.fgetattr(path, buf, None)
  File "/usr/local/lib/python3.4/site-packages/acdcli/bundled/fuse.py", line 686, in fgetattr
    attrs = self.operations('getattr', path.decode(self.encoding), fh)
  File "/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 348, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 431, in getattr
    st_mtime=node.modified.timestamp(),
  File "/usr/local/lib/python3.4/site-packages/acdcli/cache/query.py", line 127, in modified
    return datetime_from_string(self.mod)
  File "/usr/local/lib/python3.4/site-packages/acdcli/cache/query.py", line 12, in datetime_from_string
    dt = datetime.strptime(dt, '%Y-%m-%d %H:%M:%S+00:00')
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/_strptime.py", line 500, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data '2015-12-11 15:53:48.333000' does not match format '%Y-%m-%d %H:%M:%S+00:00'
```

This is how i had this log : 
```
acd_cli -d -nl mount -i0 -fg ~/acd
```

**Comment by kwiky** [comment]
I've just completely removed cache folder and start again and it works again.
