### ISSUE TITLE
No Module name _sqlite3

### ISSUE THREAD

**Issue by zenjabba** [yadayada/acd_cli#293]
After updating acd_cli with 

"pip3.4 install --upgrade git+https://github.com/yadayada/acd_cli.git"

I now get this error message... any suggestions?

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/bin/acd_cli.py", line 22, in <module>
    from acdcli.cache import format, db
  File "/usr/local/lib/python3.4/site-packages/acdcli/cache/db.py", line 4, in <module>
    import sqlite3
  File "/usr/local/lib/python3.4/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.4/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'

**Comment by zenjabba** [comment]
Solved by running python3 rather than python3.4
