### ISSUE TITLE
Random errors while uploading

### ISSUE THREAD

**Issue by jurecotic** [yadayada/acd_cli#3]
I started uploading a folder with about 1000 files and got this error a couple of times:

```
Traceback (most recent call last):
  File "./acd_cli.py", line 46, in upload
    r = content.upload_file(path, parent_id)
  File "/Users/jure/acd_cli/acd/content.py", line 70, in upload_file
    raise RequestError(status, body)
acd.common.RequestError: 400


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./acd_cli.py", line 416, in <module>
    main()
  File "./acd_cli.py", line 412, in main
    args.func(args)
  File "./acd_cli.py", line 184, in upload_action
    upload(args.file, parent)
  File "./acd_cli.py", line 38, in upload
    upload_folder(path, parent_id)
  File "./acd_cli.py", line 95, in upload_folder
    upload_folder(full_path, curr_node.id)
  File "./acd_cli.py", line 95, in upload_folder
    upload_folder(full_path, curr_node.id)
  File "./acd_cli.py", line 97, in upload_folder
    upload(full_path, curr_node.id)
  File "./acd_cli.py", line 54, in upload
    print('Uploading "%s" failed. Code: %s, msg: %s' % e.status_code, e.msg)
TypeError: not enough arguments for format string
```

Is this a server error? Another time I got a 504. Maybe if you could make it so that it would continue uploading the res of files, despite the error or try reuploading the file.

**Comment by yadayada** [comment]
That's an error handling an error. The format string is missing its first argument, namely the local file name. It should be 
```python
print('Uploading "%s" failed. Code: %s, msg: %s' % short_nm, e.status_code, e.msg)
```
Additionally, your particular error response did not include a message from Amazon, so it's unclear what happened exactly. That's another thing I didn't foresee.

A quick fix is to alter the RequestError class in the file `acd/common.py`

```python
class RequestError(Exception):
    def __init__(self, status_code, msg):
        self.status_code = status_code
        if msg:
            self.msg = msg
        else:
            self.msg = '{"message":"acd_cli: internal: no body received."}'

    def __str__(self):
        return str(self.status_code) + '\n' + self.msg
```

I had a couple of status 400 errors while trying to add files to folders that are in the trash. A 503 status usually indicates a programmer's fault somewhere, but 504 is new to me.

**Comment by yadayada** [comment]
Will be fixed in the next commit.
