### ISSUE TITLE
acd_cli debian failure

### ISSUE THREAD

**Issue by solcen** [yadayada/acd_cli#303]
Traceback (most recent call last):
  File "/media/sdl1/home/n4n/python/python3/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/media/sdl1/home/n4n/python/python3/bin/acd_cli.py", line 1345, in main
    cache = db.NodeCache(CACHE_PATH, args.check)
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/site-packages/acdcli/cache/db.py", line 48, in __init__
    connect_args={'check_same_thread': False})
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 334, in dbapi
    from pysqlite2 import dbapi2 as sqlite
ImportError: No module named 'pysqlite2'

**Comment by msh100** [comment]
How did you install `acdcli`?

It just seems the dependencies are not installed, they should be if following the [documented installation steps](https://acd-cli.readthedocs.org/en/latest/setup.html). I recommend using the pip method but it shouldn't make too much of a difference.

**Comment by belovanton** [comment]
You can use docker for easy deploy it add that to your .bashrc
```
alias acd_cli="docker run --rm  -v ~/.cache/acd_cli:/home/user/.cache/acd_cli -v /tmp:/tmp -v /home/acd:/home/acd zeitgeist/docker-acdcli"
alias acdcli=acd_cli

```

**Comment by solcen** [comment]
Re: msh100
It installed with all dependencies, call is  to pysqlite2 (python 2 module)
`pip3 install --upgrade --pre acdcli`
Re: belovanton
Its deployed on feralhosting slot, so no root access there. I'll try it your way, thanks

**Comment by solcen** [comment]
Latest - fresh install, Anton's aliases - no change
`[athena ~] alias python='~/python/python3/bin/python3.5'
[athena ~] PATH=~/python/python3/bin/
[athena ~] ~/python/python3/bin/acd_cli init
Traceback (most recent call last):
  File "/media/sdl1/home/n4n/python/python3/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/media/sdl1/home/n4n/python/python3/bin/acd_cli.py", line 22, in <module>
    from acdcli.cache import format, db
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/site-packages/acdcli/cache/db.py", line 4, in <module>
    import sqlite3
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/media/sdl1/home/n4n/python/python3/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'`

**Comment by madyoda** [comment]
@solcen did you ever find a fix to this? I find myself in the same situation on FeralHosting.
`ImportError: No module named '_sqlite3'`
