### ISSUE TITLE
Mulitple issues when python 3.4 updated

### ISSUE THREAD

**Issue by metalgeekstl** [yadayada/acd_cli#309]
After running apt-get upgrade acdcli returns the same error with all commands to it. 
```
user@machine:~$ acdcli
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/_compat.py", line 17, in <module>
    from requests.packages.urllib3 import connection
ImportError: No module named 'requests.packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/bin/acd_cli.py", line 20, in <module>
    from acdcli.api import client
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 11, in <module>
    from .content import ContentMixin
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/content.py", line 10, in <module>
    from requests_toolbelt import MultipartEncoder
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/_compat.py", line 22, in <module>
    from urllib3 import connection
ImportError: cannot import name 'connection'

Tried to re-install via pip3 which completed but same error occurs.

**Comment by yadayada** [comment]
I think this is related to https://github.com/sigmavirus24/requests-toolbelt/issues/121.

**Comment by metalgeekstl** [comment]
I tried editing the files mentioned [here](https://github.com/sigmavirus24/requests-toolbelt/issues/121#issuecomment-166156651) but got another set of errors. Now it couldn't find "poolmanager"

Is this an issue that sigmavirus24 has to fix?

**Comment by belovanton** [comment]
Hi, the easy way resolve all depends and versions upgrades - use docker.

**Comment by metalgeekstl** [comment]
And now I have to blow away my server and learn docker. ;)

**Comment by belovanton** [comment]
Look here https://github.com/alexzeitgeist/docker-acd_cli u can easy make your own image with working acd cli. If u want I can make image for u and upload in docker registry. And u just pull it.

**Comment by metalgeekstl** [comment]
@belovanton Thanks, but I'd rather figure it out for myself. Not developing anyway, just trying to run ACDCLI for my media server. I know what I did to break it in the 1st place.

**Comment by belovanton** [comment]
I just have the same issue, and after reinstall python over and over again I found this project, making my own docker image and just pool it on each server when I need it, doesnt matter what linux on it.

**Comment by belovanton** [comment]
@yadayada IMHO u can make docker image with your application and add alternative way to install it in your readme.
