### ISSUE TITLE
Cannot Init

### ISSUE THREAD

**Issue by HorikawaOtane** [yadayada/acd_cli#318]
When I try to run:

`acd_cli --debug init
`

It returns the following error (the same thing happens without --debug):

```
16-05-01 06:24:38.336 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-05-01 06:24:38.337 [INFO] [acd_cli] - TestPlugin attached.
16-05-01 06:24:38.337 [INFO] [acd_cli] - Settings path is "/home/myUsername/.config/acd_cli".
Traceback (most recent call last):
  File "/usr/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/bin/acd_cli.py", line 1520, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

```

I'm using acd_cli-git on Arch Linux.

**Comment by HorikawaOtane** [comment]
Installing from pip worked.

**Comment by yadayada** [comment]
Somehow, you got a version mismatch of acd_cli.py and the api package there.

>Installing from pip worked.

Well...
