### ISSUE TITLE
TypeError: unsupported operand type(s) for |=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by xcolsanders** [yadayada/acd_cli#321]
Using python 2.7.9. Have been using acdcli for a while. The token showed as expired one day and now I this after running acd_cli -v upload /backups /

Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1366, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 643, in upload_action
    args.deduplicate, excl_re, args.exclude_path, jobs)
  File "/usr/local/bin/acd_cli.py", line 257, in create_upload_jobs
    exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 311, in traverse_ul_dir
    overwr, force, dedup, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 257, in create_upload_jobs
    exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 311, in traverse_ul_dir
    overwr, force, dedup, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 257, in create_upload_jobs
    exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 311, in traverse_ul_dir
    overwr, force, dedup, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 257, in create_upload_jobs
    exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 311, in traverse_ul_dir
    overwr, force, dedup, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 257, in create_upload_jobs
    exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 311, in traverse_ul_dir
    overwr, force, dedup, exclude, exclude_paths, jobs)
TypeError: unsupported operand type(s) for |=: 'int' and 'NoneType'

Tried getting a new token, and reinstalling acd_cli via pip.

**Comment by yadayada** [comment]
Please install the GitHub version.

**Comment by xcolsanders** [comment]
Switched to the github version and got:
```
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1559, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 783, in upload_action
    excl_re, args.exclude_path, jobs)
  File "/usr/local/bin/acd_cli.py", line 355, in create_upload_jobs
    rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 413, in traverse_ul_dir
    overwr, force, dedup, rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 355, in create_upload_jobs
    rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 413, in traverse_ul_dir
    overwr, force, dedup, rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 355, in create_upload_jobs
    rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 413, in traverse_ul_dir
    overwr, force, dedup, rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 355, in create_upload_jobs
    rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 413, in traverse_ul_dir
    overwr, force, dedup, rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 355, in create_upload_jobs
    rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 413, in traverse_ul_dir
    overwr, force, dedup, rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 355, in create_upload_jobs
    rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 413, in traverse_ul_dir
    overwr, force, dedup, rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 355, in create_upload_jobs
    rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 413, in traverse_ul_dir
    overwr, force, dedup, rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 355, in create_upload_jobs
    rsf, exclude, exclude_paths, jobs)
  File "/usr/local/bin/acd_cli.py", line 412, in traverse_ul_dir
    ret_val |= create_upload_jobs(dirs, full_path, curr_node.id,
AttributeError: 'NoneType' object has no attribute 'id'

```
