### ISSUE TITLE
acd_cli give a sqlite_transfer_bindings error

### ISSUE THREAD

**Issue by KoreanTie** [yadayada/acd_cli#322]
```
root@ubuntu:~# acd_cli sync
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/bin/acd_cli.py", line 22, in <module>
    from acdcli.cache import format, db
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/db.py", line 5, in <module>
    import sqlite3
  File "/usr/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python3.5/lib-dynload/_sqlite3.cpython-35m-x86_64-linux-gnu.so: undefined symbol: sqlite3_transfer_bindings
```

This error starts happening and the only way I've been able to fix it is by reinstalled acd_cli.

**Comment by yadayada** [comment]
I was hoping someone could help you out. All I can tell you is that there is something awry with your Python installation.
