### ISSUE TITLE
Setuptools and urllib3 problem

### ISSUE THREAD

**Issue by kz0** [yadayada/acd_cli#323]
Hello,

Upgraded my system today and i'm getting the following error:

```
Traceback (most recent call last):
  File "/usr/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/pkg_resources/__init__.py", line 549, in load_entry_point
  File "/usr/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/pkg_resources/__init__.py", line 2709, in load_entry_point
  File "/usr/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/pkg_resources/__init__.py", line 2369, in load
  File "/usr/lib/python3.5/site-packages/setuptools-19.4-py3.5.egg/pkg_resources/__init__.py", line 2375, in resolve
  File "/usr/bin/acd_cli.py", line 20, in <module>
    from acdcli.api import client
  File "/usr/lib/python3.5/site-packages/acdcli/api/client.py", line 5, in <module>
    import requests
  File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'

```
Python version 3.5.1

Linux-4.4.9-1-ARCH-armv5tel-with-arch

**Comment by yadayada** [comment]
http://lmgtfy.com/?q=ImportError%3A+cannot+import+name+%27DependencyWarning%27
