### ISSUE TITLE
sqlite3.DatabaseError: file is encrypted or is not a database

### ISSUE THREAD

**Issue by thrillfall** [yadayada/acd_cli#329]
I am using acd_cli on a raspberry pi 2 with raspbian wheezy installed. I was using acd_cli successfully for some days but now i get the following error whenever i try to sync:
```
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1532, in main
    cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/db.py", line 70, in __init__
    self.integrity_check(check)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/db.py", line 135, in integrity_check
    r = c.execute('PRAGMA integrity_check;')
sqlite3.DatabaseError: file is encrypted or is not a database
```
Python: 3.4.2
OS: Linux-4.1.19-v7+-armv7l-with-debian-8.0

**Comment by thrillfall** [comment]
sorry, i was deleting the wrong nodes.db from a different user. consider this closed
