### ISSUE TITLE
Problem with big files

### ISSUE THREAD

**Issue by jhdscript** [yadayada/acd_cli#335]
Hello, when I upload large file with rsync on acd mount drive, the file doesn t have the good name

ex: 7C5C3D44BC58D590451D593BE01D2A.zc is .7C5C3D44BC58D590451D593BE01D2A.zc.Yjn9iF

Someone have the same issue ?

**Comment by tintop2k** [comment]
That's how rsync works by default. It's nothing to do with acd_cli

https://superuser.com/questions/579001/rsync-does-it-create-a-temp-file-during-transfer

**Comment by jhdscript** [comment]
I use this cmd rsync -ah --progress --remove-source-files $@
maybe I made a mistake :/

**Comment by yadayada** [comment]
I just had a look at the ACDFuse write thread implementation. There currently is no proper timeout handling for big files like there is for the CLI upload/overwrite. So, if there is a timeout, rsync will presumably not rename that temp file.

To confirm this, please mount with ``acd_cli -d mount -fg </mount/point>`` and look for an error message like ``Error writing node "foo". ... `` near a flush or release operation on your file and post it.

Some more questions:
1) Are the files uploaded completely?
2) How large are we talking? 10GiB?
3) Do you get an rsync error message?

**Comment by grince** [comment]
Hi,
I just tried to use acd_cli for my backup where I want to encrypt everything; so I use scduply / duplicity for the backup work.
There I use the mounted Amazon WebDrive and my backup files are ~100MB each.

When i try to send the backup-files to the webdrive, I get the following:

reply: 'HTTP/1.1 201 Created\r\n'
header: Content-Type header: Date header: Server header: x-amzn-RequestId header: Content-Length header: Connection 16-07-31 07:39:52.826 [DEBUG] [requests.packages.urllib3.connectionpool] - "POST /cdproxy/nodes?suppress=deduplication HTTP/1.1" 201 616
16-07-31 07:39:52.828 [DEBUG] [acdcli.api.backoff_req] - x-amzn-RequestId: foobarbaz (redacted)
16-07-31 07:39:57.836 [DEBUG] [acdcli.acd_fuse] - <- create '[Unhandled Exception]'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python3.4/dist-packages/fuse.py", line 736, in create
    fi.fh = self.operations('create', path, mode)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/acd_fuse.py", line 360, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/acd_fuse.py", line 545, in create
    self.cache.insert_node(r)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/sync.py", line 80, in insert_node
    self.insert_nodes([node])
  File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/sync.py", line 72, in insert_nodes
    self.insert_files(files)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/sync.py", line 117, in insert_files
    f['status']
sqlite3.OperationalError: database is locked




So, as far as I see there is a locking issue with the sqlite3...
