### ISSUE TITLE
New library needed?

### ISSUE THREAD

**Issue by dansku** [yadayada/acd_cli#34]
Now whenever I try to install, it gives this error

```
 Running setup.py (path:/tmp/pip-vdq1vkdi-build/setup.py) egg_info for package from file:///root
    Traceback (most recent call last):
      File "/tmp/pip-vdq1vkdi-build/acdcli/api/content.py", line 10, in <module>
        from requests_toolbelt import MultipartEncoder
      File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/__init__.py", line 19, in <module>
        from .adapters import SSLAdapter, SourceAddressAdapter
      File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
        from .ssl import SSLAdapter
      File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/ssl.py", line 13, in <module>
        from requests.packages.urllib3.poolmanager import PoolManager
    ImportError: No module named 'requests.packages'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-vdq1vkdi-build/setup.py", line 4, in <module>
        from acd_cli import __version__
      File "/tmp/pip-vdq1vkdi-build/acd_cli.py", line 18, in <module>
        from acdcli.api import *
      File "/tmp/pip-vdq1vkdi-build/acdcli/api/content.py", line 12, in <module>
        from acdcli.bundled.encoder import MultipartEncoder
      File "/tmp/pip-vdq1vkdi-build/acdcli/bundled/encoder.py", line 12, in <module>
        from requests.packages.urllib3 import fields
    ImportError: No module named 'requests.packages'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "/tmp/pip-vdq1vkdi-build/acdcli/api/content.py", line 10, in <module>

    from requests_toolbelt import MultipartEncoder

  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/__init__.py", line 19, in <module>

    from .adapters import SSLAdapter, SourceAddressAdapter

  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>

    from .ssl import SSLAdapter

  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/ssl.py", line 13, in <module>

    from requests.packages.urllib3.poolmanager import PoolManager

ImportError: No module named 'requests.packages'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-vdq1vkdi-build/setup.py", line 4, in <module>

    from acd_cli import __version__

  File "/tmp/pip-vdq1vkdi-build/acd_cli.py", line 18, in <module>

    from acdcli.api import *

  File "/tmp/pip-vdq1vkdi-build/acdcli/api/content.py", line 12, in <module>

    from acdcli.bundled.encoder import MultipartEncoder

  File "/tmp/pip-vdq1vkdi-build/acdcli/bundled/encoder.py", line 12, in <module>

    from requests.packages.urllib3 import fields

ImportError: No module named 'requests.packages'

----------------------------------------
```

I guess I'm missing a package.

**Comment by yadayada** [comment]
Which operating system are you working on?

Please try running ``pip3 install --upgrade requests requests-toolbelt`` first. Maybe you must uninstall your distribution's package for requests, too.
