### ISSUE TITLE
Status 429, "System Unavailable"

### ISSUE THREAD

**Issue by jbuchbinder** [yadayada/acd_cli#348]
I've been seeing a higher-than-normal incidence of messages like this:

`16-06-16 03:21:01.595 [ERROR] [acd_cli] - Uploading "--filename-redacted--" failed. RequestError: 429, {"logref":"e0ce31c7-3392-11e6-9377-eff4fab6362b","message":"System unavailable. Please back off for a while and try again later","code":""}.`

Even with retry set to a relatively high value (5 or 6), some files, usually files over 1GB (but that may be random) tend to exhaust their retries with that status and acd_cli ends up stopping. I'm not sure if this is an ACD limiter of some sort, an upstream issue, or something local to my own install (running an extremely recent git version).

**Comment by xiojason** [comment]
I've also observed this yesterday and today. Additionally, starting minutes ago, I can full-sync ok, but even an attempt to move/rename a node fails with the 429 error.

**Comment by umeku** [comment]
Same thing here. But I do think this is something on Amazon side of things, as I've started getting the same 429 error when using rclone to backup to ACD (which is completely unrelated to acd_cli).

**Comment by jbuchbinder** [comment]
Confirmed, I'm seeing the same behavior with rclone.

**Comment by animetosho** [comment]
Same here, plus I get a crash. (note, I'm not using the latest version of acdcli, but it shouldn't be too old)

	16-06-18 03:43:12.590 [ERROR] [acdcli.api.backoff_req] - Error getting node list.
	16-06-18 03:43:12.646 [ERROR] [acd_cli] - Traceback (most recent call last):
	  File "/usr/local/bin/acd_cli.py", line 538, in upload_stream
		deduplication=dedup)
	  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/content.py", line 192, in upload_stream
		raise RequestError(r.status_code, r.text)
	acdcli.api.common.RequestError: RequestError: 408, [acd_api] no body received.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/bin/acd_cli.py", line 217, in wrapped
		ret_val = f(*args, **kwargs)
	  File "/usr/local/bin/acd_cli.py", line 544, in upload_stream
		return upload_timeout(parent_id, log_fname, hasher.get_result(), None, False)
	  File "/usr/local/bin/acd_cli.py", line 286, in upload_timeout
		l = acd_client.list_children(parent_id)
	  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/metadata.py", line 169, in list_children
		l = self.BOReq.paginated_get(self.metadata_url + 'nodes/' + node_id + '/children')
	  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/backoff_req.py", line 143, in paginated_get
		raise RequestError(r.status_code, r.text)
	acdcli.api.common.RequestError: RequestError: 429, {"logref":"04901803-34f6-11e6-811f-49c1876a79f2","message":"System unavailable. Please back off for a while and try again later
	"}

If the above crash still happens in acdcli, it would be nice if it could be handled more gracefully.
