### ISSUE TITLE
Error on the second sync

### ISSUE THREAD

**Issue by airstand** [yadayada/acd_cli#35]
Hello,

I have successfully done with the first sync , but I get the error, listed below , on the second sync:

```
root@raspberry:~/acd_cli# acd_cli sync
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.2.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 914, in main
    if not common.init(CACHE_PATH):
  File "/usr/local/lib/python3.2/dist-packages/acdcli/api/common.py", line 61, in init
    return oauth.init(path) and _load_endpoints()
  File "/usr/local/lib/python3.2/dist-packages/acdcli/api/oauth.py", line 40, in init
    _get_data()
  File "/usr/local/lib/python3.2/dist-packages/acdcli/api/oauth.py", line 62, in _get_data
    oauth_data = json.load(oa)
  File "/usr/lib/python3.2/json/__init__.py", line 264, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.2/json/__init__.py", line 309, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.2/json/decoder.py", line 353, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.2/json/decoder.py", line 369, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 2 column 196 (char 213)
```

**Comment by yadayada** [comment]
Please have a look at your oauth file which should be located in ``~/.cache/acd_cli/oauth_data``.
If it is not there, check the output ``acd_cli -v sync`` to see where your cache path is.

This is how it should look like
![screenshot-oauth_data - cache-acd_cli - vim](https://cloud.githubusercontent.com/assets/4608955/7680154/17a4e3ea-fd64-11e4-978c-9cae5c8d3830.png)

If it doesn't, you can simply delete this file and redo the OAuth procedure.

**Comment by airstand** [comment]
Hi , 
I have made the access_token and refresh_token on one line.

But the next error is:

Syncing...
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.2.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 929, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 428, in sync_action
    r = sync_node_list(full=args.full)
  File "/usr/local/bin/acd_cli.py", line 123, in sync_node_list
    db.init(CACHE_PATH)
  File "/usr/local/lib/python3.2/dist-packages/acdcli/cache/db.py", line 238, in init
    sqlite = ctypes.CDLL(find_library('sqlite3'))
  File "/usr/lib/python3.2/ctypes/util.py", line 210, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/lib/python3.2/ctypes/util.py", line 202, in _findSoname_ldconfig
    with contextlib.closing(os.popen('LC_ALL=C LANG=C /sbin/ldconfig -p 2>/dev/null')) as f:
  File "/usr/lib/python3.2/os.py", line 786, in popen
    bufsize=buffering)
  File "/usr/lib/python3.2/subprocess.py", line 745, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.2/subprocess.py", line 1207, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory


:)

This is raspberry-pi with 1GB of ram :)

**Comment by yadayada** [comment]
> I have made the access_token and refresh_token on one line.

What does that mean?

**Comment by airstand** [comment]
This means that the key is just on one line - it isn't separated on different lines.

**Comment by yadayada** [comment]
> This means that the key is just on one line - it isn't separated on different lines.

Mine is as well; the lines are merely soft-wrapped.

Could you actually see what the the error was in the "access_token" line?

Well, I don't think I can do much about the memory usage. About 100-150MB will be necessary.

**Comment by airstand** [comment]
now everything looks fine with the oauth_data file.

But this is still exists:

root@raspberry:~/acd_cli# acd_cli sync
Syncing...
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.2.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 929, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 428, in sync_action
    r = sync_node_list(full=args.full)
  File "/usr/local/bin/acd_cli.py", line 123, in sync_node_list
    db.init(CACHE_PATH)
  File "/usr/local/lib/python3.2/dist-packages/acdcli/cache/db.py", line 238, in init
    sqlite = ctypes.CDLL(find_library('sqlite3'))
  File "/usr/lib/python3.2/ctypes/util.py", line 210, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/lib/python3.2/ctypes/util.py", line 202, in _findSoname_ldconfig
    with contextlib.closing(os.popen('LC_ALL=C LANG=C /sbin/ldconfig -p 2>/dev/null')) as f:
  File "/usr/lib/python3.2/os.py", line 786, in popen
    bufsize=buffering)
  File "/usr/lib/python3.2/subprocess.py", line 745, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.2/subprocess.py", line 1207, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
root@raspberry:~/acd_cli#

I saw that acd_cli process take more than 300mb memory and then stops with the error listed above.

**Comment by yadayada** [comment]
```
--- db.py	2015-05-16 01:23:02.600536050 +0200
+++ db_b.py	2015-05-18 17:01:53.311763042 +0200
@@ -233,12 +233,15 @@
     logger.info('Initializing cache with path "%s".' % os.path.realpath(path))
     db_path = os.path.join(path, 'nodes.db')
 
-    import ctypes
-    from ctypes.util import find_library
-    sqlite = ctypes.CDLL(find_library('sqlite3'))
-    if not sqlite.sqlite3_threadsafe():
-        # http://www.sqlite.org/c3ref/threadsafe.html
-        logger.warning('Your sqlite3 version was compiled without mutexes. It is not thread-safe.')
+    try:
+        import ctypes
+        from ctypes.util import find_library
+        sqlite = ctypes.CDLL(find_library('sqlite3'))
+        if not sqlite.sqlite3_threadsafe():
+            # http://www.sqlite.org/c3ref/threadsafe.html
+            logger.warning('Your sqlite3 version was compiled without mutexes. It is not thread-safe.')
+    except:
+        pass
 
     global Session
     global engine
```

Please save the above text as "db.patch" and run 
``patch /usr/local/lib/python3.2/dist-packages/acdcli/cache/db.py < db.patch``

**Comment by airstand** [comment]
The process stays on this state:
31509 root      20   0  537m 534m 6852 R 100.2 61.9   6:43.00 acd_cli
where 61.9 are percents of memory and 100.2 - cpu.

root@raspberry:~/acd_cli# time acd_cli sync
Syncing...
Done.

real	32m13.456s
user	31m16.670s
sys	0m24.570s


All done :)
Thank you very much.

**Comment by yadayada** [comment]
Glad it works.
By the way, is it always this slow? Do you have a lot of files? (``acd_cli tree | wc -l``)

**Comment by airstand** [comment]
They are around 100k files and 500GB :)
root@raspberry:~# time acd_cli tree | wc -l
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.2.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 929, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 450, in tree_action
    print(node)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 49-51: ordinal not in range(128)
72680

real	1m4.940s
user	1m3.170s
sys	0m1.690s

Also , I have problems when try to download a directory that already exist on the raspberry:
root@raspberry:/backup/Pictures# acd_cli download /2011/
15-05-18 19:19:55.469 [ERROR] [acd_cli] - Error creating directory "/backup/Pictures/2011".
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.2.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 929, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 523, in download_action
    return ret_val | ql.start()
  File "/usr/local/lib/python3.2/dist-packages/acdcli/utils/threading.py", line 62, in start
    t = Thread(target=self._worker_task, args=(i,), daemon=True, name='worker-' + str(i))
TypeError: __init__() got an unexpected keyword argument 'daemon'
root@raspberry:/backup/Pictures# ls -la | grep 2011
drwxrwxrwx  48 root root         52 May 18 16:44 2011
root@raspberry:/backup/Pictures#

**Comment by airstand** [comment]
Also , I am not able to upload any file/dir

root@raspberry:/backup/backups/sauro# acd_cli upload -f sauro-www-19-May-2015.tar.gz /backups/sauro/
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.2.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 929, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 497, in upload_action
    return ret_val | ql.start()
  File "/usr/local/lib/python3.2/dist-packages/acdcli/utils/threading.py", line 58, in start
    p = Thread(target=self._print_prog, daemon=True)
TypeError: __init__() got an unexpected keyword argument 'daemon'

**Comment by yadayada** [comment]
That's the same error as before. 
https://docs.python.org/3.3/library/threading.html#thread-objects

You can a) wait a bit b) fix the source code yourself c) upgrade your Python to 3.3 or higher (if possible).

**Comment by ebouda33** [comment]
Your problem is in your sharedkey in oauth_data
make all parameter in one line
For me that corrige every thing
