### ISSUE TITLE
[Errno 5] Input/output error

### ISSUE THREAD

**Issue by zenjabba** [yadayada/acd_cli#354]
Seems to happen **:**:39 every 2 mins... any thoughts?

```
16-06-26 23:30:39.628 [ERROR] [acd_cli] - Traceback (most recent call last):
  File "/usr/local/bin/acd_cli.py", line 192, in autosync
    try:
  File "/usr/local/bin/acd_cli.py", line 123, in sync_node_list
    CHECKPOINT_KEY = 'checkpoint'
OSError: [Errno 5] Input/output error
16-06-26 23:32:39.729 [ERROR] [acd_cli] - Traceback (most recent call last):
  File "/usr/local/bin/acd_cli.py", line 192, in autosync
    try:
  File "/usr/local/bin/acd_cli.py", line 123, in sync_node_list
    CHECKPOINT_KEY = 'checkpoint'
OSError: [Errno 5] Input/output error
```

**Comment by yadayada** [comment]
That's an error when creating/writing to the temporary file into which the changesets are saved.
