### ISSUE TITLE
Can't mount on OSX

### ISSUE THREAD

**Issue by OskarPersson** [yadayada/acd_cli#355]
I'm trying to use this on OS X 10.11.5 but I'm getting the following error when mounting:

```
$ acdcli mount myacd
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1366, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 904, in mount_action
    import acdcli.acd_fuse
  File "/usr/local/lib/python3.5/site-packages/acdcli/acd_fuse.py", line 15, in <module>
    from acdcli.bundled.fuse import FUSE, FuseOSError as FuseError, Operations
  File "/usr/local/lib/python3.5/site-packages/acdcli/bundled/fuse.py", line 67, in <module>
    _libiconv = CDLL(find_library('iconv'), RTLD_GLOBAL)  # libfuse dependency
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/Oskar/lib/libiconv.dylib, 10): no suitable image found.  Did find:
	/Users/Oskar/lib/libiconv.dylib: mach-o, but wrong architecture
```

I've tried both with `sudo pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git` and `sudo pip3 install --upgrade --pre acdcli`.

Is there some dependency I'm missing?

**Comment by Zettt** [comment]
As far as I understand the [documentation](http://acd-cli.readthedocs.io/en/latest/FUSE.html), it needs a path to mount to (the same way other mount commands do). I haven't tested it, but shouldn't it be possible to mount it some of the available devices in `/dev`?

**Comment by jlarson82** [comment]
Below is a simplified version of what I use in a bash shell script to quickly mount ACD on my MacBook Air running El Capitan (using the OS X Fuse beta) (I stripped out all error checking and other aspects of the script to focus solely on a simple quick method of mounting on OS X for this response; I use a more complicated script which also unmounts the drive if it is already mounted and exits if it can't be unmounted prior to mounting):

------------Start of simplified script to mount on OS X-------------
- #!/bin/bash
- acd_mount_dir="/Volumes/amazon_cloud_drive/"
- mkdir -p "$acd_mount_dir"
- env no_proxy='*' acd_cli sync
- sleep 1
- env no_proxy='*' acd_cli -d mount -fg -i0 -ao "$acd_mount_dir"
- sleep 1
- echo "Mounted path ""$acd_mount_dir"" now contains the following root level ACD files and folders:"
- ls -1 "$acd_mount_dir"
------------End of simplified script to mount on OS X-------------

I personally also use the "-ro" option before the mount directory variable since I have not been using acd_cli to upload files and instead have only been using it to provide read access to my files across any application on the laptop.  I imagine there are cleaner ways to accomplish the same task.  This is just what I've been using lately.

**Comment by nitschkecm** [comment]
@jlarson82 regarding your script which looks very good indeed. I was trying to run it and I get "mkdir: /Volumes/Amazon/" permission denied error. I know it is overcome by running it as sudo but

Have you found a way to automatically mount the Amazon Cloud Drive at startup? Any suggestion for that ?

**Comment by jlarson82** [comment]
@nitschkecm : My attempts last year to auto-mount ACD at startup on my previous laptop were unfortunately not successful, even when I tried to utilize a third party software to launch a mounting script.  At that time, sudo privileges were still required for the mount which possibly were the problem when combined with the third party software/utility.

With respect to sudo being required for mounting, I modified some execute and/or write permissions a few months ago on my old laptop so that my user account could mount ACD into /Volumes/xyz without requiring sudo permissions.  I will let you know once I figure out which files I modified since I am just starting the transition to my new laptop and thus will need to figure this out again.  This approach to avoid sudo privileges may or may not be acceptable for your own situation depending on the security ramifications of the modifications once I re-discover what was modified.

Unfortunately, ever after upgrading to Sierra I have the perpetual root node not found issue each and every acd_cli sync so I currently can't mount ACD.  I haven't had any time lately to investigate the sync issues.  Once that issue is resolved, I will see if I can figure out a different way to mount ACD at startup.  My quick attempts yesterday to update fstab via vifs were unsuccessful in getting ACD to mount at start-up.  I didn't figure out if there were any error messages or other information of interest regarding fstab auto-mounting ACD.  Regardless, I'll let you know if I find a way to automatically mount ACD at startup on macOS Sierra.

**Comment by jlarson82** [comment]
@nitschkecm : I succeeded in getting ACD to mount at startup.  To fix my broken acd_cli installation I ended up having to remove Python 3.6.0 and instead installed Python 3.4.5 using the .pkg installer.

Below is the key steps performed on my laptop which enabled me to auto-mount ACD on macOS Sierra:

1) macOS Sierra (10.12.x) no longer allows normal users to have write privileges to /Volumes/.  Thus a different directory is needed to contain the desired mount point.

- sudo mkdir /mnt/

2) Update permissions & ownership of this new directory so that your user (replace "userid" with your own user ID in the chown command) has the necessary permissions for mounting into this folder without requiring sudo.

- sudo chmod 775 /mnt

- sudo chown userid:staff /mnt

3) [Optional] Create symbolic link to provide a shorter path to the acd_cli binary (below is what was performed for my setup with is python install path dependent):

- ln -s /Library/Frameworks/Python.framework/Versions/3.5/bin/acdcli /usr/local/bin/acd_cli

4) Using Automator, create a new "Application".  Select the action to "Run Shell Script".  Copy into it your script for mounting ACD.  Note that any calls to acd_cli require the full path so that acd_cli can be found by Automator (the below sample script uses the symbolic link to the acd_cli binary - i.e.,  /usr/local/bin/acd_cli).

------------Start of simplified Automator shell script for auto-mounting ACD-------------

- acd_mount_dir="/mnt/amazon_cloud_drive/"
- mkdir -p "$acd_mount_dir"
- env no_proxy='*' /usr/local/bin/acd_cli sync
- sleep 1
- env no_proxy='*' /usr/local/bin/acd_cli -d mount -fg -i0 -ao "$acd_mount_dir"
- sleep 1
- echo "Mounted path ""$acd_mount_dir"" now contains the following root level ACD files and folders:"
- ls -1 "$acd_mount_dir"

------------End of simplified script to auto-mount ACD on OS X-------------

5) Save this Automator application to a location accessible to your desired user account (I saved mine within the /Applications/ folder as "Amazon_Cloud_Drive_automount.app")

6) Test the Automatic application by pressing the "Run" button.  Ensure it correctly mounts ACD before proceeding to the next step.  If troubleshooting is required, use the "Results" portion of Automator to review any printed statements (e.g., echoed output) to see where the script is broken.  This is how I deduced that it couldn't find acd_cli without the hard coded path which was the only issue I encountered when migrating my script to the Automator application.

7) Using System Preferences, click on "Users & Groups".  For the desired user(s), click on the login items tab and add the newly created Automator application for mounting ACD.

**Comment by nitschkecm** [comment]
@jlarson82 
Many thanks for your time and effort to detail this. I have followed your steps and at least it a creates the directory. The script says it runs "successfully" however I do not have my Amazon Cloud Drive mounted. 

running the following command in terminal

/usr/local/bin/acd_cli mount -ao /amz/Plex/ (my mount folder is amz)

I get this 
`Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 1622, in main
    set_log_level(args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 1213, in set_log_level
    maxBytes=MAX_LOG_SIZE, backupCount=MAX_LOG_FILES)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1035, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/Users/media/Library/Caches/acd_cli/acd_cli.log'
`
If you have any suggestion I would be more than happy to try. Thanks a lot for the help!

**Comment by jlarson82** [comment]
@nitschkecm
Could you check the permissions of this file and its parent folder?  I suspect your userid doesn't have write privileges to acd_cli's log file.  You can check the permissions with something like the following:

ls -l "/Users/media/Library/Caches/acd_cli/acd_cli.log"

ls -l "/Users/media/Library/Caches/" | grep acd_cli

Hopefully I didn't have any typos or autocorrect errors since this response is via my phone.

**Comment by nitschkecm** [comment]
@jlarson82 
Sure 
the first 
`ls -l "/Users/media/Library/Caches/acd_cli/acd_cli.log"
-rw-r--r--  1 root  staff  10404411 Jan  8 19:46 /Users/media/Library/Caches/acd_cli/acd_cli.log
`

the second
`ls -l "/Users/media/Library/Caches/" | grep acd_cli
drwx------  13 media  staff     442 Jan  8 19:20 acd_cli`

**Comment by jlarson82** [comment]
The output of the log file shows it is owned by root instead of the media user.  Using sudo let's try updating the permissions and ownership of the log file to see if this is the source of the problem or not:

sudo chown media:staff "/Users/media/Library/Caches/acd_cli/acd_cli.log"

sudo chmod 664 "/Users/media/Library/Caches/acd_cli/acd_cli.log"

**Comment by nitschkecm** [comment]
@jlarson82 
Found the error the oauth_data file was not owned by the user.
I have made two tests.
1. Run it as shell script in shell
`#!/bin/bash
acd_mount_dir="/amz/Plex/"
mkdir -p "$acd_mount_dir"
#env no_proxy='*' /usr/local/bin/acd_cli sync
sleep 1
env no_proxy='*' /usr/local/bin/acd_cli -d mount -fg -i0 -ao "$acd_mount_dir"
sleep 1
echo "Mounted path ""$acd_mount_dir"" now contains the following root level ACD$
ls -1 "$acd_mount_dir"`

worked out fine (I have commented out the sync for the test). 

When I run the same in the Automator
It does mount, however it seems like the job will never finish. Could it be that there is a "special setting" I need for the automator to work.
Shell is set to /bin/bash (Ihave it only selected in the drop down box not added it again into the code like as I have it on the sh.script
Pass input to stdin
Option none selected. The job never finishes... 
Any further idea?
