### ISSUE TITLE
RequestError: 401

### ISSUE THREAD

**Issue by crack00r** [yadayada/acd_cli#365]
```
root@123:~# acd_cli sync
Getting changesTraceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1601, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 721, in sync_action
    return sync_node_list(args.full, args.to_file, args.from_file)
  File "/usr/local/bin/acd_cli.py", line 140, in sync_node_list
    file=to_file if to_file else None)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/metadata.py", line 51, in get_changes
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 401, [acd_api] no body received.
```

**Comment by scriptzteam** [comment]
https://github.com/yadayada/acd_cli/issues/328

https://github.com/yadayada/acd_cli/issues/259

https://github.com/yadayada/acd_cli/issues/147

https://github.com/yadayada/acd_cli/issues/332

**Comment by yadayada** [comment]
Sorry, there is no way for me to do anything about this. Please try the `old-sync` or save the changes to a file on another machine and import them on the one where the sync fails.
