### ISSUE TITLE
Read time out

### ISSUE THREAD

**Issue by pmwoodward3** [yadayada/acd_cli#375]
Brand new install, got oauth_data than tried to sync and this happens.

````
# acdcli --verbose sync
16-08-08 18:37:04.835 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-08-08 18:37:04.835 [INFO] [acd_cli] - TestPlugin attached.
16-08-08 18:37:04.836 [INFO] [acd_cli] - Settings path is "/root/.config/acd_cli".
16-08-08 18:37:04.839 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
16-08-08 18:37:04.840 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-08-08 18:37:04.844 [INFO] [acdcli.cache.schema] - DB schema version is 2.
Getting changes16-08-08 18:37:04.845 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "None".
16-08-08 18:37:04.846 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
16-08-08 18:37:04.855 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdws.us-east-1.amazonaws.com', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/acdcli-0.3.1-py3.5.egg/acdcli/api/common.py", line 48, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/acdcli-0.3.1-py3.5.egg/acdcli/api/backoff_req.py", line 104, in _request
    **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='cdws.us-east-1.amazonaws.com', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "/usr/local/lib/python3.5/dist-packages/acdcli-0.3.1-py3.5.egg/EGG-INFO/scripts/acd_cli.py", line 1601, in main
    ret = args.func(args)
  File "/usr/local/lib/python3.5/dist-packages/acdcli-0.3.1-py3.5.egg/EGG-INFO/scripts/acd_cli.py", line 721, in sync_action
    return sync_node_list(args.full, args.to_file, args.from_file)
  File "/usr/local/lib/python3.5/dist-packages/acdcli-0.3.1-py3.5.egg/EGG-INFO/scripts/acd_cli.py", line 140, in sync_node_list
    file=to_file if to_file else None)
  File "/usr/local/lib/python3.5/dist-packages/acdcli-0.3.1-py3.5.egg/acdcli/api/metadata.py", line 48, in get_changes
    r = self.BOReq.post(self.metadata_url + 'changes', data=json.dumps(body), stream=True)
  File "/usr/local/lib/python3.5/dist-packages/acdcli-0.3.1-py3.5.egg/acdcli/api/backoff_req.py", line 128, in post
    return self._request('POST', url, acc_codes, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/acdcli-0.3.1-py3.5.egg/acdcli/api/common.py", line 50, in decorated
    raise RequestError(RequestError.CODE.CONN_EXCEPTION, e.__str__())
acdcli.api.common.RequestError: RequestError: 1000, HTTPSConnectionPool(host='cdws.us-east-1.amazonaws.com', port=443): Read timed out. (read timeout=60)
```
`

**Comment by yadayada** [comment]
Sorry, I can't do anything about connection errors or timeouts.

**Comment by acejam** [comment]
Did you ever find a solution to this? I am consistently seeing these same timeout errors, verified on 2 different servers. `old-sync` seems to work for me, but I've never been able to get `sync` to work.

**Comment by camjac251** [comment]
I too am having this issue. Like @acejam said `acd_cli old-sync` works just fine but `acd_cli sync` does not.

Here is the log from my server
`root@server:~# acd_cli --verbose sync
16-10-04 14:22:04.697 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-10-04 14:22:04.697 [INFO] [acd_cli] - TestPlugin attached.
16-10-04 14:22:04.697 [INFO] [acd_cli] - Settings path is "/root/.config/acd_cli".
16-10-04 14:22:04.698 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
16-10-04 14:22:04.698 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-10-04 14:22:04.699 [INFO] [acdcli.cache.schema] - DB schema version is 2.
Getting changes16-10-04 14:22:04.743 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "None".
16-10-04 14:22:04.743 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
16-10-04 14:22:04.745 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1609, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 729, in sync_action
    return sync_node_list(args.full, args.to_file, args.from_file)
  File "/usr/local/bin/acd_cli.py", line 148, in sync_node_list
    file=to_file if to_file else None)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/metadata.py", line 51, in get_changes
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 504, [acd_api] no body received.

root@server:~# acd_cli --verbose old-sync
16-10-04 14:23:14.229 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-10-04 14:23:14.229 [INFO] [acd_cli] - TestPlugin attached.
16-10-04 14:23:14.229 [INFO] [acd_cli] - Settings path is "/root/.config/acd_cli".
16-10-04 14:23:14.230 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
16-10-04 14:23:14.230 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-10-04 14:23:14.231 [INFO] [acdcli.cache.schema] - DB schema version is 2.
Syncing...
16-10-04 14:23:14.349 [INFO] [acdcli.cache.schema] - Dropped all tables.
16-10-04 14:23:14.466 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-10-04 14:23:14.467 [INFO] [acdcli.api.backoff_req] - GET "https://cdws.us-east-1.amazonaws.com/drive/v1/nodes"
16-10-04 14:23:14.469 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
16-10-04 14:23:16.038 [INFO] [acdcli.cache.sync] - Inserted/updated 1 folder(s).
16-10-04 14:23:16.039 [INFO] [acdcli.cache.sync] - Parented 1 node(s).
Done.
root@server:~# `
