### ISSUE TITLE
database disk image is ...

### ISSUE THREAD

**Issue by procmail** [yadayada/acd_cli#38]
Hi,

When doing an upload, the mac crashed and now I get this error while trying to upload:

```
Traceback (most recent call last):
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./acd_cli.py", line 935, in <module>
    main()
  File "./acd_cli.py", line 920, in main
    db.init(CACHE_PATH)
  File "/Users/eric/.virtualenvs/acd_cli/acd_cli/acdcli/cache/db.py", line 251, in init
    uninitialized = not engine.has_table(Node.__tablename__)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 2056, in has_table
    return self.run_callable(self.dialect.has_table, table_name, schema)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1959, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1467, in run_callable
    return callable_(self, *args, **kwargs)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/dialects/sqlite/base.py", line 966, in has_table
    connection, "table_info", table_name, schema=schema)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1307, in _get_table_pragma
    cursor = connection.execute(statement)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
    statement, parameters
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/eric/.virtualenvs/acd_cli/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed [SQL: 'PRAGMA table_info("nodes")']
```

**Comment by procmail** [comment]
Solution: delete ~/Library/Caches/acd_cli/* and redo the oauth, then sync.
