### ISSUE TITLE
Ubuntu 16.04.1 LTS, No such file or directory when mounting

### ISSUE THREAD

**Issue by diendanyoi54** [yadayada/acd_cli#384]
Appreciate the efforts yadayada!  Recently installed Ubuntu 16.04.1 and installed everything from a sudo user.

```
sudouser:~$ acd_cli mount ~/
amazon/                    .bash_logout               .cache/                    .python_history            .sudo_as_admin_successful
.bash_history              .bashrc                    .profile                   .ssh/                      .viminfo
sudouser:~$ acd_cli mount -ao ~/amazon
fuse: failed to exec fusermount: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1366, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 909, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/acd_fuse.py", line 559, in mount
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/acdcli/bundled/fuse.py", line 416, in __init__
    raise RuntimeError(err)
RuntimeError: 1
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/usr/local/bin/acd_cli.py", line 102, in signal_handler
    sys.exit(KEYB_INTERR_RETVAL)
SystemExit: 4
sudouser:~$ ls -a
.  ..  amazon  .bash_history  .bash_logout  .bashrc  .cache  .profile  .python_history  .ssh  .sudo_as_admin_successful  .viminfo
sudouser:~$ acd_cli mount -ao amazon/
fuse: failed to exec fusermount: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1366, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 909, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/acd_fuse.py", line 559, in mount
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/acdcli/bundled/fuse.py", line 416, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```
Not exactly sure what I'm doing wrong but the output shows you that the file does exist and I am the owner.  I ran both the lsmod | grep fuse and the modprobe fuse commands and received no output.

**Comment by yadayada** [comment]
>fuse: failed to exec fusermount: No such file or directory

I suppose some fuse-related package is missing
http://packages.ubuntu.com/search?suite=quantal&arch=any&mode=filename&searchon=contents&keywords=fusermount

**Comment by diendanyoi54** [comment]
Thanks for getting back to me so quickly.  I think it was the glusterfs-client package that I needed to install.  Afterwards I adjusted the /etc/fuse.conf file to allow others and was good to go.
