### ISSUE TITLE
503 Over Quota

### ISSUE THREAD

**Issue by sbcrumb** [yadayada/acd_cli#394]
This application is temporarily over its serving quota

Anyone else getting this when trying to get a token? I was getting this on a mount so thought I needed a new token.

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1567, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 44, in __init__
    self.handler = oauth.create_handler(cache_path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 28, in create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 167, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 99, in load_oauth_data
    self.get_auth_token(reload=False)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 117, in get_auth_token
    self.refresh_auth_token()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 210, in refresh_auth_token
    'Error refreshing authentication token: %s' % response.text)
acdcli.api.common.RequestError: RequestError: 1004, Error refreshing authentication token: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>503 Over Quota</title>
<style></style>

</head>
<body text=#000000 bgcolor=#ffffff>
<table border=0 cellpadding=2 cellspacing=0 width=100%>
<tr><td bgcolor=#3366cc><font face=arial,sans-serif color=#ffffff><b>Error</b></td></tr>
<tr><td>&nbsp;</td></tr></table>
<blockquote>
<H1>Over Quota</H1>
This application is temporarily over its serving quota.  Please try again later.

<p>
</blockquote>
<table width=100% cellpadding=0 cellspacing=0><tr><td bgcolor=#3366cc><img alt="" width=1 height=4></td></tr></table>
</body></html>

**Comment by zmwangx** [comment]
What about taking a look at the issue tracker before asking "Anyone else getting this when trying to get a token?" #393

**Comment by sbcrumb** [comment]
yes my apologies. I see the issue being reported a few times. I used a work around as mentioned in
[https://github.com/yadayada/acd_cli/issues/391](url)
