### ISSUE TITLE
No module named 'acd_cli'

### ISSUE THREAD

**Issue by Cologler** [yadayada/acd_cli#395]
after upgrade to 0.3.2 by `pip`:

``` cmd
C:\Windows\System32>acd_cli
Traceback (most recent call last):
  File "c:\users\X\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\X\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\X\AppData\Local\Programs\Python\Python35\Scripts\acd_cli.exe\__main__.py", line 5, in <module>
ImportError: No module named 'acd_cli'
```

**Comment by Cologler** [comment]
In my `sys.path`, only contain these path:

``` cmd
C:\Users\X\AppData\Local\Programs\Python\Python35\python35.zip
C:\Users\X\AppData\Local\Programs\Python\Python35\DLLs
C:\Users\X\AppData\Local\Programs\Python\Python35\lib
C:\Users\X\AppData\Local\Programs\Python\Python35
C:\Users\X\AppData\Local\Programs\Python\Python35\lib\site-packages
```

**Comment by yadayada** [comment]
Did you use the PyPI installation method ``pip3 install acdcli``? On Windows 7, I get the same error when I do that (I tried to install 0.3.2 and 0.3.1).

I am not sure why that happens, but installing from the repository worked for me.
```
pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git
```

**Comment by Cologler** [comment]
Yes I did.
`acd_cli.py` is in the directory `C:\Users\X\AppData\Local\Programs\Python\Python35\Scripts`, it is not in `sys.path`.
