### ISSUE TITLE
Cannot mount cloud drive

### ISSUE THREAD

**Issue by AHaymond** [yadayada/acd_cli#396]
I had to uninstall node and npm do to another issue and now suddenly when I run `acdcli mount ~/drive` I get the following error.

```
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1574, in main
    cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
  File "/usr/local/lib/python3.5/site-packages/acdcli/cache/db.py", line 59, in __init__
    self.integrity_check(check)
  File "/usr/local/lib/python3.5/site-packages/acdcli/cache/db.py", line 124, in integrity_check
    r = c.execute('PRAGMA integrity_check;')
sqlite3.DatabaseError: file is encrypted or is not a database
```

I have checked `~/.cache` for the acd_cli folder so I could delete it as many suggest, but it is not there. Also running `acdcli clear-cache` produces the same error

**Comment by msh100** [comment]
Try deleting the database file?
