### ISSUE TITLE
Unable to mount in FreeNAS

### ISSUE THREAD

**Issue by Stesus** [yadayada/acd_cli#407]
I can't seem to figure out why I can't use fuse to mount. I always get this error. I'm using FreeNAS 9.10.1.

`root@x:/ # acdcli mount [/mnt/acd/]`
`fuse: failed to open fuse device: No such file or directory`
`Traceback (most recent call last):`
`  File "/usr/local/bin/acdcli", line 11, in <module>`
`    sys.exit(main())`
`  File "/usr/local/bin/acd_cli.py", line 1601, in main`
`    ret = args.func(args)`
`  File "/usr/local/bin/acd_cli.py", line 1088, in mount_action`
`    allow_root=args.allow_root, allow_other=args.allow_other)`
`  File "/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 716, in mount`
`    FUSE(ACDFuse(**args), path, subtype=ACDFuse.__name__, **kwargs)`
`  File "/usr/local/lib/python3.4/site-packages/fuse.py", line 480, in __init__`
`    raise RuntimeError(err)`
`RuntimeError: 1 `

**Comment by acs-ferreira** [comment]
Have you read https://acd-cli.readthedocs.io/en/latest/FUSE.html#usage ?

Try `acdcli -nl mount -ao /mnt/acd`

**Comment by Stesus** [comment]
Yes I've read. I just tried that, but it gives the same exact error.

**Comment by acs-ferreira** [comment]
Try `kldload fuse` first.

**Comment by Stesus** [comment]
I get the following error:
`kldload: can't load fuse: Operation not permitted`

**Comment by acs-ferreira** [comment]
Are you root or you run FreeNAS in a jail ?
See https://forums.freenas.org/index.php?threads/kldload-operation-not-permitted.20545/

**Comment by Stesus** [comment]
I am running it in a jail. 

I tried this fix, but nothing changed. I guess I will have to wait until FreeNAS 10?

> Probably too late but I ran into this lately and I was able to get fuse available in a jail by creating a tunable with the values as below.
>
> Variable: fuse_load
> Value: YES
> Type: loader
> Comment: something for your own reference
> Enabled: true (tick the box)
