### ISSUE TITLE
KeyError: 'metadataUrl'

### ISSUE THREAD

**Issue by amfalmeida** [yadayada/acd_cli#41]
Hi,

I'm getting the following error, could you help me?

```
15-05-20 00:40:47.269 [INFO] [acd_cli] - Plugin leaf classes: StreamPlugin, TestPlugin
15-05-20 00:40:47.269 [INFO] [acd_cli] - StreamPlugin attached.
15-05-20 00:40:47.269 [INFO] [acd_cli] - TestPlugin attached.
15-05-20 00:40:47.270 [INFO] [acdcli.api.common] - Initializing acd with path "/home/xxx/.cache/acd_cli".
15-05-20 00:40:47.271 [INFO] [acdcli.cache.db] - Initializing cache with path "/home/xxx/.cache/acd_cli".
15-05-20 00:40:47.352 [INFO] [acdcli.cache.db] - Cache considered uninitialized.
Syncing... 
15-05-20 00:40:47.695 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "None".
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.2.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 936, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 434, in sync_action
    r = sync_node_list(full=args.full)
  File "/usr/local/bin/acd_cli.py", line 115, in sync_node_list
    nodes, purged, ncp, full = metadata.get_changes(checkpoint=None if full else cp, include_purged=not full)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/metadata.py", line 47, in get_changes
    r = BackOffRequest.post(get_metadata_url() + 'changes', data=json.dumps(body), stream=True)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/common.py", line 44, in <lambda>
    get_metadata_url = lambda: endpoint_data['metadataUrl']
KeyError: 'metadataUrl'
```

**Comment by yadayada** [comment]
What's the content of your ``/home/<user>/.cache/acd_cli/endpoint_data``?

**Comment by amfalmeida** [comment]
{
    "exp_time": 1432337514.517731,
    "message": "Failed to verify access token"
}

**Comment by amfalmeida** [comment]
I remove the file /home/<user>/.cache/acd_cli/endpoint_data and now it is
working.
