### ISSUE TITLE
Sqlite database integrity check failed

### ISSUE THREAD

**Issue by kuuhakuu** [yadayada/acd_cli#412]
Out of the blue I just got a Bad Address Error on my fusemount and after trying to sync again I got this: 
```
16-09-17 13:55:23.733 [WARNING] [acdcli.cache.db] - Sqlite database integrity check failed. You may need to clear the cache if you encounter any errors.
Getting changes..
Inserting nodes.
```

When I try to unmount and mount again I get this: 
```
16-09-17 13:57:05.208 [WARNING] [acdcli.cache.db] - Sqlite database integrity check failed. You may need to clear the cache if you encounter any errors.
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/bin/acd_cli.py", line 1580, in main
    if not check_cache():
  File "/usr/local/bin/acd_cli.py", line 1220, in check_cache
    if not cache.resolve('/'):
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/query.py", line 162, in resolve
    return Node(r)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/query.py", line 78, in __init__
    self.id = row['id']
TypeError: 'NoneType' object is not subscriptable
```

I also tried reinstalling but that doesn't work either, so now I'm stuck.

**Comment by yadayada** [comment]
You need to delete the `nodes.db` file  in your cache directory.

**Comment by kuuhakuu** [comment]
thanks, this worked.
