### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by reinierkors** [yadayada/acd_cli#417]
When running:
`acd_cli upload -x 2 -r 4 --deduplicate --remove-source-files ~/main/ /Main/`
It shows the following error twice:

```
[ERROR] [acd_cli] - Traceback (most recent call last):
  File "/home/xDiglett/.local/bin/acd_cli.py", line 246, in wrapped
    ret_val = f(*args, **kwargs)
  File "/home/xDiglett/.local/bin/acd_cli.py", line 461, in upload_file
    nodes = [n for n in cache.path_format(nodes)]
  File "/home/xDiglett/.local/bin/acd_cli.py", line 461, in <listcomp>
    nodes = [n for n in cache.path_format(nodes)]
  File "/home/xDiglett/.local/lib/python3.5/site-packages/acdcli/cache/format.py", line 186, in path_format
    yield self.first_path(node.id) + node.name
  File "/home/xDiglett/.local/lib/python3.5/site-packages/acdcli/cache/query.py", line 274, in first_path
    node = Node(r)
  File "/home/xDiglett/.local/lib/python3.5/site-packages/acdcli/cache/query.py", line 78, in __init__
    self.id = row['id']
TypeError: 'NoneType' object is not subscriptable
```

The progress shows 0.0B/s 0s, and the script eventually stops. It did upload all folders, but now it just doesn't do anything.

**Comment by acs-ferreira** [comment]
Same problem/error here.
