### ISSUE TITLE
ACDCLI gives error on sync (solved on linux - not working on macos)

### ISSUE THREAD

**Issue by seb206** [yadayada/acd_cli#448]
Hello all,

I have installed acdcli on debian and I have the issue quoted... "sqlite3.DatabaseError: file is encrypted or is not a database". Removing the ~/.cache/acd_cli/nodes.db is working fine!

However, I have an issue on MacOS, I did the same setup, acd_cli was working fine, and I have the "sqlite3.DatabaseError: file is encrypted or is not a database" while syncing. Unfortunately, I'm not able to find where is located the nodes.db database !
"locate" is returning nothing, I checked /User/myuser/.cache there's no drawer....
I launch acd_cli with a sudo, and there's no root folder on mac :(
Could you please help to find the issue, the error log is the following:

Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli", line 9, in
load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 1584, in main
cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/cache/db.py", line 59, in init
self.integrity_check(check)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/cache/db.py", line 124, in integrity_check
r = c.execute('PRAGMA integrity_check;')
sqlite3.DatabaseError: file is encrypted or is not a database

**Comment by yadayada** [comment]
``acd_cli -v init`` should print the cache directory where the database file is located.

**Comment by seb206** [comment]
thanks for the help, but it's not working,
please find the output:16-10-19 19:03:48.542 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-10-19 19:03:48.543 [INFO] [acd_cli] - TestPlugin attached.
16-10-19 19:03:48.543 [INFO] [acd_cli] - Settings path is "/Users/seb206/Library/Application Support/acd_cli".
16-10-19 19:03:48.545 [INFO] [acdcli.api.client] - Initializing ACD with path "/Users/seb206/Library/Caches/acd_cli".
16-10-19 19:03:48.546 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 1584, in main
    cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/cache/db.py", line 59, in __init__
    self.integrity_check(check)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/cache/db.py", line 124, in integrity_check
    r = c.execute('PRAGMA integrity_check;')
sqlite3.DatabaseError: file is encrypted or is not a database

**Comment by seb206** [comment]
do you know where is located the nodes.db file to erase it?
thanks

**Comment by yadayada** [comment]
```
16-10-19 19:03:48.545 [INFO] [acdcli.api.client] - Initializing ACD with path "/Users/seb206/Library/Caches/acd_cli".
```

**Comment by seb206** [comment]
thanks that's it :)
