### ISSUE TITLE
ImportError: No module named 'urlparse'

### ISSUE THREAD

**Issue by rubstew** [yadayada/acd_cli#484]
After upgrading to the last version it's crashing everything.
'Python 3.4.2'

```
acd_cli sync
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/_compat.py", line 49, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/contrib/appengine.py", line 45, in <module>
    from urlparse import urljoin
ImportError: No module named 'urlparse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/bin/acd_cli.py", line 22, in <module>
    from acdcli.api import client
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 14, in <module>
    from .content import ContentMixin
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/content.py", line 10, in <module>
    from requests_toolbelt import MultipartEncoder
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/_compat.py", line 51, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine'
```

**Comment by sapk** [comment]
Cela provient peut-être de la nouvelle version de https://pypi.python.org/pypi/requests

**Comment by chris243** [comment]
having same exact problem

**Comment by rubstew** [comment]
Great this solved the problem!! Thanks!
