### ISSUE TITLE
Get oauth file -> Internal Server Error

### ISSUE THREAD

**Issue by sneaker8650** [yadayada/acd_cli#49]
Hi, 

i guess this a Problem on the amazon API ? Everything worked fine yesterday, but now i cant sync through acd_cli nor get get a new token :
```
Internal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tensile-runway-92512/1.384480744453469618/main.py", line 84, in get
    resp = urllib.urlopen(AMAZON_OA_TOKEN_URL, urllib.urlencode(params))
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 88, in urlopen
    return opener.open(url, data)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url, data)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 433, in open_https
    errcode, errmsg, headers = h.getreply()
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/gae_override/httplib.py", line 623, in getreply
    response = self._conn.getresponse()
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/gae_override/httplib.py", line 526, in getresponse
    raise HTTPException(str(e))
HTTPException: Deadline exceeded while waiting for HTTP response from URL: https://api.amazon.com/auth/o2/token
```
Great CLI by the way, it works very well for me :)

**Comment by yadayada** [comment]
I will look into it.

**Comment by yadayada** [comment]
Seems to have been a temporary problem for a few hours. Anyway, I increased the timeout to 15s.
