### ISSUE TITLE
unknown issue when sync

### ISSUE THREAD

**Issue by NicoLeOca** [yadayada/acd_cli#490]
Hi,

I had an issue this night. several mount points disappeared after rcloning to acd.
I don't know exactly where it comes from, either Fuse, acdcli or rclone.
though when I try to sync now, I get this:

```
nicoleoca@sd-99529:~$ acdcli sync
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/bin/acd_cli.py", line 24, in <module>
    from acdcli.cache import format, db
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/db.py", line 5, in <module>
    import sqlite3
  File "/usr/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python3.5/lib-dynload/_sqlite3.cpython-35m-x86_64-linux-gnu.so: undefined symbol: sqlite3_transfer_bindings
```

Is it something you have seen before?

**Comment by yadayada** [comment]
Your Python installation is borked.

**Comment by NicoLeOca** [comment]
@yadayada 
thanks for replying quickly

usually rebooting fixes things up. but that's not a solution.
Do you have any idea on how to investigate what breaks Python?
also you labelled this issue as duplicate? did you have that from another user before? I can get in touch with him.

**Comment by yadayada** [comment]
There was an issue #322. I guess it's either related to Python or libsqlite3. Maybe @KoreanTie can help you.

**Comment by thenoahcomputer** [comment]
I had similar errors before.  Clearing ~\.cache\acd_cli folder and getting a new token fixed it for me.  

Seemed to happen whenever I wrote to ACD from elsewhere while it was mounted r/w, so I just stopped doing that.  Resorted to one r/w mount and funneled all write operations through that to prevent it.

**Comment by acs-ferreira** [comment]
Yesterday system packages had updated Python, since then, either `acdcli sync` or `acdcli cc` returns the same exact error. Ubuntu 14.04.

**Comment by NicoLeOca** [comment]
FYI, I haven't faced the initial again.
I just opened a new issue though
