### ISSUE TITLE
fuse: mount failed: No such device even when its enabled!

### ISSUE THREAD

**Issue by hnterm** [yadayada/acd_cli#497]
hi 
getting this error when i try mount 
sudo acdcli mount -ro path/to or 
mount alone or with -ao the same error
fuse: mount failed: No such device
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1679, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 1154, in mount_action
    volname=args.volname)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/acd_fuse.py", line 719, in mount
    FUSE(ACDFuse(**args), path, subtype=ACDFuse.__name__, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/fuse.py", line 480, in __init__
    raise RuntimeError(err)
RuntimeError: 1

the fuse works 100% and its openvm vps.. 
pls help!

**Comment by yadayada** [comment]
What does `cat /proc/filesystems | grep fuse ` output?

**Comment by hnterm** [comment]
nothing :|

**Comment by yadayada** [comment]
It should say something like
```
	fuseblk
nodev	fuse
nodev	fusectl
```

Maybe you need to modprobe fuse or install a missing package.

**Comment by hnterm** [comment]
well fuse module is not installed now :| , seems i need to contact the admin agian 
thanks alot!
