### ISSUE TITLE
raspian python 3.2

### ISSUE THREAD

**Issue by linuxonlinehelp** [yadayada/acd_cli#500]
On Raspian: pi2 command acd_cli sync
```
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2280, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1990, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/bin/acd_cli.py", line 22, in <module>
    from acdcli.api import client
  File "/usr/local/lib/python3.2/dist-packages/acdcli/api/client.py", line 5, in <module>
    import requests
  File "/usr/local/lib/python3.2/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/__init__.py", line 39, in <module>
    from . import idna
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/idna/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/idna/core.py", line 10
    _unicode_dots_re = re.compile(u'[\u002e\u3002\uff0e\uff61]')
                                                              ^
SyntaxError: invalid syntax
```
thanks for fix..

**Comment by yadayada** [comment]
I think the requests package dropped Python 3.2 support recently (beginning with 2.11.0?).

Please see if you can upgrade to Python 3.3 or higher, or downgrade requests to 2.10.0, or uninstall the requests version installed by pip and use your distribution's packaged pip variant.

**Comment by yadayada** [comment]
I can't check for myself, but Travis now builds on 3.2 again with the modifications I suggested.
