### ISSUE TITLE
Bug: KeyError: 'volname' when mounting on Debian

### ISSUE THREAD

**Issue by ghost** [yadayada/acd_cli#506]
Getting this on a fresh install off `master` when mounting with the following command on `Linux 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`: 
````sh
$ acdcli --verbose mount --interval 60 --allow-other --foreground --modules=subdir,subdir=/mount-this-subdir /media/mount-point
16-12-26 18:19:24.051 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-12-26 18:19:24.052 [INFO] [acd_cli] - TestPlugin attached.
16-12-26 18:19:24.052 [INFO] [acd_cli] - Settings path is "/home/user/.config/acd_cli".
16-12-26 18:19:24.055 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/user/.cache/acd_cli".
16-12-26 18:19:24.056 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-12-26 18:19:24.277 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-12-26 18:19:24.279 [INFO] [acd_cli] - Last sync at 2016-12-26 08:18:56.213960.
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1611, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 1097, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/home/user/.local/lib/python3.5/site-packages/acdcli/acd_fuse.py", line 713, in mount
    del kwargs['volname']
KeyError: 'volname'
````

Commenting out lines [712](https://github.com/yadayada/acd_cli/blob/master/acdcli/acd_fuse.py#L712) and [713](https://github.com/yadayada/acd_cli/blob/master/acdcli/acd_fuse.py#L713) avoids the issue.

**Comment by yadayada** [comment]
I suspected there was some version mismatch between acd_cli.py and acd_fuse.py. 

```
  File "/usr/local/bin/acd_cli.py", line 1097, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
```

And there it is. Maybe you have a (mismatching) system-wide installation and a user installation side by side.
