### ISSUE TITLE
sqlite error on macOS: cannot change into wal mode from within a transaction

### ISSUE THREAD

**Issue by mattmaddux** [yadayada/acd_cli#509]
I'm getting this error repeatedly on Mac OS 10.11 (El Capitan). I actually totally wiped the system after seeing the error the first time (for another reason) and figured I'd try again after the new install. I see the same thing every time, though not always on the same command. After running into the error I found the suggestion in the FAQ to use env no_proxy='*' on macOS, so I've done so, but it didn't solve the problem.

Any suggestions?

Here's my command line: 

> Media-Server:~ ******$ pip3 install --upgrade --pre acdcli
> Collecting acdcli
>   Using cached acdcli-0.3.2-py3-none-any.whl
> Requirement already up-to-date: python-dateutil in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from acdcli)
> Requirement already up-to-date: requests!=2.9.0,>=2.1.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from acdcli)
> Requirement already up-to-date: requests-toolbelt!=0.5.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from acdcli)
> Requirement already up-to-date: fusepy in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from acdcli)
> Requirement already up-to-date: appdirs in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from acdcli)
> Requirement already up-to-date: colorama in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from acdcli)
> Requirement already up-to-date: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from python-dateutil->acdcli)
> Installing collected packages: acdcli
> Successfully installed acdcli-0.3.2
> Media-Server:~ ******$ env no_proxy='*' acd_cli init
> For the one-time authentication a browser (tab) will be opened at https://tensile-runway-92512.appspot.com/.
> Please accept the request and save the plaintext response data into a file called "oauth_data" in the directory "/Users/******/Library/Caches/acd_cli".
> Press a key to open a browser.
> 
> Press a key if you have saved the "oauth_data" file into "/Users/******/Library/Caches/acd_cli".
> 
> 16-12-29 00:13:30.294 [CRITICAL] [acd_cli] - Root node not found. Please sync.
> Media-Server:~ ******$ env no_proxy='*' acd_cli sync
> Getting changes..
> Inserting nodes.
> Media-Server:~ ******$ env no_proxy='*' acd_cli -nl mount -ro /Users/******/cloud_drive
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli", line 11, in <module>
>     sys.exit(main())
>   File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 1574, in main
>     cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/cache/db.py", line 78, in __init__
>     self._execute_pragma('journal_mode', self._conf['sqlite']['journal_mode'])
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/cache/db.py", line 88, in _execute_pragma
>     c.execute('PRAGMA %s=%s;' % (key, value))
> sqlite3.OperationalError: cannot change into wal mode from within a transaction
> Media-Server:~ ******$

**Comment by mattmcdonald-uk** [comment]
I found the same issue on OS X Sierra using Python 3.6.

Installing Python 3.4 and running via that older version seems to work fine.

**Comment by mattmcdonald-uk** [comment]
Somewhat inconclusively, yes - but it's also now working for me on 3.6 without the patch (possibly because I'm running a version on 3.4 alongside)

**Comment by jlarson82** [comment]
I tested the small patch on my system and it didn't resolve the "sqlite3.OperationalError: cannot change into wal mode from within a transaction" issue on my laptop.  My OS is macOS Sierra 10.12.2 with Python 3.6.0 installed.  I have acdcli 0.3.2 installed with api 0.9.2.

**Comment by sspilleman** [comment]
@yadayada, I can also confirm the smal patch is NOT working.... Sierra 10.13.3, Python 3.6, acdcli 0.3.2, api 0.9.2.

**Comment by spaccewalker** [comment]
Exactly the same problem. It just worked again after 12 days of errors! Donno why it worked but maybe the thing amazon just gives out a certain number of nods during 12 days or something like that (I suppose it could be that)... But I really don't know. (I'm not a programmer and a also a totally newbie to working in the terminal). Sierra 10.12.2, acdcli 0.3.2, api 0.9.2.

**Comment by yadayada** [comment]
Another shot in the dark:

```diff
diff --git a/acdcli/cache/db.py b/acdcli/cache/db.py
index 35eab35..5bab3d2 100644
--- a/acdcli/cache/db.py
+++ b/acdcli/cache/db.py
@@ -84,6 +84,7 @@ class NodeCache(SchemaMixin, QueryMixin, SyncMixin, FormatterMixin):
         return self.tl._conn
 
     def _execute_pragma(self, key, value) -> str:
+        self._conn.commit()
         with cursor(self._conn) as c:
             c.execute('PRAGMA %s=%s;' % (key, value))
             r = c.fetchone()

```

**Comment by sspilleman** [comment]
Hi @yadayada . Sorry, this one doesn't work either :-(

**Comment by sspilleman** [comment]
See code below.... that seems to work when executing 

> acdcli ls

Not sure however what i'm risking/breaking just disabling the 'PRAGMA journal_mode=wal;'
```python
def _execute_pragma(self, key, value) -> str:
        """bug"""
        with cursor(self._conn) as c:
            if key is 'journal_mode':
                logger.info('PRAGMA %s=%s;' % (key, value))
            else:
                c.execute('PRAGMA %s=%s;' % (key, value))
            r = c.fetchone()
```

**Comment by yadayada** [comment]
Yes, you may just disable WAL mode.

```diff
diff --git a/acdcli/cache/db.py b/acdcli/cache/db.py
index 35eab35..194b0f7 100644
--- a/acdcli/cache/db.py
+++ b/acdcli/cache/db.py
@@ -75,7 +75,6 @@ class NodeCache(SchemaMixin, QueryMixin, SyncMixin, FormatterMixin):
             self.root_id = first_id
 
         self._execute_pragma('busy_timeout', self._conf['sqlite']['busy_timeout'])
-        self._execute_pragma('journal_mode', self._conf['sqlite']['journal_mode'])
 
     @property
     def _conn(self) -> sqlite3.Connection:
```

**Comment by RinCat** [comment]
Same error on Linux.

> sqlite3.OperationalError: cannot change into wal mode from within a transaction

**Comment by mattmaddux** [comment]
Can confirm problem is fixed by rolling back to Python 3.4.4

**Comment by yadayada** [comment]
Let's have a look at the [sqlite3 module documentation for Python 3.6](https://docs.python.org/3.6/library/sqlite3.html#controlling-transactions)...
>So if you are within a transaction and issue a command like CREATE TABLE ..., VACUUM, PRAGMA, the sqlite3 module will commit implicitly before executing that command. 

But the [What's New in Python 3.6 page](https://docs.python.org/3/whatsnew/3.6.html) states
>sqlite3 no longer implicitly commits an open transaction before DDL statements.

I'm still looking for a missing commit statement.

**Comment by yadayada** [comment]
```diff
diff --git a/acdcli/cache/db.py b/acdcli/cache/db.py
index 35eab35..aac79ed 100644
--- a/acdcli/cache/db.py
+++ b/acdcli/cache/db.py
@@ -35,7 +35,7 @@ class IntegrityError(Exception):
 
 
 def _create_conn(path: str) -> sqlite3.Connection:
-    c = sqlite3.connect(path)
+    c = sqlite3.connect(path, isolation_level='IMMEDIATE')
     c.row_factory = sqlite3.Row # allow dict-like access on rows with col name
     return c
```

I did not encounter any problems using the above patch, can anyone confirm?

**Comment by dschense** [comment]
Im still getting this error:

`acd_cli -v sync
17-01-15 10:39:09.550 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
17-01-15 10:39:09.550 [INFO] [acd_cli] - TestPlugin attached.
17-01-15 10:39:09.550 [INFO] [acd_cli] - Settings path is "/home/dschense/.config/acd_cli".
17-01-15 10:39:09.551 [INFO] [acd_cli] - Cache path is "/home/dschense/.cache/acd_cli".
17-01-15 10:39:09.553 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/dschense/.cache/acd_cli".
17-01-15 10:39:09.554 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
17-01-15 10:39:10.072 [INFO] [acdcli.cache.schema] - DB schema version is 2.
Getting changes17-01-15 10:39:10.073 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "None".
17-01-15 10:39:10.073 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.eu-west-1.amazonaws.com/drive/v1/changes"
.......
17-01-15 10:39:12.984 [INFO] [acdcli.api.metadata] - Found "reset" tag in changes.
17-01-15 10:39:13.006 [INFO] [acdcli.cache.schema] - Dropped all tables.
17-01-15 10:39:13.024 [INFO] [acdcli.cache.schema] - DB schema version is 2.
Inserting nodes17-01-15 10:39:13.144 [INFO] [acdcli.cache.sync] - Inserted/updated 184 folder(s).
17-01-15 10:39:14.047 [INFO] [acdcli.cache.sync] - Inserted/updated 1408 file(s).
17-01-15 10:39:14.069 [INFO] [acdcli.cache.sync] - Parented 1592 node(s).
.17-01-15 10:39:14.293 [INFO] [acdcli.cache.sync] - Inserted/updated 243 folder(s).
17-01-15 10:39:14.982 [INFO] [acdcli.cache.sync] - Inserted/updated 1106 file(s).
17-01-15 10:39:15.018 [INFO] [acdcli.cache.sync] - Parented 1349 node(s).
.17-01-15 10:39:15.195 [INFO] [acdcli.cache.sync] - Inserted/updated 209 folder(s).
17-01-15 10:39:15.874 [INFO] [acdcli.cache.sync] - Inserted/updated 1056 file(s).
17-01-15 10:39:15.905 [INFO] [acdcli.cache.sync] - Parented 1265 node(s).
.17-01-15 10:39:16.106 [INFO] [acdcli.cache.sync] - Inserted/updated 259 folder(s).
17-01-15 10:39:16.882 [INFO] [acdcli.cache.sync] - Inserted/updated 1288 file(s).
17-01-15 10:39:16.923 [INFO] [acdcli.cache.sync] - Parented 1547 node(s).
.17-01-15 10:39:18.338 [INFO] [acdcli.cache.sync] - Inserted/updated 2000 file(s).
17-01-15 10:39:18.365 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
.17-01-15 10:39:18.467 [INFO] [acdcli.cache.sync] - Inserted/updated 98 folder(s).
17-01-15 10:39:19.094 [INFO] [acdcli.cache.sync] - Inserted/updated 674 file(s).
17-01-15 10:39:19.139 [INFO] [acdcli.cache.sync] - Parented 772 node(s).
.17-01-15 10:39:19.147 [INFO] [acdcli.api.metadata] - 6 page(s) in changes.

17-01-15 10:39:19.150 [ERROR] [acd_cli] - Root node not found. Sync may have been incomplete.
[dschense@upload ~]$ acd_cli -v sync
17-01-15 10:39:25.467 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
17-01-15 10:39:25.467 [INFO] [acd_cli] - TestPlugin attached.
17-01-15 10:39:25.467 [INFO] [acd_cli] - Settings path is "/home/dschense/.config/acd_cli".
17-01-15 10:39:25.468 [INFO] [acd_cli] - Cache path is "/home/dschense/.cache/acd_cli".
17-01-15 10:39:25.469 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/dschense/.cache/acd_cli".
17-01-15 10:39:25.470 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
17-01-15 10:39:25.520 [INFO] [acdcli.cache.schema] - DB schema version is 2.
Traceback (most recent call last):
  File "/usr/bin/acd_cli", line 11, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/bin/acd_cli.py", line 1653, in main
    cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
  File "/usr/lib/python3.6/site-packages/acdcli/cache/db.py", line 78, in __init__
    self._execute_pragma('journal_mode', self._conf['sqlite']['journal_mode'])
  File "/usr/lib/python3.6/site-packages/acdcli/cache/db.py", line 88, in _execute_pragma
    c.execute('PRAGMA %s=%s;' % (key, value))
sqlite3.OperationalError: cannot change into wal mode from within a transaction`

**Comment by dschense** [comment]
But this probem is only on one of my machines. Iam running two identical Archlinux machines:

```
acd_cli 0.3.2, api 0.9.0
Python 3.6.0
```

one machine is working without any problems, and the other one gives me the problem above.

**Comment by ahom** [comment]
The patch with `isolation_level='IMMEDIATE'` did not work on Linux/Python3.6.
However, if I completely disable wal mode by removing the corresponding `PRAGMA` it works fine.

**Comment by yadayada** [comment]
@ahom Strange, I tested on Debian testing with a freshly compiled Python 3.6.0 and it made the intermittent wal mode change errors reliably disappear.

**Comment by juanrodgil** [comment]
The patch with `isolation_level='IMMEDIATE'` did not work on Archlinux fully updated with the AUR acd_cli package.

**Comment by ahom** [comment]
@yadayada I was using `archlinux` and the `acd_cli-git` AUR package. I rebuilt from scratch this morning with the commit you submitted and it now works fine without patches.

**Comment by juanrodgil** [comment]
@yadayada 
I changed the acd_cli to the acd_cli-git AUR package, with the last commit, and it works for me too!

**Comment by rodrigc** [comment]
Looks like this is the change in Python which changed the behavior: https://github.com/python/cpython/commit/3a96828b60afb528a5bf07e168c1b54f15df783f

**Comment by rexhunt** [comment]
I just also changes from acd_cli to acd_cli-git AUR packages which has fixed this problem for me.
