### ISSUE TITLE
Can't Sync

### ISSUE THREAD

**Issue by dany20mh** [yadayada/acd_cli#539]
I'm trying to sync but every time I get error and it won't work.

```
Danials-iMac:~ danial$ acdcli sync -f
Getting changes..........................................................
Inserting nodes.........................................................
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acdcli", line 11, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 1685, in main
    ret = args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 776, in sync_action
    ret = sync_node_list(args.full, args.to_file, args.from_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 197, in sync_node_list
    sync_owner_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 126, in sync_owner_id
    owner_id = acd_client.get_owner_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/api/metadata.py", line 254, in get_owner_id
    node = self.create_file('acd_cli_get_owner_id')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/api/content.py", line 103, in create_file
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 409, {"logref":"f9480558-022d-11e7-9322-2bd03d3b4999","message":"Node with the name acd_cli_get_owner_id already exists under parentId HoFLBzT4R1SnBiJKtu9Ytg conflicting NodeId: 51dqN24BRDyj1DHHxFftbw","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"51dqN24BRDyj1DHHxFftbw"}}
Danials-iMac:~ danial$ acdcli sync
Last sync was very recent or has invalid date. Waiting 4m 52s.
Getting changes..
Inserting nodes.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acdcli", line 11, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 1685, in main
    ret = args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 776, in sync_action
    ret = sync_node_list(args.full, args.to_file, args.from_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 197, in sync_node_list
    sync_owner_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 126, in sync_owner_id
    owner_id = acd_client.get_owner_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/api/metadata.py", line 254, in get_owner_id
    node = self.create_file('acd_cli_get_owner_id')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/api/content.py", line 103, in create_file
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 409, {"logref":"ac9d4b48-022e-11e7-9324-c119d2235820","message":"Node with the name acd_cli_get_owner_id already exists under parentId HoFLBzT4R1SnBiJKtu9Ytg conflicting NodeId: 51dqN24BRDyj1DHHxFftbw","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"51dqN24BRDyj1DHHxFftbw"}}
Danials-iMac:~ danial$ acdcli sync
Last sync was very recent or has invalid date. Waiting 4m 46s.
Getting changes..
Inserting nodes.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acdcli", line 11, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 1685, in main
    ret = args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 776, in sync_action
    ret = sync_node_list(args.full, args.to_file, args.from_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 197, in sync_node_list
    sync_owner_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 126, in sync_owner_id
    owner_id = acd_client.get_owner_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/api/metadata.py", line 254, in get_owner_id
    node = self.create_file('acd_cli_get_owner_id')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/api/content.py", line 103, in create_file
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 409, {"logref":"5f493085-022f-11e7-aa20-bd702643cf30","message":"Node with the name acd_cli_get_owner_id already exists under parentId HoFLBzT4R1SnBiJKtu9Ytg conflicting NodeId: 51dqN24BRDyj1DHHxFftbw","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"51dqN24BRDyj1DHHxFftbw"}}
Danials-iMac:~ danial$ acdcli sync
Last sync was very recent or has invalid date. Waiting 4m 56s.
Getting changes..
Inserting nodes.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acdcli", line 11, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 1685, in main
    ret = args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 776, in sync_action
    ret = sync_node_list(args.full, args.to_file, args.from_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 197, in sync_node_list
    sync_owner_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 126, in sync_owner_id
    owner_id = acd_client.get_owner_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/api/metadata.py", line 254, in get_owner_id
    node = self.create_file('acd_cli_get_owner_id')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/api/content.py", line 103, in create_file
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 409, {"logref":"126f0196-0230-11e7-ab5f-71bd16b1fe57","message":"Node with the name acd_cli_get_owner_id already exists under parentId HoFLBzT4R1SnBiJKtu9Ytg conflicting NodeId: 51dqN24BRDyj1DHHxFftbw","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"51dqN24BRDyj1DHHxFftbw"}}
Danials-iMac:~ danial$ acdcli sync
Getting changes..
Inserting nodes.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acdcli", line 11, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 1685, in main
    ret = args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 776, in sync_action
    ret = sync_node_list(args.full, args.to_file, args.from_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 197, in sync_node_list
    sync_owner_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/acd_cli.py", line 126, in sync_owner_id
    owner_id = acd_client.get_owner_id()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/api/metadata.py", line 254, in get_owner_id
    node = self.create_file('acd_cli_get_owner_id')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/acdcli/api/content.py", line 103, in create_file
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 409, {"logref":"36b31b83-0231-11e7-aea8-3f9c9ceb5428","message":"Node with the name acd_cli_get_owner_id already exists under parentId HoFLBzT4R1SnBiJKtu9Ytg conflicting NodeId: 51dqN24BRDyj1DHHxFftbw","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"51dqN24BRDyj1DHHxFftbw"}}
Danials-iMac:~ danial$ 
```

**Comment by madmanali93** [comment]
Have you tried clearing cache before syncing?

**Comment by bgemmill** [comment]
If that doesn't work, try manually deleting the node mentioned in the 409 error, node_id: `51dqN24BRDyj1DHHxFftbw`

Sync attempts to find the owner id of acdcli by creating a node at a known location and inspecting it. It looks like sync got itself into a funny state where that node exists but your cache doesn't have it.

**Comment by dany20mh** [comment]
I finally get to sync it again.
