### ISSUE TITLE
Error when mounting

### ISSUE THREAD

**Issue by joemarshalljm** [yadayada/acd_cli#541]
After trying to use the re-mount script, I now get this error when trying to mount:

```
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1555, in main
    set_log_level(args)
  File "/usr/local/bin/acd_cli.py", line 1153, in set_log_level
    maxBytes=MAX_LOG_SIZE, backupCount=MAX_LOG_FILES)
  File "/usr/lib/python3.4/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.4/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.4/logging/__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.4/logging/__init__.py", line 1035, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/lib/plexmediaserver/.cache/acd_cli/acd_cli.log'
```

**Comment by madmanali93** [comment]
`PermissionError: [Errno 13] Permission denied: '/var/lib/plexmediaserver/.cache/acd_cli/acd_cli.log'`

What are the permission of the folder?

**Comment by yadayada** [comment]
You should check the permissions in that folder or set the `ACD_CLI_CACHE_PATH` (see the documentation).
