### ISSUE TITLE
[acd_api] no body received (on sync, upload, everything really)

### ISSUE THREAD

**Issue by MrColdbird** [yadayada/acd_cli#544]
[amazon@Antergos ~]$ acd_cli sync
Getting changesTraceback (most recent call last):
  File "/usr/bin/acd_cli", line 11, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/bin/acd_cli.py", line 1685, in main
    ret = args.func(args)
  File "/usr/bin/acd_cli.py", line 776, in sync_action
    ret = sync_node_list(args.full, args.to_file, args.from_file)
  File "/usr/bin/acd_cli.py", line 149, in sync_node_list
    file=to_file if to_file else None)
  File "/usr/lib/python3.6/site-packages/acdcli/api/metadata.py", line 51, in get_changes
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 401, [acd_api] no body received.

Started happening in the middle of last night while uploading, and persisting throughout the whole day now.

Also finding a bunch of expired token errors in the upload logs of last night.

**Comment by MrColdbird** [comment]
I'm starting to think those are actual amazon drive server issues, as now, 10 hours after the incident, things are back to normal.

Closing the issue for now because of this.
