### ISSUE TITLE
403 on https://acd-cli-oa-backup.appspot.com/ and https://tensile-runway-92512.appspot.com/

### ISSUE THREAD

**Issue by GeorgLippold** [yadayada/acd_cli#557]
Hi,

Firstly, thanks for creating acd_cli, I use it often.

I'm currently getting errors when trying to do an acd_cli sync and acd_cli init.

It seems that

https://tensile-runway-92512.appspot.com/

and

https://acd-cli-oa-backup.appspot.com/

do not have world-read permissions. See attached screenshots.

![screen shot 2017-05-12 at 11 34 06 pm](https://cloud.githubusercontent.com/assets/7425172/26000331/d77999c0-376b-11e7-9205-1bad270be16b.png)
![screen shot 2017-05-12 at 11 34 27 pm](https://cloud.githubusercontent.com/assets/7425172/26000333/d7d0e306-376b-11e7-80ba-143dfc786037.png)

Not sure if this is intentional, but it breaks acd_cli as follows for me:

```
acd_cli sync
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 11, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1646, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/usr/local/lib/python3.6/site-packages/acdcli/api/client.py", line 43, in __init__
    self.handler = oauth.create_handler(cache_path)
  File "/usr/local/lib/python3.6/site-packages/acdcli/api/oauth.py", line 28, in create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.6/site-packages/acdcli/api/oauth.py", line 168, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.6/site-packages/acdcli/api/oauth.py", line 99, in load_oauth_data
    self.get_auth_token(reload=False)
  File "/usr/local/lib/python3.6/site-packages/acdcli/api/oauth.py", line 117, in get_auth_token
    self.refresh_auth_token()
  File "/usr/local/lib/python3.6/site-packages/acdcli/api/oauth.py", line 211, in refresh_auth_token
    'Error refreshing authentication token: %s' % response.text)
acdcli.api.common.RequestError: RequestError: 1004, Error refreshing authentication token: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/</code> from this server.  <ins>That’s all we know.</ins>
```

I tried the fixes in issue #47 (the patch to oauth.py) but that doesn't work either.

**Comment by GeorgLippold** [comment]
Seems to work again. Not sure what caused this

**Comment by hongkongkiwi** [comment]
Still an issue here :-(

**Comment by yadayada** [comment]
@hongkongkiwi I had to take these apps down (see #549). You need to upgrade to the latest GitHub commit. [The PyPI version is not working, currently.]
