### ISSUE TITLE
Error getting account quota data.

### ISSUE THREAD

**Issue by willbeeching** [yadayada/acd_cli#560]
Hi there,

Recently when mounting my ACD I'm now getting this error:

`17-05-14 02:18:49.123 [WARNING] [acdcli.acd_fuse] - Error getting account quota data. Cannot determine total and available disk space.
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1680, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 1155, in mount_action
    volname=args.volname)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/acd_fuse.py", line 719, in mount
    FUSE(ACDFuse(**args), path, subtype=ACDFuse.__name__, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/fuse.py", line 480, in __init__
    raise RuntimeError(err)
RuntimeError: 1`

None of my settings have changed, so any help would really be appreciated!

**Comment by yadayada** [comment]
I think acd_cli may have hit its rate limits, see #416.

**Comment by Christoph-D** [comment]
The workaround from #416 does not work for me because [amazon has stopped giving out invites for the drive API](https://forums.developer.amazon.com/questions/62280/how-to-get-invited-for-amazon-drive-development.html).

**Comment by Keeperjoey** [comment]
When you go to https://tensile-runway-92512.appspot.com/ you get 
Error
 
Over Quota

This application is temporarily over its serving quota. Please try again later. You can't auth anymore.
