### ISSUE TITLE
Refreshing authentication token - Unauthorized

### ISSUE THREAD

**Issue by erse80** [yadayada/acd_cli#561]
hi 

i have this error any suggestion?

it stop working after year of usage

17-05-14 14:08:03.384 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
17-05-14 14:08:03.384 [INFO] [acd_cli] - TestPlugin attached.
17-05-14 14:08:03.384 [INFO] [acd_cli] - Settings path is "/root/.config/acd_cli".
17-05-14 14:08:03.384 [INFO] [acd_cli] - Cache path is "/root/.cache/acd_cli".
17-05-14 14:08:03.386 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
17-05-14 14:08:03.386 [INFO] [acdcli.api.oauth] - Token expired at 2017-05-14 11:33:55.998284.
17-05-14 14:08:03.386 [INFO] [acdcli.api.oauth] - Refreshing authentication token.
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 11, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1646, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/client.py", line 43, in __init__
    self.handler = oauth.create_handler(cache_path)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/oauth.py", line 28, in create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/oauth.py", line 167, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/oauth.py", line 99, in load_oauth_data
    self.get_auth_token(reload=False)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/oauth.py", line 117, in get_auth_token
    self.refresh_auth_token()
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/oauth.py", line 210, in refresh_auth_token
    'Error refreshing authentication token: %s' % response.text)
acdcli.api.common.RequestError: RequestError: 1004, Error refreshing authentication token: {
    "error": "HTTP Error 401: Unauthorized",

**Comment by cpare** [comment]
**_Please read the other posts before starting a new thread._**
It appears Amazon has temporally disabled acd_cli due to defect #549 - This is impacting all users while Amazon investigates with yadayada.  Watch this thread, or #559 for updates.

**Comment by erse80** [comment]
Sorry, you're right
