### ISSUE TITLE
I have error: RequestError: 1004, Error refreshing authentication token

### ISSUE THREAD

**Issue by dcroid** [yadayada/acd_cli#565]
# acd_cli -v init
17-05-25 15:39:53.828 [INFO] [acd_cli] - Plugin leaf classes: TermsOfUsePlugin, TestPlugin, DebugPlugin
17-05-25 15:39:53.829 [INFO] [acd_cli] - TermsOfUsePlugin attached.
17-05-25 15:39:53.829 [INFO] [acd_cli] - TestPlugin attached.
17-05-25 15:39:53.829 [INFO] [acd_cli] - DebugPlugin attached.
17-05-25 15:39:53.829 [INFO] [acd_cli] - Settings path is "/root/.config/acd_cli".
17-05-25 15:39:53.832 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
17-05-25 15:39:53.832 [INFO] [acdcli.api.oauth] - Token expired at 2017-05-14 12:18:08.485725.
17-05-25 15:39:53.833 [INFO] [acdcli.api.oauth] - Refreshing authentication token.
Traceback (most recent call last):
  File "/usr/bin/acd_cli", line 11, in <module>
    sys.exit(main())
  File "/usr/bin/acd_cli.py", line 1567, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/usr/lib/python3.4/site-packages/acdcli/api/client.py", line 44, in __init__
    self.handler = oauth.create_handler(cache_path)
  File "/usr/lib/python3.4/site-packages/acdcli/api/oauth.py", line 28, in create_handler
    return AppspotOAuthHandler(path)
  File "/usr/lib/python3.4/site-packages/acdcli/api/oauth.py", line 167, in __init__
    self.load_oauth_data()
  File "/usr/lib/python3.4/site-packages/acdcli/api/oauth.py", line 99, in load_oauth_data
    self.get_auth_token(reload=False)
  File "/usr/lib/python3.4/site-packages/acdcli/api/oauth.py", line 117, in get_auth_token
    self.refresh_auth_token()
  File "/usr/lib/python3.4/site-packages/acdcli/api/oauth.py", line 210, in refresh_auth_token
    'Error refreshing authentication token: %s' % response.text)
acdcli.api.common.RequestError: RequestError: 1004, Error refreshing authentication token: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Page not found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL was not found on this server.  <ins>That’s all we know.</ins>

**Comment by tintop2k** [comment]
Did you delete your existing oauth_data file and generate a new one from the new appspot site? The error above suggests not as it shows this "Token expired at 2017-05-14"

**Comment by misant** [comment]
I did that, but expiration time is 3600 seconds. How I can increase it? 
> Did you delete your existing oauth_data file and generate a new one from the new appspot site? The error above suggests not as it shows this "Token expired at 2017-05-14"

**Comment by beam** [comment]
It can't bee increased, you have to refresh token every hour.
BUT you are using old token server, you have to reinstall acd_cli from GH, change URL manualy or wait for new release.

**Comment by dcroid** [comment]
May be I clear config file. How can I Create a new file?

**Comment by misant** [comment]
Ok, any chance to automate that? I has no sense if i need to refresh token manually every hour
> It can't bee increased, you have to refresh token every hour.

**Comment by yadayada** [comment]
@dcroid, @misant  Please update to the latest commit on GitHub.

**Comment by beam** [comment]
acd_cli refreshing expired tokens automaticly, but you are using old version.
Just wait for new release or use version from git.

**Comment by misant** [comment]
thank you, it helped

**Comment by dcroid** [comment]
I Upgrade from git.
But site show me after enter sms code 
> Error: access_denied
> Description: User not authenticated
