### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by triwing** [yadayada/acd_cli#568]
Hello guys,

after updating the acd_cli with the way explained here: https://github.com/yadayada/acd_cli/issues/564
My first sync and mount went fine, but after uploading a few 100gigs, I get this message. Connecting to the EU acd if that matters.
I now get the following error:

```
acd_cli sync
17-05-29 11:03:40.115 [CRITICAL] [acdcli.api.oauth] - Error refreshing authentication token.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 203, in refresh_auth_token
    response = requests.post(self.APPSPOT_URL, data=ref)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 523, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1646, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 43, in __init__
    self.handler = oauth.create_handler(cache_path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 28, in create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 167, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 99, in load_oauth_data
    self.get_auth_token(reload=False)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 117, in get_auth_token
    self.refresh_auth_token()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/oauth.py", line 206, in refresh_auth_token
    raise RequestError(RequestError.CODE.CONN_EXCEPTION, e.__str__())
acdcli.api.common.RequestError: RequestError: 1000, [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

**Comment by pink-mist** [comment]
A friend of mine had this exact same problem, and after some troubleshooting we determined that his SSL libraries and/or certificates were out of date. He updated them, and since then has not had a problem at all.

**Comment by triwing** [comment]
Thanks pink-mist!
So apperently my libssl-dev wasn't up2date...
