### ISSUE TITLE
404 when running acd_cli init (or sync or mount) with 'simple' authentication

### ISSUE THREAD

**Issue by SpoonMeiser** [yadayada/acd_cli#576]
I get the following output:

```
Traceback (most recent call last):
  File "/home/oj/.virtualenvs/acd/bin/acd_cli", line 11, in <module>
    sys.exit(main())
  File "/home/oj/.virtualenvs/acd/bin/acd_cli.py", line 1567, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/home/oj/.virtualenvs/acd/lib/python3.5/site-packages/acdcli/api/client.py", line 44, in __init__
    self.handler = oauth.create_handler(cache_path)
  File "/home/oj/.virtualenvs/acd/lib/python3.5/site-packages/acdcli/api/oauth.py", line 28, in create_handler
    return AppspotOAuthHandler(path)
  File "/home/oj/.virtualenvs/acd/lib/python3.5/site-packages/acdcli/api/oauth.py", line 167, in __init__
    self.load_oauth_data()
  File "/home/oj/.virtualenvs/acd/lib/python3.5/site-packages/acdcli/api/oauth.py", line 99, in load_oauth_data
    self.get_auth_token(reload=False)
  File "/home/oj/.virtualenvs/acd/lib/python3.5/site-packages/acdcli/api/oauth.py", line 117, in get_auth_token
    self.refresh_auth_token()
  File "/home/oj/.virtualenvs/acd/lib/python3.5/site-packages/acdcli/api/oauth.py", line 210, in refresh_auth_token
    'Error refreshing authentication token: %s' % response.text)
acdcli.api.common.RequestError: RequestError: 1004, Error refreshing authentication token: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Page not found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL was not found on this server.  <ins>That’s all we know.</ins>
```

And visiting the appspot page directly I see the same.

**Comment by yadayada** [comment]
I'm afraid acd_cli will no longer work for you (if you don't happen to have created a whitelisted security profile).

**Comment by vinhdizzo** [comment]
Hi, I too am getting this error.  How do I go about fixing it?  Thank you.

**Comment by pink-mist** [comment]
Unfortunately if you don't have a whitelisted security profile already there is simply no way to fix this. And there is also no way to get a new security profile whitelisted. The only way you can make use of acd_cli is with an already whitelisted one.

**Comment by vinhdizzo** [comment]
Thanks @pink-mist for your response.

Odd, don't recall anything about whitelisting any profiles when I first  set this up. Wish I did it earlier so I could continue to leverage acdcli...

**Comment by tigerjack** [comment]
Not sure if it's related to this, but I'm trying to install and use acd_cli and when I launched acd_cli -v init for the first time, the given appspot url returned a 404.

**Comment by Jomenvisst** [comment]
Got the same problem as @tigerjack. After running `acd_cli -v init` and clicking a button to open the browser, I get a 404 message.

**Comment by hsch0** [comment]
@yadayada I set up the adc_cli last year but deleted all the configuration. Does it mean I have a whitelisted security profile. if yes, how do I find it?

**Comment by vinhdizzo** [comment]
Following up on my 404 message.  Tried to create a security profile now, but can't get it whitelisted because the API is now closed to new developers...bummer.
