### ISSUE TITLE
 SyntaxError: invalid syntax in setup.py

### ISSUE THREAD

**Issue by lakefire** [yadayada/acd_cli#63]
I am getting the following error when trying to install. I am on a Mac running Yosemite. I have tried upgrading pip and Setuptools. I am not familiar with python at all so I don't know if this is a problem with your code or my setup.

Collecting git+https://github.com/yadayada/acd_cli.git
  Cloning https://github.com/yadayada/acd_cli.git to /tmp/pip-vcuO2q-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-vcuO2q-build/setup.py", line 7
        def read(fname: str) -> str:
                      ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-vcuO2q-build

**Comment by lakefire** [comment]
I kept looking around and found out how to install python3 on a Mac. That fixed the issue for me.
