### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by Cleverbum** [yadayada/acd_cli#73]
Please forgive any stupid mistakes, I'm new to GIT.

I've followed the install instructions to install and run pip3 on ubuntu to get:
```
$pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 61, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'
```

**Comment by yadayada** [comment]
I think this occurs because the distribution's pip3 upgrades the requests package to a version that it no longer is compatible with.

Try
```
apt-get remove python3-pip
easy_install3 pip
```
