### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded while getting the str of an object

### ISSUE THREAD

**Issue by alamers** [yadayada/acd_cli#82]
While uploading a time machine backup, I get the following traceback. (Could have something to do with hard links?)

```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a2', 'console_scripts', 'acdcli')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 1083, in main
    sys.exit(args.func(args))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 559, in upload_action
    args.deduplicate, excl_re, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 198, in create_upload_jobs
    return traverse_ul_dir(path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 251, in traverse_ul_dir
    ret_val |= create_upload_jobs(full_path, curr_node.id, overwr, force, dedup, exclude, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 198, in create_upload_jobs
    return traverse_ul_dir(path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 251, in traverse_ul_dir
    ret_val |= create_upload_jobs(full_path, curr_node.id, overwr, force, dedup, exclude, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 198, in create_upload_jobs
    return traverse_ul_dir(path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 251, in traverse_ul_dir
    ret_val |= create_upload_jobs(full_path, curr_node.id, overwr, force, dedup, exclude, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 198, in create_upload_jobs
    return traverse_ul_dir(path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 251, in traverse_ul_dir
    ret_val |= create_upload_jobs(full_path, curr_node.id, overwr, force, dedup, exclude, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 198, in create_upload_jobs
    return traverse_ul_dir(path, parent_id, overwr, force, dedup, exclude, jobs)
...
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 251, in traverse_ul_dir
    ret_val |= create_upload_jobs(full_path, curr_node.id, overwr, force, dedup, exclude, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 198, in create_upload_jobs
    return traverse_ul_dir(path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 227, in traverse_ul_dir
    logger.info('Created folder "%s"' % (parent.full_path() + short_nm))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/cache/db.py", line 213, in full_path
    return self.parents[0].full_path() + self.simple_name()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/cache/db.py", line 213, in full_path
    return self.parents[0].full_path() + self.simple_name()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/cache/db.py", line 213, in full_path
    return self.parents[0].full_path() + self.simple_name()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/cache/db.py", line 213, in full_path
    return self.parents[0].full_path() + self.simple_name()
[...]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/cache/db.py", line 213, in full_path
    return self.parents[0].full_path() + self.simple_name()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/cache/db.py", line 213, in full_path
    return self.parents[0].full_path() + self.simple_name()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/acdcli/cache/db.py", line 211, in full_path
    if len(self.parents) == 0:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
    value = self.callable_(state, passive)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 528, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 598, in _emit_lazyload
    result = q.all()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2399, in all
    return list(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1003, in _execute_clauseelement
    inline=len(distilled_params) > 1)
  File "<string>", line 1, in <lambda>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 500, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 392, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 190, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 213, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 1526, in visit_select
    nested_join_translation=True, **kwargs
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 1605, in visit_select
    text, select, inner_columns, froms, byfrom, kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 1702, in _compose_select_body
    t = select._whereclause._compiler_dispatch(self, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 745, in visit_clauselist
    for c in clauselist.clauses)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 742, in <genexpr>
    s for s in
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 745, in <genexpr>
    for c in clauselist.clauses)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 921, in visit_binary
    return self._generate_generic_binary(binary, opstring, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 937, in _generate_generic_binary
    opstring + \
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 1067, in visit_bindparam
    name = self._truncate_bindparam(bindparam)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 1123, in _truncate_bindparam
    bind_name = self._truncated_identifier("bindparam", bind_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 1134, in _truncated_identifier
    anonname = name.apply_map(self.anon_map)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 3610, in apply_map
    return self % map_
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/util/_collections.py", line 728, in __missing__
    self[key] = val = self.creator(key)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 1153, in _process_anon
    return derived + "_" + str(anonymous_counter)
RuntimeError: maximum recursion depth exceeded while getting the str of an object
```

**Comment by yadayada** [comment]
I think there is an infinite loop in your local folder structure.

**Comment by alamers** [comment]
Hm, yes could be... This is a time machine backup I'm trying to store on ACD. I guess ACD doesn't support replicating the hard links any way. I guess I'll have to take the route as described in feature #75. 
Thanks.

**Comment by yadayada** [comment]
Could you please check if there's actually a loop in the folder structure that was created while traversing the backup directory? E.g. ``acd_cli ls -r /`` should fail with the same error...

**Comment by alamers** [comment]
Hi,

I just did but that crashed with a different error:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a2', 'console_scripts', 'acdcli')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 1083, in main
    sys.exit(args.func(args))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/acd_cli.py", line 682, in children_action
    print(entry)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0301' in position 173: ordinal not in range(128)

I actually don't think that this will reproduce the same error anyway, I'd assume the infinite loop is local only. Doesn't `acd_cli ls -r /` list remotely, there the infinite loop probably is not replicated.

**Comment by alamers** [comment]
Just to confirm: there **is** an infinite loop in my (local) backup:

...
[1RvkdlllSPmdJaieP8L0zg] [A] Backups/201507051822/Backup/Backups.backupdb/Arjan's Laptop/2014-03-08-163547/Macintosh HD/Applications/Adium.app/Contents/Frameworks/libjson-glib.framework/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/Headers/
...

**Comment by yadayada** [comment]
I will add cycle detection to the next commit.

**Comment by alamers** [comment]
Ok, cool! Many thanks :)
