### ISSUE TITLE
Unable to upload encfs created files and folders

### ISSUE THREAD

**Issue by ShapeShifter499** [yadayada/acd_cli#93]
So I created a encfs mounted folder and attempted to upload the encrypted files and folders, the following errors is what I got. Any ideas on this?

```
[lance@Arch-Chromebook 0afd4383-73bb-4234-bba0-f69b261248c3]$ acdcli -v upload /mnt/encfs/ /
15-07-22 01:48:35.815 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-07-22 01:48:35.816 [INFO] [acd_cli] - TestPlugin attached.
15-07-22 01:48:35.816 [INFO] [acdcli.api.common] - Initializing acd with path "/home/lance/.cache/acd_cli".
15-07-22 01:48:35.817 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
15-07-22 01:48:35.817 [INFO] [acdcli.cache.db] - Initializing cache with path "/home/lance/.cache/acd_cli".
15-07-22 01:48:36.053 [INFO] [acdcli.cache.db] - Cache not considered uninitialized.
15-07-22 01:48:36.058 [INFO] [acdcli.cache.db] - DB schema version is 1.
15-07-22 01:48:36.078 [INFO] [acd_cli] - Last sync at 2015-07-22 08:48:22.631740.
15-07-22 01:48:36.085 [INFO] [acd_cli] - Resolved "/" to "-82W8y5uT5-UkmRMen0xvg"
15-07-22 01:48:45.764 [ERROR] [acd_cli] - Path "/mnt/encfs/HjauMln-4pA/Dj8G-DoeVdlOM,q4pzh4uW5/CNHSQGxkeot4/a,cVUHLZ0-Ipp4gI1wJ4K8mz/VZEbTfKl" is not accessible.
15-07-22 01:48:57.194 [INFO] [acdcli.api.common] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/nodes"
15-07-22 01:48:57.204 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
15-07-22 01:48:57.817 [INFO] [acd_cli] - Created folder "/encfs/HjauMln-4pA/ifVeBRH2N,/soAOxCdV22hV/ExgxtuzA7QYVUMqxTBpwNwctBMZm"
15-07-22 01:48:58.010 [INFO] [acdcli.cache.sync] - Inserted/updated 1 folders.
15-07-22 01:48:58.140 [INFO] [acdcli.cache.sync] - Parented 1 nodes.
15-07-22 01:49:08.091 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/0KBEie5/Tu1dny,nrA,/OsusfweGTI4/uIpZqD0fADKh3p,JSM4" is not accessible.
15-07-22 01:49:09.281 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/0Aka76tDhmGd0d7" is not accessible.
15-07-22 01:49:09.521 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/,ET5BTNvj9dRzrSWFK,NSgOQzRgwfcth/CmxY9Tq529QQ-fdynWJnSOyEj0" is not accessible.
15-07-22 01:49:09.523 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/7CPO1UShpUVdVWEKX3RhkBms-izkx-IdC2uUeU6IeR,yiMSAVdR40CAcr17" is not accessible.
15-07-22 01:49:09.524 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/9ZqJS4MEOUJ,0WPVx7CXQnuOsKIstdv2" is not accessible.
15-07-22 01:49:09.530 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/Hx0ncox4BfOH-PzVBNbsdb9VgxIWW1/8dgH2igqyaima4nwNl3rz1xJc7hpaDxALELk" is not accessible.
15-07-22 01:49:09.531 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/LjuRyYlRgxupJguvZmPEd-Gv,E0RjeI8YOUImTANTD5SULXd" is not accessible.
15-07-22 01:49:09.532 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/N5kz0cSYKCKkxH5TBjm7DsBWzBTMIwgkRnH0rPKYROAvAAg7C6SA-D-JBp7" is not accessible.
15-07-22 01:49:09.535 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SaZRn7ZXWQRgK4vjxmjO7foWe-T77YX8xLF1bmGvyPMvTfv9u494RiZHCyYR" is not accessible.
15-07-22 01:49:09.542 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/74JWSY3HAMDNHoO8e3ZfXbqJv7PFF-" is not accessible.
15-07-22 01:49:09.543 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/A92n3NNIuhmIwCQNErTFIEuPBInef-" is not accessible.
15-07-22 01:49:09.545 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/AOJS3jrpTQNa6-q6-M,tHreJxKxQNdog" is not accessible.
15-07-22 01:49:09.546 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/CV7iAMPdVBZohUxfIZRtQKfS" is not accessible.
15-07-22 01:49:09.547 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/U-Zl0nV3Ow2u6-PZro6" is not accessible.
15-07-22 01:49:09.548 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/X52j7DopGUhxV3fOe6,zRmVs" is not accessible.
15-07-22 01:49:09.553 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/gGMaLeXM1lH3v2-c1XswX," is not accessible.
15-07-22 01:49:09.554 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/mCtIW61wPCtVvISZ7RV4Sm0S" is not accessible.
15-07-22 01:49:09.556 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/oZuWpQVCPvEGkfNXbr1" is not accessible.
15-07-22 01:49:09.558 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/qb3WKx6NX7l12QNWDTBJPTV7-," is not accessible.
15-07-22 01:49:09.559 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/sb3TrYUs,P9ZOv0" is not accessible.
15-07-22 01:49:09.560 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/sh5maX4i3IU34rSiy1lj1IsN" is not accessible.
15-07-22 01:49:09.561 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/vSlTquMTthLBzRR6BbqRP1" is not accessible.
15-07-22 01:49:09.562 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/xBzi-CWXdIxPdKUw4O,AWPL2J1" is not accessible.
15-07-22 01:49:09.564 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/yd3hm7hzqF-VrIgbkfJj8z0Q" is not accessible.
15-07-22 01:49:09.565 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/SgZz7Yw0k4lfs-o1,bDnw1Her7Vo4nEw11/zAIXxrSPQIuBvLZDdLqeP7qveYNRH-" is not accessible.
15-07-22 01:49:09.572 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/c80YNJig2MMJOQJpD1zRBL1K3oo6lWx3/8pWv9PsUWCvMtGy7JBw4KtmC1Cik" is not accessible.
15-07-22 01:49:09.578 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/rb5,PdtCOjoIUHmxUprR15aYqs9170/jEi,XPgENu-FLJnNEz95MCGlnPQt" is not accessible.
15-07-22 01:49:09.580 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/rb5,PdtCOjoIUHmxUprR15aYqs9170/vFHC0zxmaVKeUA3Fd0" is not accessible.
15-07-22 01:49:09.587 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/tnxwbQIlR9vYXolBriEKA,TDjN57j-/5j-qvArQjw9bbAZY11," is not accessible.
15-07-22 01:49:09.593 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/7djoZW-pRADQ/JUS-dsz5489/yBPCfzXpIBEDxdfd0F0Mi8etXUA/cr-ZM8Mo4opfVxYUvfNYERDf6D9" is not accessible.
15-07-22 01:49:10.111 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/M4tU4GCY" is not accessible.
15-07-22 01:49:10.214 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/TY88NsdM/y5LjY38c0j2y/AuzemlEOM4vPs,nkOa-Au8YAnXUmJAY-" is not accessible.
15-07-22 01:49:10.215 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/TY88NsdM/y5LjY38c0j2y/IwIewTyhD7LnJmQHjg9V9VRjrxdBx4oy51" is not accessible.
15-07-22 01:49:10.326 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/0N9dG7NM-1HYd8HoTxqQmKo8CUKB7HulOrZE" is not accessible.
15-07-22 01:49:10.327 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/0aCrApdcepdl9Nwq8MLtsHweu1" is not accessible.
15-07-22 01:49:10.329 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/6oTyMDcmo7aeN7r,ONdmFgx6w1" is not accessible.
15-07-22 01:49:10.330 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/DFzwdkX4anT0XAZsnCM9nBYSH," is not accessible.
15-07-22 01:49:10.331 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/Gwf3DlCjv7peQPZP7K0yxtA" is not accessible.
15-07-22 01:49:10.333 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/JuQjxyvrEtAWqD0uROQT" is not accessible.
15-07-22 01:49:10.334 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/LsUW8fH7I0JnZrqleTLeryxOcgfNIH2" is not accessible.
15-07-22 01:49:10.335 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/PJGZ3YoK9b,IrmmAaaJaa7Ag7CXfgTx-ArmWB1" is not accessible.
15-07-22 01:49:10.336 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/PdQZTjM3-zE1JbDVtrTNi5M," is not accessible.
15-07-22 01:49:10.339 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/YJza5HIyHeo7ugJlqT0" is not accessible.
15-07-22 01:49:10.340 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/bPCa9egzh8VcY5qMMZPU" is not accessible.
15-07-22 01:49:10.342 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/mYIaxufecKTq4BPZcNzxkXl6" is not accessible.
15-07-22 01:49:10.343 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/o0uIXfA0EUwJXnbg3a8J" is not accessible.
15-07-22 01:49:10.345 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/s0RqGlD6T0cK8rffflzDI9dQ9xWj" is not accessible.
15-07-22 01:49:10.347 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/bLboxaXYl1/5endFVVM4J6/ytEdN0kYp8ZifT8Nm9qEt7W4tQ5-MpnX" is not accessible.
15-07-22 01:49:10.375 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/byDdK8XHctpFq,Wi" is not accessible.
15-07-22 01:49:10.608 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/hr0sezgL2zujQ0/KCVJUfL6Onogd0" is not accessible.
15-07-22 01:49:10.630 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/j-aDI3vaOn27TxAS" is not accessible.
15-07-22 01:49:11.048 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/qwgFtt8Vg69/aUhFIU5" is not accessible.
15-07-22 01:49:11.049 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/qwgFtt8Vg69/eBYiJiUQy0Njc0POPt7" is not accessible.
15-07-22 01:49:11.115 [WARNING] [acd_cli] - Directory cycle detected in "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/wOT3rr5/7djoZW-pRADQ/XlM,qeox".
15-07-22 01:49:11.181 [WARNING] [acd_cli] - Directory cycle detected in "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/35lJT6B/wOT3rr5/vxE7O-TKs-/xfBiIrkUwrLwAm0jlsQ1,L6ul5h8sFW5cPAB".
15-07-22 01:49:12.436 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/5q1o7Z7q/U8dDJfGj61/CBxv60dO-z8/rALDIY5nP,/5ar6WPnFZL3x2K25HQ2/-nC88W0hZeWX,-/sQHzYo03OLgT4kWH/-i9Uw-" is not accessible.
15-07-22 01:49:12.437 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/5q1o7Z7q/U8dDJfGj61/CBxv60dO-z8/rALDIY5nP,/5ar6WPnFZL3x2K25HQ2/-nC88W0hZeWX,-/sQHzYo03OLgT4kWH/LWUHi0" is not accessible.
15-07-22 01:49:12.438 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/5q1o7Z7q/U8dDJfGj61/CBxv60dO-z8/rALDIY5nP,/5ar6WPnFZL3x2K25HQ2/-nC88W0hZeWX,-/sQHzYo03OLgT4kWH/MRFGjCD" is not accessible.
15-07-22 01:49:12.440 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/5q1o7Z7q/U8dDJfGj61/CBxv60dO-z8/rALDIY5nP,/5ar6WPnFZL3x2K25HQ2/-nC88W0hZeWX,-/sQHzYo03OLgT4kWH/T6LEd,B" is not accessible.
15-07-22 01:49:12.441 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/5q1o7Z7q/U8dDJfGj61/CBxv60dO-z8/rALDIY5nP,/5ar6WPnFZL3x2K25HQ2/-nC88W0hZeWX,-/sQHzYo03OLgT4kWH/WTLAAT8" is not accessible.
Traceback (most recent call last):
  File "/usr/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a2', 'console_scripts', 'acdcli')()
  File "/usr/bin/acd_cli.py", line 1096, in main
    sys.exit(args.func(args))
  File "/usr/bin/acd_cli.py", line 572, in upload_action
    args.deduplicate, excl_re, jobs)
  File "/usr/bin/acd_cli.py", line 209, in create_upload_jobs
    return traverse_ul_dir(dirs, path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 263, in traverse_ul_dir
    overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 209, in create_upload_jobs
    return traverse_ul_dir(dirs, path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 263, in traverse_ul_dir
    overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 209, in create_upload_jobs
    return traverse_ul_dir(dirs, path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 263, in traverse_ul_dir
    overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 209, in create_upload_jobs
    return traverse_ul_dir(dirs, path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 263, in traverse_ul_dir
    overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 209, in create_upload_jobs
    return traverse_ul_dir(dirs, path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 263, in traverse_ul_dir
    overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 209, in create_upload_jobs
    return traverse_ul_dir(dirs, path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 263, in traverse_ul_dir
    overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 209, in create_upload_jobs
    return traverse_ul_dir(dirs, path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 263, in traverse_ul_dir
    overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 209, in create_upload_jobs
    return traverse_ul_dir(dirs, path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 263, in traverse_ul_dir
    overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 209, in create_upload_jobs
    return traverse_ul_dir(dirs, path, parent_id, overwr, force, dedup, exclude, jobs)
  File "/usr/bin/acd_cli.py", line 263, in traverse_ul_dir
    overwr, force, dedup, exclude, jobs)
TypeError: unsupported operand type(s) for |=: 'int' and 'NoneType'
[lance@Arch-Chromebook 0afd4383-73bb-4234-bba0-f69b261248c3]$ 
```

**Comment by msh100** [comment]
To achieve this I have been creating directories and uploading files one by one, I guess that's a bit indirect thinking about it now.

```
15-07-22 01:49:08.091 [ERROR] [acd_cli] - Path "/mnt/encfs/TQDEpnp6Kn3MzJZWhvD/0KBEie5/Tu1dny,nrA,/OsusfweGTI4/uIpZqD0fADKh3p,JSM4" is not accessible.
```

This to me suggests that the user you're running `acd_cli` from can't read the mount. Did you mount encfs with the `--public` flag or from that user?

**Comment by ShapeShifter499** [comment]
@msh100 I already made the mount as a non-root user 

```
[lance@Arch-Chromebook 0afd4383-73bb-4234-bba0-f69b261248c3]$ encfs --reverse  --public /run/media/lance/0afd4383-73bb-4234-bba0-f69b261248c3/ /mnt/encfs/
04:07:06 (main.cpp:344) option '--public' ignored for non-root user
```

**Comment by msh100** [comment]
@ShapeShifter499 is that user the same user which `acd_cli` is running from?

**Comment by ShapeShifter499** [comment]
@msh100 yes

**Comment by ShapeShifter499** [comment]
@msh100 just occurred to me, could issue stem from permissions on the non-encrypted folder?

**Comment by msh100** [comment]
Perhaps, can you read the stuff on the encfs mountpoint with other applications on that user?

**Comment by ShapeShifter499** [comment]
yes, thunar file browser in xfce

**Comment by ShapeShifter499** [comment]
I just ran "chmod 777 -R" on this hard drive and that seems to have corrected things.  This was a backup drive so it really didn't matter what file permissions there were.

**Comment by ShapeShifter499** [comment]
I actually found out it was broken symlinks in the unencrypted filesystem, I found and removed them and that was the fix.

**Comment by resipsa2917** [comment]
Sounds like you solved it.  For me I use:

/usr/bin/encfs --reverse --public /data/ /dataEncrypted/

Then upload /dataEncrypted/ to ACD.
