### ISSUE TITLE
Fuse media interruption

### ISSUE THREAD

**Issue by msh100** [yadayada/acd_cli#94]
I am trying to stream a large media file with `acd_cli`. I have encountered an issue where the media will simply stop.

The `acd_cli` mount log:

```
15-07-22 20:23:52.253 [DEBUG] [acdcli.fuse] - read $FILENAME, ln: 131072 of: 628736000 fh 19
15-07-22 20:23:52.262 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 628736000-628867071
15-07-22 20:23:52.262 [DEBUG] [acdcli.fuse] - s: 628736000-1048559615; r: 628736000-628867071
15-07-22 20:23:52.262 [DEBUG] [acdcli.fuse] - 131072
15-07-22 20:23:53.163 [DEBUG] [acdcli.fuse] - read $FILENAME, ln: 131072 of: 628867072 fh 19
15-07-22 20:23:53.177 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 628867072-628998143
15-07-22 20:23:53.178 [DEBUG] [acdcli.fuse] - s: 628867072-1048559615; r: 628867072-628998143
15-07-22 20:23:53.178 [DEBUG] [acdcli.fuse] - 131072
15-07-22 20:23:53.179 [DEBUG] [acdcli.fuse] - read $FILENAME, ln: 131072 of: 628998144 fh 19
15-07-22 20:23:53.188 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 628998144-629129215
15-07-22 20:23:53.188 [DEBUG] [acdcli.fuse] - s: 628998144-1048559615; r: 628998144-629129215
15-07-22 20:23:53.189 [DEBUG] [acdcli.fuse] - 130577
15-07-22 20:23:53.189 [DEBUG] [acdcli.fuse] - read $FILENAME, ln: 131072 of: 629129216 fh 19
15-07-22 20:23:53.198 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 629129216-629260287
15-07-22 20:23:53.198 [DEBUG] [acdcli.fuse] - s: 629128721-1048559615; r: 629129216-629260287
15-07-22 20:23:53.198 [DEBUG] [acdcli.api.content] - o 629129216 l 524288000
15-07-22 20:23:53.198 [DEBUG] [acdcli.api.common] - Retry 0, waiting -315.241276 secs
15-07-22 20:23:53.198 [DEBUG] [acdcli.api.common] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/$NODE/content"
15-07-22 20:23:53.200 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (14): content-na.drive.amazonaws.com
15-07-22 20:23:53.828 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/$NODE/content HTTP/1.1" 206 524288000
15-07-22 20:23:54.139 [DEBUG] [acdcli.fuse] - 131072
15-07-22 20:23:54.139 [DEBUG] [acdcli.fuse] - read $FILENAME, ln: 131072 of: 629260288 fh 19
15-07-22 20:23:54.152 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 629260288-629391359
15-07-22 20:23:54.152 [DEBUG] [acdcli.fuse] - s: 629128721-1048559615; r: 629260288-629391359
15-07-22 20:23:54.152 [DEBUG] [acdcli.fuse] - s: 629260288-1153417215; r: 629260288-629391359
15-07-22 20:23:54.257 [DEBUG] [acdcli.fuse] - 131072
15-07-22 20:23:54.258 [DEBUG] [acdcli.fuse] - read $FILENAME, ln: 131072 of: 629391360 fh 19
15-07-22 20:23:54.274 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 629391360-629522431
15-07-22 20:23:54.274 [DEBUG] [acdcli.fuse] - s: 629128721-1048559615; r: 629391360-629522431
15-07-22 20:23:54.274 [DEBUG] [acdcli.fuse] - s: 629391360-1153417215; r: 629391360-629522431
15-07-22 20:23:54.336 [DEBUG] [acdcli.fuse] - 131072
15-07-22 20:23:54.337 [DEBUG] [acdcli.fuse] - release $FILEPATH/$FILENAME, 19
```

The only error I see on the media player is

```
Jul 22, 2015 20:23:54 ... 0x3749ea0 Read error
```

Do you have any idea what's going on?

**Comment by msh100** [comment]
Happened again

```
15-07-22 21:35:21.147 [DEBUG] [acdcli.fuse] - read $FILE, ln: 131072 of: 1020755968 fh 9
15-07-22 21:35:21.160 [DEBUG] [acdcli.fuse] - s: 1020755968-1153544191; r: 1020755968-1020887039
15-07-22 21:35:21.160 [DEBUG] [acdcli.fuse] - 118289
15-07-22 21:35:21.161 [DEBUG] [acdcli.fuse] - read $FILE, ln: 131072 of: 1020887040 fh 9
15-07-22 21:35:21.173 [DEBUG] [acdcli.fuse] - s: 1020874257-1153544191; r: 1020887040-1021018111
15-07-22 21:35:21.173 [DEBUG] [acdcli.fuse] - s: 245760-524287999; r: 1020887040-1021018111
15-07-22 21:35:21.173 [DEBUG] [acdcli.fuse] - s: 1621766144-1621774812; r: 1020887040-1021018111
15-07-22 21:35:21.173 [DEBUG] [acdcli.fuse] - s: 1621774813-1621774812; r: 1020887040-1021018111
15-07-22 21:35:21.173 [DEBUG] [acdcli.fuse] - s: 629256192-1152708607; r: 1020887040-1021018111
15-07-22 21:35:21.173 [DEBUG] [acdcli.api.content] - o 1020887040 l 524288000
15-07-22 21:35:21.173 [DEBUG] [acdcli.api.common] - Retry 0, waiting -3182.905667 secs
15-07-22 21:35:21.174 [INFO] [acdcli.api.oauth] - Token expired at 2015-07-22 21:03:14.449523.
15-07-22 21:35:21.174 [INFO] [acdcli.api.oauth] - Refreshing authentication token.
15-07-22 21:35:21.175 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): tensile-runway-92512.appspot.com
15-07-22 21:35:21.670 [DEBUG] [requests.packages.urllib3.connectionpool] - "POST / HTTP/1.1" 200 1042
15-07-22 21:35:21.672 [INFO] [acdcli.api.oauth] - New token expires at 2015-07-22 22:33:21.174401.
15-07-22 21:35:21.689 [DEBUG] [acdcli.api.common] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/$NODE/content"
15-07-22 21:35:21.690 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (5): content-na.drive.amazonaws.com
send: b'GET /drive/v1/account/quota HTTP/1.1\r\nHost: cdws.us-east-1.amazonaws.com\r\nConnection: keep-alive\r\nAuthorization: Bearer <REMOVED>\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: acd_cli/0.3.0a2 python-requests/2.7.0 CPython/3.4.0 Linux/2.6.32-042stab094.7\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server header: Date header: Content-Type header: Content-Length header: Connection header: x-amzn-RequestId header: Content-Encoding header: Vary send: b'GET /cdproxy/nodes/$NODE/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAuthorization: Bearer <REMOVED>\r\nAccept-Encoding: gzip, deflate\r\nRange: bytes=629256192-1153544191\r\nConnection: keep-alive\r\nUser-Agent: acd_cli/0.3.0a2 python-requests/2.7.0 CPython/3.4.0 Linux/2.6.32-042stab094.7\r\nAccept: */*\r\n\r\n'
reply: 'HTTP/1.1 206 Partial Content\r\n'
header: Accept-Ranges header: Cache-Control header: Content-Disposition header: Content-Range header: Content-Type header: Date header: ETag header: Server header: x-amzn-RequestId header: Content-Length header: Connection send: b'GET /cdproxy/nodes/$NODE/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAuthorization: Bearer <REMOVED>\r\nAccept-Encoding: gzip, deflate\r\nRange: bytes=0-524287999\r\nConnection: keep-alive\r\nUser-Agent: acd_cli/0.3.0a2 python-requests/2.7.0 CPython/3.4.0 Linux/2.6.32-042stab094.7\r\nAccept: */*\r\n\r\n'
reply: 'HTTP/1.1 206 Partial Content\r\n'
header: Accept-Ranges header: Cache-Control header: Content-Disposition header: Content-Range header: Content-Type header: Date header: ETag header: Server header: x-amzn-RequestId header: Content-Length header: Connection send: b'GET /cdproxy/nodes/$NODE/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAuthorization: Bearer <REMOVED>\r\nAccept-Encoding: gzip, deflate\r\nRange: bytes=1621745664-2146033663\r\nConnection: keep-alive\r\nUser-Agent: acd_cli/0.3.0a2 python-requests/2.7.0 CPython/3.4.0 Linux/2.6.32-042stab094.7\r\nAccept: */*\r\n\r\n'
reply: 'HTTP/1.1 206 Partial Content\r\n'
header: Accept-Ranges header: Cache-Control header: Content-Disposition header: Content-Range header: Content-Type header: Date header: ETag header: Server header: x-amzn-RequestId header: Content-Length header: Connection send: b'GET /cdproxy/nodes/$NODE/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAuthorization: Bearer <REMOVED>\r\nAccept-Encoding: gzip, deflate\r\nRange: bytes=1621766144-2146054143\r\nConnection: keep-alive\r\nUser-Agent: acd_cli/0.3.0a2 python-requests/2.7.0 CPython/3.4.0 Linux/2.6.32-042stab094.7\r\nAccept: */*\r\n\r\n'
reply: 'HTTP/1.1 206 Partial Content\r\n'
header: Accept-Ranges header: Cache-Control header: Content-Disposition header: Content-Range header: Content-Type header: Date header: ETag header: Server header: x-amzn-RequestId header: Content-Length header: Connection send: b'GET /cdproxy/nodes/$NODE/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAuthorization: Bearer <REMOVED>\r\nAccept-Encoding: gzip, deflate\r\nRange: bytes=628420608-1152708607\r\nConnection: keep-alive\r\nUser-Agent: acd_cli/0.3.0a2 python-requests/2.7.0 CPython/3.4.0 Linux/2.6.32-042stab094.7\r\nAccept: */*\r\n\r\n'
reply: 'HTTP/1.1 206 Partial Content\r\n'
header: Accept-Ranges header: Cache-Control header: Content-Disposition header: Content-Range header: Content-Type header: Date header: ETag header: Server header: x-amzn-RequestId header: Content-Length header: Connection send: b'POST / HTTP/1.1\r\nHost: tensile-runway-92512.appspot.com\r\nContent-Length: 473\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: acd_cli/0.3.0a2 python-requests/2.7.0 CPython/3.4.0 Linux/2.6.32-042stab094.7\r\nConnection: keep-alive\r\nContent-Type: application/x-www-form-urlencoded\r\nAccept: */*\r\n\r\nrefresh_token=<REMOVED>'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type header: Cache-Control header: Date header: Server header: Content-Length header: Alternate-Protocol send: b'GET /cdproxy/nodes/$NODE/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAuthorization: Bearer <REMOVED>\r\nAccept-Encoding: gzip, deflate\r\nRange: bytes=1020887040-1545175039\r\nConnection: keep-alive\r\nUser-Agent: acd_cli/0.3.0a2 python-requests/2.7.0 CPython/3.4.0 Linux/2.6.32-042stab094.7\r\nAccept: */*\r\n\r\n'
reply: 'HTTP/1.1 206 Partial Content\r\n'15-07-22 21:35:22.351 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/$NODE/content HTTP/1.1" 206 524288000
15-07-22 21:35:22.656 [DEBUG] [acdcli.fuse] - 131072
15-07-22 21:35:22.657 [DEBUG] [acdcli.fuse] - read $FILE, ln: 131072 of: 1021018112 fh 9
15-07-22 21:35:22.672 [DEBUG] [acdcli.fuse] - s: 1020874257-1153544191; r: 1021018112-1021149183
15-07-22 21:35:22.672 [DEBUG] [acdcli.fuse] - s: 245760-524287999; r: 1021018112-1021149183
15-07-22 21:35:22.672 [DEBUG] [acdcli.fuse] - s: 1621766144-1621774812; r: 1021018112-1021149183
15-07-22 21:35:22.673 [DEBUG] [acdcli.fuse] - s: 1621774813-1621774812; r: 1021018112-1021149183
15-07-22 21:35:22.673 [DEBUG] [acdcli.fuse] - s: 629256192-1152708607; r: 1021018112-1021149183
15-07-22 21:35:22.673 [DEBUG] [acdcli.fuse] - s: 1021018112-1545175039; r: 1021018112-1021149183
15-07-22 21:35:22.776 [DEBUG] [acdcli.fuse] - 131072
15-07-22 21:35:22.777 [DEBUG] [acdcli.fuse] - read $FILE, ln: 131072 of: 1021149184 fh 9
15-07-22 21:35:22.785 [DEBUG] [acdcli.fuse] - s: 1020874257-1153544191; r: 1021149184-1021280255
15-07-22 21:35:22.785 [DEBUG] [acdcli.fuse] - s: 245760-524287999; r: 1021149184-1021280255
15-07-22 21:35:22.786 [DEBUG] [acdcli.fuse] - s: 1621766144-1621774812; r: 1021149184-1021280255
15-07-22 21:35:22.786 [DEBUG] [acdcli.fuse] - s: 1621774813-1621774812; r: 1021149184-1021280255
15-07-22 21:35:22.786 [DEBUG] [acdcli.fuse] - s: 629256192-1152708607; r: 1021149184-1021280255
15-07-22 21:35:22.786 [DEBUG] [acdcli.fuse] - s: 1021149184-1545175039; r: 1021149184-1021280255
15-07-22 21:35:22.886 [DEBUG] [acdcli.fuse] - 131072
15-07-22 21:35:22.887 [DEBUG] [acdcli.fuse] - release $PATH/$FILE, 9
```

**Comment by yadayada** [comment]
Currently, no. It seems the reads are complete 128K blocks and then, suddenly, the file is closed. 
I didn't have any problems streaming with vlc. Which player are you using?

**Comment by msh100** [comment]
```
15-07-22 21:35:21.147 [DEBUG] [acdcli.fuse] - read $FILE, ln: 131072 of: 1020755968 fh 9
15-07-22 21:35:21.160 [DEBUG] [acdcli.fuse] - s: 1020755968-1153544191; r: 1020755968-1020887039
15-07-22 21:35:21.160 [DEBUG] [acdcli.fuse] - 118289
```

Is it getting back a 128K block there?

**Comment by yadayada** [comment]
A bit short, eh? I also didn't notice the erratic 130577 in your first message before.

**Comment by msh100** [comment]
Do you think this is going to be a difficult one to resolve? Unfortunately I am out of my depth at this point.

**Comment by yadayada** [comment]
Should be a few lines in the ``StreamChunk.get`` method to check if the chunk size matches the requested length and try to read a bit more if something is missing. I did not assume this could happen except, only hypothetically, at the file ending (and chunk ending).

**Comment by msh100** [comment]
In both cases it seems to be caused by authentication. So I assume the chunk download was interrupted by that

**Comment by yadayada** [comment]
It is the other way round. The token must be refreshed because the prior read was incomplete. Your player tries to continue at the next 128K block offset, but there is no chunk that begins exactly at that offset, so a new file content chunk must be requested. Because the token is outdated for half an hour, it must be refreshed first.

Also, I do not see any oauth messages in the first log.

**Comment by msh100** [comment]
Okay, makes sense. Thanks for your help with this. Is there anything I can do to help or speed this up?

**Comment by yadayada** [comment]
You can have a look at the ``StreamChunk.get`` method if you want.

**Comment by msh100** [comment]
I have tried altering `StreamChunk.get` in the following way:

```python
        def get(self, length):
            b = next(self.r.iter_content(length))

            if len(b) < length:
                logger.debug('Packet smaller than expected, trying to fetch diff')
                try:
                    b += next(self.r.iter_content(length - len(b)))
                except StopIteration:
                    logger.debug('Reached end of content')

            self.offset += len(b)
            logger.debug(len(b))
            return b
```

```
15-07-23 15:28:06.958 [DEBUG] [acdcli.fuse] - read $FILE, ln: 131072 of: 1116585984 fh 7
15-07-23 15:28:06.970 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 1116585984-1116717055
15-07-23 15:28:06.970 [DEBUG] [acdcli.fuse] - s: 1048559616-1048559615; r: 1116585984-1116717055
15-07-23 15:28:06.970 [DEBUG] [acdcli.fuse] - s: 1116585984-1572847615; r: 1116585984-1116717055
15-07-23 15:28:07.109 [DEBUG] [acdcli.fuse] - Packet smaller than expected, trying to fetch diff
15-07-23 15:28:11.456 [DEBUG] [acdcli.fuse] - Reached end of content
15-07-23 15:28:11.456 [DEBUG] [acdcli.fuse] - 130576
```

To me this suggests that the content needs to be re-fetched from Amazon. Maybe I am trying the wrong things?

**Comment by yadayada** [comment]
Thanks trying that. I thought there might be something wrong with the requests package.
You are right, it cannot be fixed at that stage. Could you revert the changes please and modify the end of the function to

```python
            if len(b) < length:
                raise Exception
            return b
```

That should cause the chunk to be reloaded in the ``File.get`` method, hopefully.

**Comment by msh100** [comment]
Testing now, I will let you know when I encounter it next (it's a bit random).

**Comment by msh100** [comment]
I suspect this has worked, I just encountered the exception:

```
15-07-23 20:00:01.273 [DEBUG] [acdcli.fuse] - read $FILE, ln: 131072 of: 1934344192 fh 10
15-07-23 20:00:01.285 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 1934344192-1934475263
15-07-23 20:00:01.285 [DEBUG] [acdcli.fuse] - s: 1048559616-1048559615; r: 1934344192-1934475263
15-07-23 20:00:01.285 [DEBUG] [acdcli.fuse] - s: 1599062016-1599062015; r: 1934344192-1934475263
15-07-23 20:00:01.285 [DEBUG] [acdcli.fuse] - s: 1074774016-1598930943; r: 1934344192-1934475263
15-07-23 20:00:01.285 [DEBUG] [acdcli.fuse] - s: 1934344192-2076586269; r: 1934344192-1934475263
15-07-23 20:00:01.358 [DEBUG] [acdcli.fuse] - 131072
15-07-23 20:00:01.358 [DEBUG] [acdcli.fuse] - read $FILE, ln: 131072 of: 1934475264 fh 10
15-07-23 20:00:01.377 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 1934475264-1934606335
15-07-23 20:00:01.377 [DEBUG] [acdcli.fuse] - s: 1048559616-1048559615; r: 1934475264-1934606335
15-07-23 20:00:01.377 [DEBUG] [acdcli.fuse] - s: 1599062016-1599062015; r: 1934475264-1934606335
15-07-23 20:00:01.377 [DEBUG] [acdcli.fuse] - s: 1074774016-1598930943; r: 1934475264-1934606335
15-07-23 20:00:01.379 [DEBUG] [acdcli.fuse] - s: 1934475264-2076586269; r: 1934475264-1934606335
15-07-23 20:00:01.488 [DEBUG] [acdcli.fuse] - 130578
15-07-23 20:00:01.488 [DEBUG] [acdcli.fuse] - Exception raised as data too short
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/bundled/fuse.py", line 429, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python3.4/dist-packages/acdcli/bundled/fuse.py", line 509, in read
    offset, fh)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/bundled/fuse.py", line 724, in __call__
    return getattr(self, op)(*args)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/fuse.py", line 140, in read
    return StreamedResponseCache.get(node.id, offset, length, node.size)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/fuse.py", line 90, in get
    return cls.files[id].get(id, offset, length, total)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/fuse.py", line 62, in get
    for c in self.chunks:
RuntimeError: deque mutated during iteration
15-07-23 20:00:01.516 [DEBUG] [acdcli.fuse] - read $FILE, ln: 131072 of: 1934606336 fh 10
15-07-23 20:00:01.565 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 1934606336-1934737407
15-07-23 20:00:01.565 [DEBUG] [acdcli.fuse] - s: 1048559616-1048559615; r: 1934606336-1934737407
15-07-23 20:00:01.565 [DEBUG] [acdcli.fuse] - s: 1599062016-1599062015; r: 1934606336-1934737407
15-07-23 20:00:01.565 [DEBUG] [acdcli.fuse] - s: 1074774016-1598930943; r: 1934606336-1934737407
15-07-23 20:00:01.565 [DEBUG] [acdcli.api.content] - o 1934606336 l 524288000
15-07-23 20:00:01.565 [DEBUG] [acdcli.api.common] - Retry 0, waiting -515.078843 secs
15-07-23 20:00:01.565 [DEBUG] [acdcli.api.common] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/$NODE/content"
15-07-23 20:00:01.567 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (9): content-na.drive.amazonaws.com
15-07-23 20:00:02.186 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/$NODE/content HTTP/1.1" 206 141979934
15-07-23 20:00:02.502 [DEBUG] [acdcli.fuse] - 131072
15-07-23 20:00:02.502 [DEBUG] [acdcli.fuse] - read $FILE, ln: 4096 of: 1934475264 fh 10
15-07-23 20:00:02.524 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 1934475264-1934479359
15-07-23 20:00:02.525 [DEBUG] [acdcli.fuse] - s: 1048559616-1048559615; r: 1934475264-1934479359
15-07-23 20:00:02.525 [DEBUG] [acdcli.fuse] - s: 1599062016-1599062015; r: 1934475264-1934479359
15-07-23 20:00:02.525 [DEBUG] [acdcli.fuse] - s: 1074774016-1598930943; r: 1934475264-1934479359
15-07-23 20:00:02.525 [DEBUG] [acdcli.fuse] - s: 1934737408-2076586269; r: 1934475264-1934479359
15-07-23 20:00:02.525 [DEBUG] [acdcli.api.content] - o 1934475264 l 524288000
15-07-23 20:00:02.525 [DEBUG] [acdcli.api.common] - Retry 0, waiting 0.501280 secs
15-07-23 20:00:03.027 [DEBUG] [acdcli.api.common] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/$NODE/content"
15-07-23 20:00:03.028 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (10): content-na.drive.amazonaws.com
15-07-23 20:00:03.652 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/$NODE/content HTTP/1.1" 206 142111006
15-07-23 20:00:03.653 [DEBUG] [acdcli.fuse] - 4096
15-07-23 20:00:03.653 [DEBUG] [acdcli.fuse] - read $FILE, ln: 4096 of: 1934479360 fh 10
15-07-23 20:00:03.676 [DEBUG] [acdcli.fuse] - s: 524271616-524287999; r: 1934479360-1934483455
15-07-23 20:00:03.676 [DEBUG] [acdcli.fuse] - s: 1048559616-1048559615; r: 1934479360-1934483455
15-07-23 20:00:03.676 [DEBUG] [acdcli.fuse] - s: 1599062016-1599062015; r: 1934479360-1934483455
15-07-23 20:00:03.676 [DEBUG] [acdcli.fuse] - s: 1074774016-1598930943; r: 1934479360-1934483455
15-07-23 20:00:03.676 [DEBUG] [acdcli.fuse] - s: 1934737408-2076586269; r: 1934479360-1934483455
15-07-23 20:00:03.677 [DEBUG] [acdcli.fuse] - s: 1934479360-2076586269; r: 1934479360-1934483455
15-07-23 20:00:03.677 [DEBUG] [acdcli.fuse] - 4096
```

Note the "Exception raised as data too short" message is something I added.

It appears to get a bit of data which is too short, and then retry a smaller chunk and build up as if it is reading a new file (which I suspect is what the client is doing).

This solution raises an exception at the genuine end of a file which I guess is fine as it doesn't appear to loop.

I am going to keep testing to see if this happens again however I suspect this is a solution at this point.

**Comment by yadayada** [comment]
Whoever programmed this File class made an error by mutating the deque while iterating over it.

**Comment by yadayada** [comment]
So, now I have this for the StreamChunk

```python
        def get(self, length):
            b = next(self.r.iter_content(length))
            logger.debug('streamed %ib' % len(b))
            self.offset += len(b)

            if len(b) < length and self.offset <= self.end:
                raise Exception
            return b
```

and this for the beginning of the File class's get method

```python
        def get(self, id, offset, length, total):
            self.access = time()

            i = self.chunks.__len__() - 1
            while i >= 0:
                c = self.chunks[i]
                if c.has_byte_range(offset, length):
                    try:
                        bytes_ = c.get(length)
                    except:
                        self.chunks.remove(c)
                    else:
                        return bytes_
                i -= 1
```

**Comment by msh100** [comment]
I just encountered this again so I would say this is a confirmed fix. Do you suggest the fix is implemented into `acd_cli` in this way or do you have a better suggestion?

**Comment by msh100** [comment]
Do you want me to test these changes also?

**Comment by yadayada** [comment]
Well, I don't want to keep the faulty deque element removal in.

**Comment by msh100** [comment]
Sorry can you provider a branch or maybe a patch? I am not too sure what you want to change in the method.

**Comment by yadayada** [comment]
Pushed it to the dev branch.

**Comment by msh100** [comment]
So far this seems to be working well, in the 4 hours I have been testing from the dev branch I have not encountered any interruptions or exceptions/anything strange in the log files. I am pretty confident this is a good fix. I will continue testing.

**Comment by bgold0** [comment]
I was not able to find out how to fix this issue. Does anyone have a fix?

**Comment by yadayada** [comment]
@bgold0 I'm fairly sure you didn't encounter the original issue.
