### ISSUE TITLE
Folders not synced according to upload - TypeError: data should be a bytes-like object or an iterable, got <class 'requests_toolbelt.multipart.encoder.MultipartEncoder'>

### ISSUE THREAD

**Issue by Stapper** [yadayada/acd_cli#96]
After I sync I am still receiving following errors:
```
#~ acd_cli sync
Syncing...
Done.
#~ acd_cli ul /media/Data/Music /
15-07-24 01:47:22.659 [ERROR] [acd_cli] - Folder "Blood red shoes" already exists. Please sync.
15-07-24 01:47:26.766 [ERROR] [acd_cli] - Folder "EELS" already exists. Please sync.
15-07-24 01:47:30.741 [ERROR] [acd_cli] - Folder "Kings Of Leon" already exists. Please sync.
15-07-24 01:47:30.757 [WARNING] [acdcli.api.common] - Waiting 5.708448s because of error(s).
15-07-24 01:47:36.736 [ERROR] [acd_cli] - Folder "Only by the Night" already exists. Please sync.
15-07-24 01:47:37.709 [WARNING] [acdcli.api.common] - Waiting 5.258728s because of error(s).
15-07-24 01:47:43.196 [ERROR] [acd_cli] - Folder "Hold on to your culture" already exists. Please sync.
15-07-24 01:47:43.665 [WARNING] [acdcli.api.common] - Waiting 17.263120s because of error(s).
15-07-24 01:48:01.182 [ERROR] [acd_cli] - Folder "McLusky" already exists. Please sync.
15-07-24 01:48:02.646 [WARNING] [acdcli.api.common] - Waiting 60.990148s because of error(s).
15-07-24 01:49:03.945 [ERROR] [acd_cli] - Folder "Lullabies to Paralyze" already exists. Please sync.
15-07-24 01:49:09.323 [WARNING] [acdcli.api.common] - Waiting 122.499532s because of error(s).
15-07-24 01:51:13.009 [ERROR] [acd_cli] - Traceback (most recent call last):s
  File "/usr/lib/python3.2/http/client.py", line 780, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.2/ssl.py", line 368, in sendall
    amount = len(data)
TypeError: object of type 'MultipartEncoder' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli.py", line 166, in wrapped
    ret_val = f(*args, **kwargs)
  File "/usr/local/bin/acd_cli.py", line 281, in upload_file
    deduplication=dedup)
  File "/usr/local/lib/python3.2/dist-packages/acdcli/api/content.py", line 118, in upload_file
    stream=True, headers={'Content-Type': m.content_type})
  File "/usr/local/lib/python3.2/dist-packages/acdcli/api/common.py", line 236, in post
    return cls._request('POST', url, acc_codes, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/acdcli/api/common.py", line 139, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/acdcli/api/common.py", line 222, in _request
    r = cls.__session.request(type_, url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.2/http/client.py", line 970, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.2/http/client.py", line 1008, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.2/http/client.py", line 966, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.2/http/client.py", line 815, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.2/http/client.py", line 787, in send
    "or an iterable, got %r" % type(data))
TypeError: data should be a bytes-like object or an iterable, got <class 'requests_toolbelt.multipart.encoder.MultipartEncoder'>
```

Is this a known issue or an issue with my install? 
These are all subdirectories of a directory I'm issuing from the command line.
It doesn't matter how many times i sync, the message is always there.

**Comment by chrisidefix** [comment]
Hi! How did you install acd_cli? Are you using a release version (e.g. by checkout out the appropriate git tag) or are you using the latest master / dev branch?

**Comment by yadayada** [comment]
If you are using Python 3.2.3, you're out of luck.

https://github.com/sigmavirus24/requests-toolbelt/issues/88

**Comment by Stapper** [comment]
Ok so the first part of the error
```
15-07-24 01:47:22.659 [ERROR] [acd_cli] - Folder "Blood red shoes" already exists. Please sync.
15-07-24 01:47:26.766 [ERROR] [acd_cli] - Folder "EELS" already exists. Please sync.
15-07-24 01:47:30.741 [ERROR] [acd_cli] - Folder "Kings Of Leon" already exists. Please sync.
```
Was because of upper /lower casing for example EELS and Eels - So that's solved

Regarding the 'toolbelt' I guess I'm out of luck :)

So I guess this can be closed, thanks for the info.
