### ISSUE TITLE
(sqlite3.OperationalError) database is locked

### ISSUE THREAD

**Issue by derobert** [yadayada/acd_cli#99]
When doing an upload, I get a bunch of "database locked" exceptions. This might be related to me using `-x 8` (8 concurrent uploads). I notice you're using sqlite in "delete" journal mode instead of WAL; I've changed it (`PRAGMA journal_mode=WAL;` see https://www.sqlite.org/wal.html) and will let you know if I see any more errors. (**edit:** still see some in WAL mode)

    15-07-25 13:32:00.694 [ERROR] [acd_cli] - Traceback (most recent call last):
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
        cursor.execute(statement, parameters)
    sqlite3.OperationalError: database is locked
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/anthony/.local/bin/acd_cli.py", line 168, in wrapped
        ret_val = f(*args, **kwargs)
      File "/home/anthony/.local/bin/acd_cli.py", line 314, in upload_file
        sync.insert_node(r)
      File "/home/anthony/.local/lib/python3.4/site-packages/acdcli/cache/sync.py", line 54, in insert_node
        insert_nodes([node])
      File "/home/anthony/.local/lib/python3.4/site-packages/acdcli/cache/sync.py", line 46, in insert_nodes
        insert_files(files)
      File "/home/anthony/.local/lib/python3.4/site-packages/acdcli/cache/sync.py", line 103, in insert_files
        ) for f in files
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
        return connection.execute(statement, *multiparams, **params)
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 906, in execute
        return self._execute_text(object, multiparams, params)
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
        statement, parameters
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
        context)
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
        exc_info
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
        raise value.with_traceback(tb)
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
      File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'INSERT OR REPLACE INTO nodes (id, type, name, description, created, modified, updated, status) VALUES (:id, :type, :name, :description, :created, :modified, :updated, :status)'] [parameters: {'status': 'AVAILABLE', 'name': 'IMG_4189.JPG.png', 'description': None, 'id': 'fy1cW28WSjmE-Ksvbb4BRQ', 'updated': datetime.datetime(2015, 7, 25, 17, 31, 55, 254472), 'type': 'file', 'modified': datetime.datetime(2015, 7, 25, 17, 31, 55, 193000, tzinfo=tzutc()), 'created': datetime.datetime(2015, 7, 25, 17, 31, 55, 5000, tzinfo=tzutc())}]

**Comment by yadayada** [comment]
Ok, could you also check again with a higher ``PRAGMA busy_timeout = ...`` with more than (the standard?) 5000ms, please?

**Comment by derobert** [comment]
On 07/25/2015 02:45 PM, yadayada wrote:
>
> Ok, could you also check again with a higher |PRAGMA busy_timeout = 
> ...| with more than (the standard?) 5000ms, please?
>
I'd like to, but that doesn't persist in the database (unlike WAL) so 
I'd need to patch it in to the code somewhere... and I don't know 
Python, and a quick grep didn't find any other pragma statements to 
easily tack it on to.

If you can tell me how to add in that pragma I'll be happy to test.

**Comment by yadayada** [comment]
```diff
--- db.py	2015-07-25 20:59:08.227202770 +0200
+++ db_b.py	2015-07-26 07:49:42.920466917 +0200
@@ -296,6 +296,11 @@
     session_factory = sessionmaker(bind=engine)
     Session = scoped_session(session_factory)
 
+    timeout = 15000
+    r = engine.execute('PRAGMA busy_timeout=%i;' % timeout)
+    if r.first()[0] != timeout:
+        logger.warning('Setting timeout failed.')
+
     if uninitialized:
         return True

```

**Comment by derobert** [comment]
Ok. I've applied the patch directly to 
~/.local/lib/python3.4/site-packages/acdcli/cache/db.py and removed 
__pycache__/db.cpython-34.pyc (which was then regenerated when I ran 
acd_cli again). I'll let you know when I find another big directory to 
upload. Or worst case, just re-upload one...

**Comment by derobert** [comment]
Still getting that error. Seems to mainly happen when uploading a bunch 
of small files, BTW.

15-07-29 05:01:39.169 [ERROR] [acd_cli] - Traceback (most recent call last):
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
     context)
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
     cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
   File "/home/anthony/.local/bin/acd_cli.py", line 168, in wrapped
     ret_val = f(*args, **kwargs)
   File "/home/anthony/.local/bin/acd_cli.py", line 314, in upload_file
     sync.insert_node(r)
   File "/home/anthony/.local/lib/python3.4/site-packages/acdcli/cache/sync.py", line 54, in insert_node
     insert_nodes([node])
   File "/home/anthony/.local/lib/python3.4/site-packages/acdcli/cache/sync.py", line 46, in insert_nodes
     insert_files(files)
   File "/home/anthony/.local/lib/python3.4/site-packages/acdcli/cache/sync.py", line 110, in insert_files
     ) for f in files
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
     return connection.execute(statement, *multiparams, **params)
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 906, in execute
     return self._execute_text(object, multiparams, params)
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
     statement, parameters
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
     context)
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
     exc_info
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
     reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
     raise value.with_traceback(tb)
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
     context)
   File "/home/anthony/.local/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
     cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'INSERT OR REPLACE INTO files (id, md5, size) VALUES (:id, :md5, :size)'] [parameters: {'size': 25170, 'id': 'lHGmqUhpTM213W6FwEhvcg', 'md5': '46f6570255e19e3be9883aa63a41ca2b'}]

**Comment by derobert** [comment]
Also, hate to keep filling your inbox, but I just noticed I'm getting 
multiple different statements with a 'database locked' error:

INSERT OR REPLACE INTO files...
INSERT OR REPLACE INTO nodes...
DELETE FROM parentage...

are the ones I've noticed scrolling by the terminal.

**Comment by yadayada** [comment]
Please try the latest dev commit.
